import {TYPES,exampleWorkflow,validateWorkflow,validateGeoJSON,executionPlan,executeWorkflow} from './core.js';
import {mountCanvas} from './build/canvas.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='fieldwork-workflow-v1';
let workflow=exampleWorkflow(),selected='criteria',result=null,runWorkflow=null,busy=false,dirty=true,statuses={},history=[],future=[],flow=null,worker=null,seq=0,lastNodeCount=0,importNode=null;
let toastTimer,activeOutputId=null;
const activeOutput=()=>result?.outputs.find(o=>o.nodeId===activeOutputId)||result?.outputs[0];
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000);}
try{const saved=localStorage.getItem(KEY);if(saved)workflow=validateWorkflow(JSON.parse(saved));}catch{toast('Saved workflow could not be loaded. The example is ready.');}
function save(){try{localStorage.setItem(KEY,JSON.stringify(workflow));$('#save-status').textContent='Saved on this device';}catch{$('#save-status').textContent='Storage unavailable — export to keep';}}
function change(fn,{spatial=true}={}){if(busy)return;const previous=structuredClone(workflow);try{fn(workflow);workflow=validateWorkflow(workflow);history.push(previous);if(history.length>40)history.shift();future=[];if(spatial){dirty=true;statuses={};}save();render();}catch(e){workflow=previous;toast(e.message);render();}}
function describe(n,status){let subtitle=TYPES[n.type].description,detail='Ready';if(['places','centers'].includes(n.type)){subtitle=`${n.params.data.features.length} local locations`;detail='GeoJSON · CRS84';}if(n.type==='policy'){subtitle=`Heat alert + distance > ${n.params.thresholdKm} km`;detail='Evidence → decision';}if(n.type==='alert'){subtitle=n.params.active===null?'Alert status unknown':n.params.active?'Heat alert is active':'No active heat alert';detail=n.params.date;}if(n.type==='nearest'){detail='Kilometers · straight-line';}if(n.type==='output'){subtitle=n.params.view==='table'?'Decision table with evidence':'Map of decisions and locations';detail='Creates a Results tab';}return {definition:TYPES[n.type],type:n.type,label:n.params.label||TYPES[n.type].title,subtitle,detail,status};}
function render(){
  flow?.update(workflow,selected,statuses);$('#node-count').textContent=workflow.nodes.length;$('#undo-button').disabled=!history.length||busy;$('#redo-button').disabled=!future.length||busy;
  $('#workflow-state').textContent=busy?'Running locally…':dirty?(result?'Changed · rerun to update':'Ready to run'):'✓ Run complete';
  $('#run-button').disabled=busy;$('#run-button').innerHTML=busy?'◌ Running…':'<span>▶</span> Run workflow';
  $('#run-summary').textContent=result?(dirty?'Previous run · settings have changed':`${result.outputs.length} outputs · ${Math.round(result.trace.reduce((a,t)=>a+t.milliseconds,0))} ms`):'Run the workflow to see results';
  document.body.classList.toggle('busy',busy);flow?.setBusy(busy);renderInspector();
}
function renderLibrary(search=''){
  let group='';$('#node-library').innerHTML=Object.entries(TYPES).filter(([k,t])=>(t.title+' '+t.description).toLowerCase().includes(search.toLowerCase())).map(([k,t])=>{const heading=t.group!==group?`<div class="library-group">${t.group}</div>`:'';group=t.group;return `${heading}<button class="palette-node ${t.color}" data-add="${k}"><span class="palette-icon">${t.icon}</span><strong>${t.title}</strong><span>+</span></button>`;}).join('');
  $('#node-library').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{
    const type=b.dataset.add,sample=exampleWorkflow().nodes.find(n=>n.type===type);const id=`${type}-${Date.now()}`;
    change(w=>{w.nodes.push({...sample,id,params:type==='output'?{view:'map',label:`Map ${w.nodes.filter(n=>n.type==='output').length+1}`} : sample.params,x:180+(w.nodes.length%4)*80,y:90+(w.nodes.length%3)*80});selected=id;});flow?.fit();toast(`${TYPES[type].title} added. Connect its ports to the workflow.`);
  });
}
function title(n){const t=TYPES[n.type];return `<div class="inspector-title ${t.color}"><span class="node-icon">${t.icon}</span><div><h2>${esc(n.params.label||t.title)}</h2><p>${esc(t.group)} / ${esc(n.id)}</p></div></div>`;}
function renderInspector(){
  if(selected?.startsWith('result:')){renderEvidence(selected.slice(7));return;}
  const n=workflow.nodes.find(n=>n.id===selected);if(!n){$('#inspector-content').innerHTML='<div class="inspector-body"><h2>Your analysis, connected.</h2><p class="description">Choose a node to inspect its settings. Start with the example, or add nodes from the library.</p><div class="notice">The map and decisions use synthetic data. Build a workflow before interpreting its results.</div></div>';return;}
  let content=title(n)+`<p class="description">${esc(TYPES[n.type].description)}. ${n.type==='policy'?'Turn computed spatial evidence into explicit, inspectable conclusions.':''}</p>`;
  if(n.type==='policy'){
    content+=`<span class="inspector-section">Rule settings</span><div class="field"><label class="field-label" for="threshold">Distance threshold</label><div class="input-unit"><input id="threshold" type="number" min="0" max="1000" step="0.5" value="${n.params.thresholdKm}"><span>km</span></div><small>Flag distances strictly greater than this value.</small></div><div class="rule-preview">When the heat alert is <b>active</b><br>and the nearest center is <b>more than ${n.params.thresholdKm} km away</b>,<br>flag the neighborhood for review.</div><span class="inspector-section">Missing evidence</span><p class="description">Missing coordinates, missing centers, or an unknown alert produce “Insufficient data”.</p><div class="inspector-divider"></div><span class="inspector-section">Execution engine</span><div class="engine-card"><span class="engine-mark">⋈</span><div><strong>EYE-JS · Notation3</strong><small>WebAssembly · runs on this device</small></div></div><div class="notice">Illustrative screening criteria. A flag is a reason to review evidence, not a risk estimate or an intervention order.</div>`;
  }else if(n.type==='alert'){
    content+=`<div class="field"><label class="field-label" for="alert-state">Heat alert status</label><select id="alert-state"><option value="true" ${n.params.active===true?'selected':''}>Active</option><option value="false" ${n.params.active===false?'selected':''}>Inactive</option><option value="null" ${n.params.active===null?'selected':''}>Unknown</option></select><label class="field-label" for="assessment-date">Assessment date</label><input id="assessment-date" type="date" value="${n.params.date}"><small>This example supplies a single alert status for all locations on the assessment date. No external alert feed is queried.</small></div>`;
  }else if(['places','centers'].includes(n.type)){
    content+=`<div class="field"><label class="field-label" for="source-label">Source label</label><input id="source-label" maxlength="60" value="${esc(n.params.label)}"></div><div class="detail-row"><span>Records</span><strong>${n.params.data.features.length}</strong></div><div class="detail-row"><span>Coordinates</span><strong>Longitude, latitude · CRS84</strong></div><button id="replace-data" class="button small">↑ Replace with local GeoJSON</button><ul class="record-list">${n.params.data.features.slice(0,12).map(f=>`<li>${esc(f.properties.name)}<span>${f.geometry?'Point':'Missing location'}</span></li>`).join('')}</ul><small class="muted">Point FeatureCollections only, up to 2,000 records. Files stay in this browser.</small>`;
  }else if(n.type==='nearest'){
    content+=`<span class="inspector-section">Spatial operation</span><div class="detail-row"><span>Method</span><strong>Haversine</strong></div><div class="detail-row"><span>Earth model</span><strong>Sphere · 6,371.0088 km</strong></div><div class="detail-row"><span>Units</span><strong>Kilometers</strong></div><div class="rule-preview">For each neighborhood, find the cooling center with the <b>shortest great-circle distance</b>.</div><p class="description">Computed in JavaScript before N3 inference. Source coordinates are longitude and latitude. Full precision is used for classification; the map and table round for display.</p><div class="notice">This is not road distance, travel time, facility availability, or evidence of service access.</div>`;
  }else{
    content+=`<div class="field"><label class="field-label" for="output-label">Results tab name</label><input id="output-label" maxlength="60" value="${esc(n.params.label||'')}"><label class="field-label" for="output-view">Display as</label><select id="output-view"><option value="map" ${n.params.view!=='table'?'selected':''}>Map</option><option value="table" ${n.params.view==='table'?'selected':''}>Table</option></select></div><div class="rule-preview">Each output node creates a named tab in Results. Connect it to the decisions you want to display, then run the workflow.</div><p class="description">All output branches run together. Shared analysis nodes run once. Select a location in either view to inspect its evidence.</p>`;
  }
  const incoming=workflow.edges.filter(e=>e.to===n.id);content+=`<div class="inspector-divider"></div><span class="inspector-section">Connections</span>${incoming.map(e=>`<div class="detail-row"><span>${esc(e.port)}</span><strong>${esc(workflow.nodes.find(x=>x.id===e.from)?.params.label||TYPES[workflow.nodes.find(x=>x.id===e.from).type].title)}</strong></div>`).join('')||'<p class="muted">Source node · no incoming connections</p>'}<div class="inspector-actions"><button id="duplicate-node" class="button small">Duplicate</button><button id="delete-node" class="button small danger">Remove node</button></div>`;
  $('#inspector-content').innerHTML=`<div class="inspector-body">${content}</div>`;
  $('#threshold')?.addEventListener('change',e=>{const value=e.target.value===''?NaN:Number(e.target.value);change(w=>w.nodes.find(x=>x.id===n.id).params.thresholdKm=value);});
  $('#alert-state')?.addEventListener('change',e=>change(w=>w.nodes.find(x=>x.id===n.id).params.active=JSON.parse(e.target.value)));
  $('#assessment-date')?.addEventListener('change',e=>change(w=>w.nodes.find(x=>x.id===n.id).params.date=e.target.value));
  $('#source-label')?.addEventListener('change',e=>change(w=>w.nodes.find(x=>x.id===n.id).params.label=e.target.value.trim()||TYPES[n.type].title));
  $('#replace-data')?.addEventListener('click',()=>{importNode=n.id;$('#geojson-file').click();});
  $('#output-label')?.addEventListener('change',e=>change(w=>w.nodes.find(x=>x.id===n.id).params.label=e.target.value.trim()));
  $('#output-view')?.addEventListener('change',e=>change(w=>w.nodes.find(x=>x.id===n.id).params.view=e.target.value));
  $('#delete-node').onclick=()=>removeNodes([n.id]);
  $('#duplicate-node').onclick=()=>change(w=>{const copy=structuredClone(n);copy.id=`${n.type}-${Date.now()}`;copy.x+=40;copy.y+=90;w.nodes.push(copy);selected=copy.id;});
  if(busy)$('#inspector-content').querySelectorAll('input,select,button').forEach(el=>el.disabled=true);
}
function removeNodes(ids){change(w=>{w.nodes=w.nodes.filter(n=>!ids.includes(n.id));w.edges=w.edges.filter(e=>!ids.includes(e.from)&&!ids.includes(e.to));if(ids.includes(w.outputId))w.outputId=w.nodes.find(n=>n.type==='output')?.id||null;if(ids.includes(selected))selected=null;});}
function renderEvidence(id){
  const result=activeOutput(),row=result?.rows.find(r=>r.id===id);if(!row)return;
  const label=statusLabel(row.status);
  $('#inspector-content').innerHTML=`<div class="inspector-body"><span class="inspector-section">Decision evidence ${dirty?'· previous run':''}</span><h2>${esc(row.name)}</h2><span class="status-pill ${row.status}">${label}</span><p class="description">${esc(row.explanation)}</p><div class="inspector-divider"></div><span class="inspector-section">Inputs used in this run</span><div class="detail-row"><span>Nearest center</span><strong>${esc(row.center?.name||'Unknown')}</strong></div><div class="detail-row"><span>Distance</span><strong>${row.distanceKm===null?'Unknown':row.distanceKm.toFixed(3)+' km'}</strong></div><div class="detail-row"><span>Threshold</span><strong>${result.threshold} km</strong></div><div class="detail-row"><span>Heat alert</span><strong>${result.alert.active===null?'Unknown':result.alert.active?'Active':'Inactive'}</strong></div><div class="detail-row"><span>Assessment date</span><strong>${result.alert.date}</strong></div><div class="rule-preview">${row.status==='Review'?'The N3 rule matched an active alert and a distance above the threshold.':row.status==='Unknown'?'An explicit missing-evidence rule matched. This result is not a negative finding.':'The N3 rule matched an inactive alert or a distance at or below the threshold, with required evidence present.'}</div><span class="inspector-section">Derived assertion</span><pre>&lt;urn:fieldwork:place:${esc(row.id)}&gt;\n  fw:decision fw:${row.status}.</pre><small class="muted">This explanation is assembled from the run inputs and returned assertion. It is not an EYE proof certificate.</small><div class="inspector-actions"><button id="inspect-rules" class="button small">View N3 & evidence ↗</button></div></div>`;
  $('#inspect-rules').onclick=()=>switchView('rules');
}
function statusLabel(status){return {Review:'Review',NoFlag:'No flag',Unknown:'Insufficient data'}[status];}
function renderResults(){
  const output=activeOutput();activeOutputId=output?.nodeId||null;
  $('#result-tabs').innerHTML=(result?.outputs||[]).map(o=>`<button id="result-tab-${esc(o.nodeId)}" role="tab" aria-selected="${o.nodeId===activeOutputId}" tabindex="${o.nodeId===activeOutputId?0:-1}" aria-controls="${o.view}-panel" class="${o.nodeId===activeOutputId?'active':''}" data-output="${esc(o.nodeId)}">${o.view==='table'?'☷':'◈'} ${esc(o.label)}</button>`).join('');
  const tabs=[...$('#result-tabs').querySelectorAll('[data-output]')];
  tabs.forEach((b,i)=>{b.onclick=()=>{activeOutputId=b.dataset.output;if(selected?.startsWith('result:'))selected=null;renderResults();render();$(`#result-tab-${activeOutputId}`).focus();};b.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].click();}};});
  $('#map-panel').hidden=!output||output.view!=='map';$('#table-panel').hidden=!output||output.view!=='table';
  if(output)$(`#${output.view}-panel`).setAttribute('aria-labelledby',`result-tab-${output.nodeId}`);
  $('#results-empty').hidden=!!output;
  const rows=output?.rows||[];$('#result-metrics').innerHTML=output?`<span class="metric review"><b>${rows.filter(r=>r.status==='Review').length}</b> flagged for review</span><span class="metric"><b>${rows.filter(r=>r.status==='NoFlag').length}</b> no flag</span><span class="metric unknown"><b>${rows.filter(r=>r.status==='Unknown').length}</b> insufficient data</span>`:'';
  $('#result-rows').innerHTML=rows.map(r=>`<tr tabindex="0" data-place="${esc(r.id)}"><td>${esc(r.name)}</td><td>${esc(r.center?.name||'—')}</td><td>${r.distanceKm===null?'—':r.distanceKm.toFixed(2)+' km'}</td><td><span class="status-pill ${r.status}">${statusLabel(r.status)}</span></td></tr>`).join('');
  $('#result-rows').querySelectorAll('[data-place]').forEach(el=>{el.onclick=()=>selectResult(el.dataset.place);el.onkeydown=e=>{if(e.key==='Enter')selectResult(el.dataset.place);};});
  renderMap();
  if(result){$('#n3-preview').textContent=result.receipts.map(r=>`# RULE NODE: ${r.nodeId}\n${r.input}\n# DERIVED CONCLUSIONS\n${r.conclusions.map(q=>`<${q.subject}> <${q.predicate}> <${q.object}> .`).join('\n')}`).join('\n\n');}
}
function selectResult(id){selected=`result:${id}`;flow?.update(workflow,null,statuses);renderInspector();renderMap();}
function renderMap(){
  const result=activeOutput(),svg=$('#map'), rows=result?.rows||[], centers=result?.centers||[], points=[...rows.filter(r=>r.coordinates).map(r=>r.coordinates),...centers.filter(c=>c.geometry).map(c=>c.geometry.coordinates)];
  if(!points.length){svg.innerHTML='<text x="425" y="140" text-anchor="middle">Run the workflow to map its local results.</text>';return;}
  let minX=Math.min(...points.map(p=>p[0])),maxX=Math.max(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxY=Math.max(...points.map(p=>p[1]));
  const midY=(minY+maxY)/2,cos=Math.max(.05,Math.cos(midY*Math.PI/180)),width=Math.max((maxX-minX)*cos,.01),height=Math.max(maxY-minY,.01),scale=Math.min(660/width,210/height);
  const midX=(minX+maxX)/2,proj=c=>[425+(c[0]-midX)*cos*scale,142-(c[1]-midY)*scale];
  const grid=Array.from({length:12},(_,i)=>`<path class="gridline" d="M${i*80} 0V295"/>`).join('')+Array.from({length:5},(_,i)=>`<path class="gridline" d="M0 ${i*65}H850"/>`).join('');
  const focus=rows.find(r=>`result:${r.id}`===selected);
  let content=`<rect width="850" height="295" fill="#f0f3e9"/>${grid}<path d="M15 252 C110 140 158 268 261 142 S432 34 536 155 S710 244 844 67" fill="none" stroke="#e0e8d5" stroke-width="60" opacity=".5"/><path d="M15 252 C110 140 158 268 261 142 S432 34 536 155 S710 244 844 67" fill="none" stroke="#e6eddc" stroke-width="30"/><text x="20" y="24" style="letter-spacing:1.5px;font-size:9px">LOCAL SPATIAL PREVIEW</text><text x="815" y="30" text-anchor="middle">N</text><path d="M815 37l-4 13 4-3 4 3z" fill="#86987b"/>`;
  if(focus?.coordinates&&focus.center){const a=proj(focus.coordinates),b=proj(focus.center.coordinates);content+=`<path d="M${a.join(' ')}L${b.join(' ')}" stroke="#698b78" stroke-dasharray="4 4" stroke-width="1.5"/>`;}
  for(const c of centers){if(!c.geometry)continue;const [x,y]=proj(c.geometry.coordinates),radius=result.threshold/111.195*scale;content+=`<circle cx="${x}" cy="${y}" r="${radius}" fill="#abc2a0" opacity=".10"/><circle cx="${x}" cy="${y}" r="${radius}" fill="none" stroke="#a0b596" stroke-dasharray="3 5" opacity=".6"/><rect x="${x-6}" y="${y-6}" width="12" height="12" rx="2" fill="#3e6860" stroke="white" stroke-width="2"/><text x="${x+11}" y="${y+17}" style="font-size:9px">${esc(c.properties.name)}</text>`;}
  for(const r of rows){if(!r.coordinates)continue;const [x,y]=proj(r.coordinates),color={Review:'#c18b4f',NoFlag:'#699178',Unknown:'#a89b87'}[r.status];content+=`<g class="location" data-place="${esc(r.id)}" tabindex="0" role="button" aria-label="${esc(r.name)}, ${statusLabel(r.status)}"><title>${esc(r.name)} · ${statusLabel(r.status)} · ${r.distanceKm?.toFixed(2)??'Unknown'} km</title>${focus?.id===r.id?`<circle cx="${x}" cy="${y}" r="12" fill="none" stroke="${color}" opacity=".7"/>`:''}<circle cx="${x}" cy="${y}" r="6" fill="${color}" stroke="white" stroke-width="2"/><text class="location-label" x="${x+10}" y="${y-8}">${esc(r.name)}</text></g>`;}
  content+=`<text x="20" y="276" style="font-size:9px">${minX.toFixed(3)}° to ${maxX.toFixed(3)}° longitude · circles show ${result.threshold} km (approx.)</text>`;
  const missing=rows.filter(r=>!r.coordinates).length;if(missing)content+=`<text x="830" y="276" text-anchor="end" style="font-size:9px">${missing} unmapped · see table</text>`;
  svg.innerHTML=content;svg.querySelectorAll('[data-place]').forEach(el=>{el.onclick=()=>selectResult(el.dataset.place);el.onkeydown=e=>{if(e.key==='Enter')selectResult(el.dataset.place);};});
}
function reason(input){return new Promise((resolve,reject)=>{
  if(!worker)worker=new Worker('./reasoning-worker.js');const id=++seq;
  const timeout=setTimeout(()=>{worker.terminate();worker=null;reject(new Error('Reasoning exceeded 45 seconds. Reduce the dataset and try again.'));},45000);
  worker.onmessage=({data})=>{if(data.id!==id)return;clearTimeout(timeout);if(data.error)reject(new Error(data.error));else resolve(data.quads);};
  worker.onerror=e=>{clearTimeout(timeout);worker?.terminate();worker=null;reject(new Error(`Reasoning worker failed: ${e.message}`));};worker.postMessage({id,input});
});}
async function run(){if(busy)return;try{executionPlan(workflow);}catch(e){toast(e.message);return;}busy=true;statuses={};render();const snapshot=structuredClone(workflow);try{const next=await executeWorkflow(snapshot,reason,(id,state)=>{statuses[id]=state;flow?.update(workflow,selected,statuses);});result=next;runWorkflow=snapshot;dirty=false;renderResults();toast(`Complete: ${result.outputs.length} output tabs updated.`);}catch(e){toast(`Workflow stopped: ${e.message}`);$('#workflow-state').textContent='Run failed';console.error(e);}finally{busy=false;render();}}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function switchView(view){$('#workflow-view').hidden=view!=='workflow';$('#rules-view').hidden=view!=='rules';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function validConnection(c){const a=workflow.nodes.find(n=>n.id===c.source),b=workflow.nodes.find(n=>n.id===c.target);return !!a&&!!b&&a.id!==b.id&&!!TYPES[a.type].output&&TYPES[b.type].inputs.find(([p])=>p===c.targetHandle)?.[1]===TYPES[a.type].output;}
mountCanvas($('#canvas'),{describe,ready(api){flow=api;render();setTimeout(()=>flow.fit(),80);},select(id){selected=id;render();},clear(){selected=null;render();},move(id,p){change(w=>Object.assign(w.nodes.find(n=>n.id===id),{x:p.x,y:p.y}),{spatial:false});},connect(c){change(w=>{w.edges=w.edges.filter(e=>!(e.to===c.target&&e.port===c.targetHandle));w.edges.push({id:`e-${Date.now()}`,from:c.source,to:c.target,port:c.targetHandle});});},valid:validConnection,remove:removeNodes,removeEdges(ids){change(w=>w.edges=w.edges.filter(e=>!ids.includes(e.id)));},zoom(z){$('#zoom-value').textContent=`${Math.round(z*100)}%`;}});
$('#run-button').onclick=run;$('#node-search').oninput=e=>renderLibrary(e.target.value);$('#zoom-in').onclick=()=>flow?.zoomIn();$('#zoom-out').onclick=()=>flow?.zoomOut();$('#fit-button').onclick=()=>flow?.fit();
$('#undo-button').onclick=()=>{if(busy||!history.length)return;future.push(structuredClone(workflow));workflow=history.pop();dirty=true;statuses={};save();render();};
$('#redo-button').onclick=()=>{if(busy||!future.length)return;history.push(structuredClone(workflow));workflow=future.pop();dirty=true;statuses={};save();render();};
$('#reset-button').onclick=()=>{change(w=>{Object.assign(w,exampleWorkflow());selected='criteria';});flow?.fit();};
$('#export-button').onclick=()=>download('fieldwork-workflow.json',JSON.stringify(workflow,null,2));$('#import-button').onclick=()=>$('#workflow-file').click();
$('#workflow-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw new Error('Workflow file is too large (5 MB maximum).');const next=validateWorkflow(JSON.parse(await file.text()));change(w=>{Object.assign(w,next);selected=next.outputId;});flow?.fit();toast('Workflow imported. Run it to update results.');}catch(err){toast(err.message);}e.target.value='';};
$('#geojson-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw new Error('GeoJSON file is too large (5 MB maximum).');const data=validateGeoJSON(JSON.parse(await file.text()));change(w=>{const n=w.nodes.find(n=>n.id===importNode);if(!n)throw new Error('Source node no longer exists.');n.params.data=data;});toast('Local geographic data loaded. Run to update results.');}catch(err){toast(err.message);}e.target.value='';};
$('#download-evidence').onclick=()=>{if(!result){toast('Run the workflow first.');return;}download('fieldwork-run-receipt.json',JSON.stringify({schema:'fieldwork/run/1',workflow:runWorkflow,...result},null,2));};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('#help-button').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){e.preventDefault();$(e.shiftKey?'#redo-button':'#undo-button').click();}});
renderLibrary();renderResults();save();render();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(async()=>{const ok=!!(await caches.match('./vendor/eye-21.1.24.js'));$('#offline-status').innerHTML=ok?'<i></i> Available offline':'<i></i> Offline setup incomplete';}).catch(()=>{$('#offline-status').textContent='Offline cache unavailable';});}else{$('#offline-status').textContent='Offline cache unsupported';}
setTimeout(run,350);
