import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {blankWorkflow,newStudyArea,bboxPolygon} from '../build/study-area.js';
import {calculateArea,formatArea,AREA_UNITS} from '../build/area-computation.js';
import {coverageExercise} from '../build/spatial-coverage.js';
test("Area enrichment, units, evidence and offline recomputation",async({page,context})=>{
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));
const run=async()=>{await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});};
const select=async id=>{await page.locator('[data-view="workflow"]').click();await page.locator(`.react-flow__node[data-id="${id}"]`).click();};
  const w=blankWorkflow(),geometry=bboxPolygon(25.89,-24.7,25.91,-24.68);
  w.nodes=[{...newStudyArea(),id:'area-test',x:50,y:70}];w.nodes[0].params={...w.nodes[0].params,label:'Area experiment',selectionMode:'bbox',geometry};
  await page.goto('/?example=blank');
  await page.locator('#workflow-file').setInputFiles({name:'area.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
  await page.locator('[data-add="measure_area"]').click();
  await expect(page.locator('#area-unit')).toHaveValue('km2');
  await page.locator('#measure-area-source').selectOption('area-test');
  await expect(page.locator('.react-flow__edge')).toHaveCount(1);
  const measureId=(await saved()).nodes.find(n=>n.type==='measure_area').id;
  for(const unit of Object.keys(AREA_UNITS)){
    await page.locator('#area-unit').selectOption(unit);await run();
    await expect(page.locator('#result-metrics')).toContainText(formatArea(calculateArea(geometry,unit)));
  }
  await page.locator('[data-view="rules"]').click();await expect(page.locator('#n3-preview')).toContainText('COMPUTED FACTS (not inferred)');await expect(page.locator('#n3-preview')).toContainText('geo:hasMetricArea');
  const download=page.waitForEvent('download');await page.locator('#download-evidence').click();const receipt=JSON.parse(await readFile(await (await download).path(),'utf8'));
  assert.equal(receipt.outputs[0].measurement.squareMetres,calculateArea(geometry).squareMetres);
  assert.equal(receipt.receipts.filter(r=>r.kind==='computation').length,1);assert.equal(receipt.outputs[0].geometryId,'urn:fieldwork:geometry:area-test');
  // Parse the actual ontology and generated measurement RDF with the bundled engine.
  // This rule only checks linkage; it does not ask EYE to calculate the numeric area.
  const ontology=await readFile('ontology/fieldwork.ttl','utf8');
  const computed=receipt.receipts.find(r=>r.kind==='computation');
  const quads=await page.evaluate(async input=>{const worker=new Worker('./build/reasoning-worker.js');return await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{worker.terminate();data.error?reject(new Error(data.error)):resolve(data.quads);};worker.onerror=e=>{worker.terminate();reject(new Error(e.message));};worker.postMessage({id:1,input});});},ontology+'\n'+computed.facts+'\n{ ?activity prov:generated ?measurement. ?measurement a fw:AreaMeasurement; qudt:unit <http://qudt.org/vocab/unit/M2>. } => { ?activity <urn:test:measurementLinked> true. }.');
  assert.equal(quads.filter(q=>q.predicate==='urn:test:measurementLinked'&&q.object==='true').length,1);
  await select('area-test');await page.locator('#edit-study-area').click();await page.locator('#area-online').uncheck();
  await page.getByText('Enter bounding coordinates',{exact:true}).click();await page.locator('#area-east').fill('25.9');await page.locator('#area-use-bounds').click();await page.locator('#area-apply').click();
  await expect(page.locator('#workflow-state')).toContainText('Changed');await run();
  const smaller=bboxPolygon(25.89,-24.7,25.9,-24.68);await expect(page.locator('#result-metrics')).toContainText(formatArea(calculateArea(smaller,'mi2')));
  await select(measureId);await page.locator('#area-unit').selectOption('acre');await run();
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/area-computation-desktop.png',fullPage:true});
  const exported=page.waitForEvent('download');await page.locator('#export-button').click();const workflowBytes=await readFile(await (await exported).path());
  await page.locator('#new-workflow').click();await page.locator('#workflow-file').setInputFiles({name:'saved-area.json',mimeType:'application/json',buffer:workflowBytes});await run();
  await expect(page.locator('#offline-status')).toContainText('Available offline');await context.setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});
  await select(measureId);await expect(page.locator('#area-unit')).toHaveValue('acre');await expect(page.locator('#result-metrics')).toContainText(formatArea(calculateArea(smaller,'acre')));
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'test-results/area-computation-mobile.png',fullPage:true});
  await context.setOffline(false);await page.setViewportSize({width:1600,height:1100});
  await page.locator('#workflow-file').setInputFiles({name:'coverage.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(coverageExercise()))});
  await expect(page.locator('#run-button')).toBeEnabled();await page.locator('[data-view="workflow"]').click();
  await page.locator('[data-add="measure_area"]').click();
  await page.locator('#measure-area-source').selectOption('scope');
  const chainedId=(await saved()).nodes.find(n=>n.type==='measure_area').id;
  await select('coverage');await page.locator('#coverage-area').selectOption(chainedId);await run();
  await expect(page.locator('.react-flow__edge')).toHaveCount(3);
  await expect(page.locator('#coverage-alert')).toContainText('2 records');
  const downloadChain=async()=>{await page.locator('[data-view="rules"]').click();const pending=page.waitForEvent('download');await page.locator('#download-evidence').click();return JSON.parse(await readFile(await (await pending).path(),'utf8'));};
  const chained=await downloadChain(),check=chained.outputs.find(o=>o.kind==='spatial-coverage');
  assert.equal(check.areaId,'urn:fieldwork:area:scope');assert.equal(check.areaNodeId,'scope');assert.equal(check.geometryId,'urn:fieldwork:geometry:scope');
  assert.equal(check.measurement.squareMetres,calculateArea(geometry).squareMetres);
  assert.deepEqual(check.rows.map(r=>r.decision),['Accept','Accept','Review','Review']);
  assert.match(chained.receipts.find(r=>r.nodeId==='coverage').input,/geo:hasMetricArea/);
  await select('scope');await page.locator('#edit-study-area').click();await page.locator('#area-online').uncheck();
  await page.getByText('Enter bounding coordinates',{exact:true}).click();await page.locator('#area-east').fill('25.925');await page.locator('#area-use-bounds').click();await page.locator('#area-apply').click();await run();
  await expect(page.locator('#coverage-alert')).toContainText('1 records');
  const expanded=await downloadChain(),expandedCheck=expanded.outputs.find(o=>o.kind==='spatial-coverage');
  assert.ok(expandedCheck.measurement.squareMetres>check.measurement.squareMetres);
  assert.equal(expandedCheck.rows.find(r=>r.id==='outside').decision,'Accept');
  await select('coverage');await page.screenshot({path:'test-results/area-enriched-coverage.png',fullPage:true});
  const chainWorkflow=await saved();await page.reload();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});
  assert.deepEqual((await saved()).edges,chainWorkflow.edges);
  await page.locator('#workflow-file').setInputFiles({name:'enriched-area.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(chainWorkflow))});await run();
  await expect(page.locator('#coverage-alert')).toContainText('1 records');
  assert.deepEqual(errors,[]);console.log('PASS: separate area computation, visible connector, all six units, GeoSPARQL facts, boundary invalidation, receipt, export/import, offline recomputation and mobile layout.');
});
