import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));

test('canvas selection reveals and highlights its library primitive without adding a node',async({page})=>{
  await page.goto('/?example=snow-voronoi');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});
  const before=await saved(page);await page.locator('#node-search').fill('raster');
  await page.locator('.react-flow__node[data-id="catchments"]').click();
  await expect(page.locator('#node-search')).toHaveValue('');await expect(page.locator('[data-add="voronoi"]')).toHaveAttribute('aria-current','true');
  await expect(page.locator('.primitive-selected')).toHaveCount(1);
  await page.locator('.react-flow__node[data-id="pumps"]').click();await expect(page.locator('[data-add="observations"]')).toHaveClass(/primitive-selected/);await expect(page.locator('[data-add="voronoi"]')).toHaveAttribute('aria-current','false');
  await page.locator('.react-flow__node[data-id="locations"]').click();await expect(page.locator('[data-add="observations"]')).toHaveClass(/primitive-selected/);
  assert.equal((await saved(page)).nodes.length,before.nodes.length);
  await page.locator('.react-flow__pane').click({position:{x:10,y:10}});await expect(page.locator('.primitive-selected')).toHaveCount(0);
});
test('John Snow examples use shared primitives, persist parameters and replay offline',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/?example=snow-voronoi');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map [data-catchment]')).toHaveCount(8);await expect(page.locator('#result-metrics')).toContainText('250 matched');
  await page.locator('#result-tab-table').click();await expect(page.locator('#result-rows')).toContainText('340');await expect(page.locator('#result-head')).toContainText('locations');await page.locator('#result-tab-chart').click();await expect(page.locator('#bars-panel')).toContainText('Sum DEATHS');
  await page.locator('.react-flow__node[data-id="summary"]').click();await page.locator('#catchment-valueField').fill('');await page.locator('#catchment-valueField').blur();await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete');await expect(page.locator('#bars-panel')).toContainText('Location memberships');
  const before=await saved(page);await page.locator('#example-select').selectOption('snow-isochrone');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map [data-catchment]')).toHaveCount(4);await expect(page.locator('#result-metrics')).toContainText('250 matched');await expect(page.locator('#map [data-plot-site]')).toHaveCount(8);await expect(page.locator('#map [data-plot-observation]')).toHaveCount(250);
  const downloadPromise=page.waitForEvent('download');await page.locator('#catchment-plot-download').click();assert.equal((await downloadPromise).suggestedFilename(),'catchment-plot.svg');await page.locator('#expand-results').click();await page.screenshot({path:'test-results/nb04-fieldwork-plot.png'});
  let tiles=0;await page.route('https://tile.openstreetmap.org/**',async route=>{tiles++;await route.abort();});await page.locator('#result-tab-interactive').click();await expect(page.locator('.catchment-leaflet')).toBeVisible();await expect(page.locator('.catchment-site-marker')).toHaveCount(8);assert.equal(tiles,0);await page.locator('[data-basemap]').check();await expect(page.locator('[data-tile-status]')).toContainText('unavailable');assert.ok(tiles>0);await page.locator('[data-basemap]').uncheck();await page.locator('[data-fullscreen]').click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.id)).toBe('catchment-map-host');await page.evaluate(()=>document.exitFullscreen());await page.locator('.catchment-site-marker').first().click();await expect(page.locator('.leaflet-popup-content')).toContainText('Location');await page.locator('.leaflet-popup-close-button').click();await page.locator('.leaflet-control-layers-selector').first().uncheck();await page.locator('[data-fit]').click();await page.screenshot({path:'test-results/nb04-fieldwork-interactive.png'});await page.locator('#expand-results').click();await page.locator('#result-tab-map').click();await expect(page.locator('.catchment-leaflet')).toHaveCount(0);
  await page.locator('.react-flow__node[data-id="catchments"]').click();await expect(page.locator('#catchment-minutes')).toHaveValue('5');await page.locator('#catchment-thresholds').fill('');await page.locator('#catchment-thresholds').blur();await page.locator('#catchment-minutes').fill('1');await page.locator('#catchment-minutes').blur();await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map-note')).toContainText('1 min');
  await page.screenshot({path:'test-results/john-snow-isochrone.png'});
  await expect(page.locator('#offline-status')).toContainText('Available offline',{timeout:30000});await page.context().setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map-note')).toContainText('1 min');await page.locator('#result-tab-interactive').click();await expect(page.locator('.catchment-leaflet')).toBeVisible();await expect(page.locator('.catchment-site-marker')).toHaveCount(8);await page.locator('.leaflet-control-zoom-in').click();
  await page.locator('#example-select').selectOption('snow-voronoi');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});assert.deepEqual((await saved(page)).nodes,before.nodes);await page.screenshot({path:'test-results/john-snow-voronoi.png'});assert.deepEqual(errors,[]);
});
test('Street network imports GraphML and rejects invalid uploads without replacing saved data',async({page})=>{
  await page.goto('/?example=blank');await page.locator('[data-add="network_input"]').click();
  const xml='<graphml><key id="crs" attr.name="crs"/><key id="x" attr.name="x"/><key id="y" attr.name="y"/><key id="l" attr.name="length"/><graph edgedefault="directed"><data key="crs">EPSG:4326</data><node id="a"><data key="x">-.136</data><data key="y">51.513</data></node><node id="b"><data key="x">-.135</data><data key="y">51.513</data></node><edge source="a" target="b"><data key="l">70</data></edge></graph></graphml>';
  await page.locator('#network-upload').setInputFiles({name:'tiny.graphml',mimeType:'application/xml',buffer:Buffer.from(xml)});await expect(page.locator('#inspector-content')).toContainText('2 nodes');const w=await saved(page),node=w.nodes.find(n=>n.type==='network_input');assert.equal(node.params.data.edges.length,1);assert.equal(node.params.data.provenance.sha256.length,64);
  await page.locator('#network-upload').setInputFiles({name:'invalid.graphml',mimeType:'application/xml',buffer:Buffer.from(xml.replace('EPSG:4326','EPSG:3857'))});await expect(page.locator('#toast')).toContainText('WGS84');assert.deepEqual((await saved(page)).nodes,w.nodes);
});
test('Street network downloads bounded OSM data explicitly, preserves failed downloads and acquisition provenance',async({page})=>{
  await page.clock.install();
  await page.goto('/?example=snow-isochrone');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});
  let requests=0;await page.route('https://overpass-api.de/api/interpreter',async route=>{requests++;assert.match(route.request().postData(),/data=/);await route.fulfill({json:{elements:[{type:'node',id:1,lon:-.136668,lat:51.513341},{type:'node',id:2,lon:-.135,lat:51.513341},{type:'way',id:3,nodes:[1,2],tags:{highway:'footway'}}]}});});
  await page.locator('.react-flow__node[data-id="network"]').click();await page.locator('#network-input-method').selectOption('osm');assert.equal(requests,0);await page.locator('#download-network').click();await expect(page.locator('#inspector-content')).toContainText('2 nodes');assert.equal(requests,1);const w=await saved(page),data=w.nodes.find(n=>n.type==='network_input').params.data;assert.equal(data.provenance.provider,'OpenStreetMap');assert.ok(data.provenance.bounds[0]<-.142);assert.ok(data.provenance.boundary.coordinates.length);
  await expect(page.locator('#download-network')).toBeDisabled();await expect(page.locator('#network-download-status')).toContainText('seconds');await page.clock.fastForward(61000);await expect(page.locator('#download-network')).toBeEnabled();
  await page.unroute('https://overpass-api.de/api/interpreter');await page.route('https://overpass-api.de/api/interpreter',route=>route.fulfill({status:429,body:'Rate limited'}));await page.locator('#download-network').click();await expect(page.locator('#toast')).toContainText('HTTP 429');assert.deepEqual((await saved(page)).nodes,w.nodes);
});
test('sized study boundaries and independent buffer preserve reporting geometry',async({page})=>{
  await page.goto('/?example=snow-voronoi');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await page.locator('.react-flow__node[data-id="study"]').click();await page.locator('#edit-study-area').click();await page.locator('#area-online').uncheck();await page.locator('#area-sized-box summary').click();await page.locator('#area-box-shape').selectOption('square');await page.locator('#area-box-width').fill('1000');await page.locator('#area-box-create').click();await page.locator('#area-apply').click();
  let w=await saved(page),area=w.nodes.find(n=>n.id==='study');assert.equal(area.params.selectionMode,'bbox');const original=area.params.geometry;
  await page.locator('[data-add="buffer_area"]').click();await expect(page.locator('#catchment-distanceM')).toHaveValue('500');await page.locator('#catchment-distanceM').fill('750');await page.locator('#catchment-distanceM').blur();w=await saved(page);assert.deepEqual(w.nodes.find(n=>n.id==='study').params.geometry,original);assert.equal(w.nodes.find(n=>n.type==='buffer_area').params.distanceM,750);
  await page.locator('.react-flow__node[data-id="study"]').click();await page.locator('#edit-study-area').click();await page.locator('#area-sized-box summary').click();await page.locator('#area-box-shape').selectOption('rectangle');await page.locator('#area-box-width').fill('2000');await page.locator('#area-box-height').fill('1000');await page.locator('#area-box-create').click();await page.locator('#area-apply').click();w=await saved(page);const ring=w.nodes.find(n=>n.id==='study').params.geometry.coordinates[0];assert.ok(ring[1][0]-ring[0][0]>original.coordinates[0][1][0]-original.coordinates[0][0][0]);
});
