import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const secret='test-key-not-real-837492',password='synthetic long passphrase';
test('credential file round trip stays outside persistent project state and locks on reload',async({page})=>{
 await page.goto('/?example=blank');await page.locator('#credentials-button').click();await page.locator('#credential-new').click();await page.locator('#credential-ref').fill('healthsites-personal');await page.locator('#credential-label').fill('Personal key');await page.locator('#credential-secret').fill(secret);await page.locator('#credential-add').click();await expect(page.locator('#credential-secret')).toHaveValue('');await expect(page.locator('#credential-list')).toContainText('Personal key');await expect(page.locator('#credential-list')).not.toContainText(secret);
 await page.locator('#credential-password').fill(password);await page.locator('#credential-confirm').fill('different');await page.locator('#credential-download').click();await expect(page.locator('#credential-error')).toContainText('do not match');await page.locator('#credential-confirm').fill(password);const download=page.waitForEvent('download');await page.locator('#credential-download').click();const bytes=await readFile(await(await download).path());assert.ok(!bytes.toString().includes(secret));await expect(page.locator('#credential-password')).toHaveValue('');
 const stored=await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}));assert.ok(!stored.includes(secret));assert.ok(!stored.includes(password));assert.ok(!stored.includes('healthsites-personal'));
 const persisted=await page.evaluate(async()=>{const records=[];for(const info of await indexedDB.databases()){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{for(const name of db.objectStoreNames)records.push(await new Promise((resolve,reject)=>{const r=db.transaction(name,'readonly').objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));}finally{db.close();}}return JSON.stringify(records);});assert.ok(!persisted.includes(secret));assert.ok(!persisted.includes(password));assert.ok(!persisted.includes('healthsites-personal'));
 await page.locator('#credential-close').click();await expect(page.locator('#credential-dialog')).toHaveCount(0);await expect(page.locator('#credentials-button')).toContainText('unlocked');const exported=page.waitForEvent('download');await page.locator('#export-button').click();const project=await readFile(await(await exported).path(),'utf8');assert.ok(!project.includes(secret));assert.ok(!project.includes('healthsites-personal'));await page.reload();await expect(page.locator('#credentials-button')).toHaveText('Credentials');
 await expect(page.locator('#offline-status')).toContainText('Available offline');await page.context().setOffline(true);await page.locator('#credentials-button').click();await page.locator('#credential-file').setInputFiles({name:'keys.fwcredentials',mimeType:'application/octet-stream',buffer:bytes});await page.locator('#credential-password').fill('wrong');await page.locator('#credential-unlock').click();await expect(page.locator('#credential-error')).toContainText('Could not unlock');await page.locator('#credential-password').fill(password);await page.locator('#credential-unlock').click();await expect(page.locator('#credential-list')).toContainText('Personal key');
 await page.getByRole('button',{name:'Delete healthsites-personal',exact:true}).click();await expect(page.locator('#credential-status')).toContainText('0 credentials');await page.locator('#credential-lock').click();await expect(page.locator('#credential-dialog')).toHaveCount(0);await expect(page.locator('#credentials-button')).toHaveText('Credentials');await page.locator('#credentials-button').click();await expect(page.locator('#credential-password')).toHaveValue('');await page.screenshot({path:'test-results/credentials-dialog.png'});
});
test('inactivity locks credentials and clears the dialog',async({page})=>{
 await page.clock.install();await page.goto('/?example=blank');await page.locator('#credentials-button').click();await page.locator('#credential-new').click();await page.locator('#credential-secret').fill(secret);await page.clock.fastForward(16*60*1000);await expect(page.locator('#credential-dialog')).toHaveCount(0);await expect(page.locator('#credentials-button')).toHaveText('Credentials');
});
test('closing during unlock cannot restore a cancelled credential operation',async({page})=>{
 const {encryptCredentials}=await import('../build/credentials.js'),blob=await encryptCredentials([{ref:'example',provider:'healthsites',label:'Example',origin:'https://healthsites.io',secret}],password);
 await page.goto('/?example=blank');await page.locator('#credentials-button').click();await page.locator('#credential-file').setInputFiles({name:'keys.fwcredentials',mimeType:'application/octet-stream',buffer:Buffer.from(await blob.arrayBuffer())});await page.locator('#credential-password').fill(password);
 await page.evaluate(()=>{const original=crypto.subtle.deriveKey.bind(crypto.subtle);crypto.subtle.deriveKey=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,500));return original(...args);};});await page.locator('#credential-unlock').click();await page.locator('#credential-close').click();await page.waitForTimeout(800);await expect(page.locator('#credentials-button')).toHaveText('Credentials');await page.locator('#credentials-button').click();await expect(page.locator('#credential-list')).toBeEmpty();await expect(page.locator('#credential-password')).toHaveValue('');
});
