import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {validateWorkflow,executionPlan,distanceKm} from '../build/core.js';
import {oldNalediWorkflow,executeOldNode} from '../build/old-naledi.js';
import {boundary,facilities} from '../examples/old-naledi/data.js';
import {Parser} from 'n3';
const legacy=JSON.parse(await readFile(new URL('./fixtures/old-naledi-source-2026-10-06.json',import.meta.url),'utf8'));
test('legacy registry splits once, preserving outgoing edges and respecting deliberate disconnection',()=>{
  const original=structuredClone(legacy),w=validateWorkflow(legacy);
  assert.deepEqual(legacy,original);assert.equal(w.nodes.length,legacy.nodes.length+1);
  assert.deepEqual(w.edges.slice(0,legacy.edges.length),legacy.edges);
  const source=w.nodes.find(n=>n.type==='observations');assert.equal(source.params.data.features.length,214);
  assert.equal(source.params.sourceInfo.commit,'7f183843075a6534b6699cd107cc74def1315bcd');
  assert.deepEqual(validateWorkflow(w),w);
  w.edges=w.edges.filter(e=>e.port!=='points');
  assert.throws(()=>executionPlan(w),/points input connected/);
  assert.equal(validateWorkflow(w).nodes.length,w.nodes.length);
  const collision=structuredClone(legacy);collision.nodes.push({...source,id:'facility-input-1'});
  assert.ok(validateWorkflow(collision).nodes.some(n=>n.id==='facility-input-2'));
});
test('connected selection preserves the historical candidate set and actually uses edited input',async()=>{
  const w=validateWorkflow(oldNalediWorkflow()),node=w.nodes.find(n=>n.type==='facilities');
  const source=w.nodes.find(n=>n.id==='facility-data');
  const points={...source.params.data,sourceNodeId:source.id,sourceInfo:source.params.sourceInfo};
  const inputs={area:{boundary,areaId:'urn:test:area'},points};const receipts=[];
  const result=await executeOldNode(node,inputs,()=>{throw Error('Selection must not invoke reasoning');},receipts,distanceKm);
  const coords=boundary.type==='MultiPolygon'?boundary.coordinates.flat(2):boundary.coordinates.flat();const origin=[(Math.min(...coords.map(p=>p[0]))+Math.max(...coords.map(p=>p[0])))/2,(Math.min(...coords.map(p=>p[1]))+Math.max(...coords.map(p=>p[1])))/2];
  const expected=facilities.filter(f=>distanceKm(origin,f.coordinates)<=6);
  assert.deepEqual(result.facilities.map(({attributes,...f})=>f),expected);
  assert.equal(receipts[0].kind,'computation');assert.match(receipts[0].facts,/fw:NearbyFacilitySelection/);
  const quads=new Parser().parse(receipts[0].facts);
  assert.equal(quads.find(q=>q.predicate.value==='urn:fieldwork:selectedRecordCount').object.value,String(expected.length));
  assert.equal(quads.filter(q=>q.predicate.value==='http://www.w3.org/ns/prov#used').length,2);
  inputs.points={...points,features:[{...points.features[0],geometry:null}]};
  const missing=await executeOldNode(node,inputs,()=>{},[],distanceKm);
  assert.equal(missing.facilities.length,0);assert.equal(missing.facilitySource.missingLocationCount,1);
  inputs.points={...points,features:[{...points.features[0],properties:{name:'Incomplete'}}]};
  await assert.rejects(executeOldNode(node,inputs,()=>{},[],distanceKm),/owner and serviceType/);
});
