import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
test("Old Naledi evidence and diagnostic access workflows",async({page,context})=>{
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const done=()=>expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});
const run=async()=>{await page.locator('#run-button').click();await done();};
const select=async id=>{await page.locator('[data-view="workflow"]').click();await page.locator(`.react-flow__node[data-id="${id}"]`).click();};
const number=async(id,value)=>{await page.locator(id).fill(String(value));await page.locator(id).press('Tab');};
  await page.goto('/?example=old-naledi');await done();
  await expect(page.getByRole('tab')).toHaveCount(4);
  await expect(page.locator('#result-metrics .review b')).toHaveText('21');
  await expect(page.locator('#map path[fill-rule="evenodd"]')).toHaveCount(1);
  await page.getByRole('tab',{name:'Facility evidence'}).click();
  await page.locator('#result-search').fill('Old Naledi');await expect(page.locator('#result-rows tr:visible')).toHaveCount(1);
  await page.locator('#result-search').fill('');
  const clinic=page.locator('#result-rows tr').filter({hasText:'Old Naledi Clinic'});
  await expect(clinic).toContainText('Inferential');await expect(clinic).toContainText('Onsite or referral');
  await expect(page.locator('#result-rows tr').filter({hasText:'Princess Marina Hospital'})).toContainText('Direct');
  await clinic.click();await expect(page.locator('#inspector-content')).toContainText('Dickinson 2017');
  await page.getByRole('tab',{name:'Access zones'}).click();await expect(page.locator('#bars-panel')).toBeVisible();
  await expect(page.locator('#bars-panel .bar-row').filter({hasText:'> 30 min'}).locator('b')).toHaveText('21');
  await select('access');await page.locator('#param-minimumEvidence').selectOption('inferential');await page.locator('#param-service').selectOption('anyKnown');await run();
  await page.getByRole('tab',{name:'Access map'}).click();await expect(page.locator('#result-metrics .review b')).toHaveText('0');
  await page.locator('#map [data-place="sample-1"]').click();await expect(page.locator('#inspector-content')).toContainText('Generated grid location');
  await page.locator('#expand-results').click();await expect(page.locator('#workflow-view')).toBeHidden();
  await page.locator('#expand-results').click();await expect(page.locator('#workflow-view')).toBeVisible();
  await select('access');await page.locator('#param-minimumEvidence').selectOption('direct');
  await select('facilities');await number('#param-radiusKm',1);await run();
  await expect(page.locator('#result-metrics .unknown b')).toHaveText('21');
  // Switching examples preserves their independent local edits.
  await page.locator('#example-select').selectOption('heat');await done();
  await number('#threshold',7);await run();
  await page.locator('#example-select').selectOption('old-naledi');await done();
  await select('facilities');await expect(page.locator('#param-radiusKm')).toHaveValue('1');
  await page.locator('#example-select').selectOption('heat');await done();await expect(page.locator('#threshold')).toHaveValue('7');
  await page.locator('#example-select').selectOption('old-naledi');await done();
  await page.locator('#reset-button').click();await run();
  await page.locator('[data-view="rules"]').click();await expect(page.locator('#n3-preview')).toContainText('fw:evidenceLevel');
  const downloadPromise=page.waitForEvent('download');await page.locator('#download-evidence').click();const download=await downloadPromise;
  const receipt=JSON.parse(await readFile(await download.path(),'utf8'));
  assert.equal(receipt.outputs.length,4);assert.equal(receipt.receipts.length,8);assert.equal(receipt.outputs[0].dataset,'gaborone-7f183843');
  assert.equal(receipt.outputs[0].provenance.files.length,3);assert.ok(receipt.outputs[0].provenance.files.every(f=>/^[a-f0-9]{64}$/.test(f.sha256)));
  assert.equal(receipt.outputs[0].rows.length,21);assert.equal(receipt.workflow.nodes.find(n=>n.type==='facilities').params.radiusKm,6);
  // Exercise actual N3 boundary semantics and unknown access independently of the UI.
  const boundaryResults=await page.evaluate(async()=>{
    const {accessN3}=await import('./build/old-naledi.js');
    const rows=[null,0,5,15,30,30.000001].map((minutes,i)=>({id:'test-'+i,minutes}));
    const worker=new Worker('./build/reasoning-worker.js');
    return await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{worker.terminate();data.error?reject(new Error(data.error)):resolve(data.quads.filter(q=>q.predicate==='urn:fieldwork:zone'||q.predicate==='urn:fieldwork:decision'));};worker.onerror=e=>{worker.terminate();reject(new Error(e.message));};worker.postMessage({id:1,input:accessN3(rows,30).input});});
  });
  const value=(i,p)=>boundaryResults.find(q=>q.subject===`urn:fieldwork:test-${i}`&&q.predicate==='urn:fieldwork:'+p)?.object.replace('urn:fieldwork:','');
  assert.deepEqual([0,1,2,3,4,5].map(i=>value(i,'zone')),['Unknown','Within5','Within5','Within15','Within30','Over30']);
  assert.deepEqual([0,1,2,3,4,5].map(i=>value(i,'decision')),['Unknown','NoFlag','NoFlag','NoFlag','NoFlag','Review']);
  await expect(page.locator('#offline-status')).toContainText('Available offline');await context.setOffline(true);await page.reload();await done();
  await expect(page.getByRole('tab')).toHaveCount(4);await expect(page.locator('#result-metrics .review b')).toHaveText('21');
  await context.setOffline(false);await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/old-naledi-desktop.png',fullPage:true});
  await page.getByRole('tab',{name:'Access zones'}).click();await page.screenshot({path:'test-results/old-naledi-chart.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.getByRole('tab',{name:'Facility evidence'}).click();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile horizontal overflow');
  await page.screenshot({path:'test-results/old-naledi-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: Old Naledi real EYE inference, evidence filters, unknown handling, boundary rules, four output widgets, receipts, saved examples, offline reload, mobile layout.');
});
