import {validateRasterProvenance,rasterProvenanceN3,WORLDPOP_BOTSWANA} from '../build/raster-provenance.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Parser} from 'n3';
import {writeArrayBuffer} from 'geotiff';
import {inspectRaster,encodeRaster,readRasterWindow,rasterWindow,clipRaster} from '../build/raster.js';
import {rasterReceipt} from '../build/raster-workflow.js';
import {contentHash} from '../build/project-files.js';
import {createEncryptedPackage,readEncryptedPackage} from '../build/encrypted-package.js';
import {oldNalediWorkflow} from '../build/old-naledi.js';
import {validateWorkflow} from '../build/core.js';
// GeoTIFF.js BlobSource uses the browser FileReader API; emulate only that API in Node.
globalThis.FileReader=class {readAsArrayBuffer(blob){blob.arrayBuffer().then(result=>{this.result=result;this.onload({target:this});},error=>{this.error=error;this.onerror(error);});}};
const metadata={width:4,height:4,bands:1,bounds:[25,-25,26,-24],origin:[25,-24],resolution:[0.25,-0.25],crs:'EPSG:4326',rasterType:'PixelIsArea',noData:'NaN',bits:64,sampleFormat:3,compression:1,blockWidth:4,blockHeight:4,bytesPerPixel:8,geoKeys:{},gdal:null,band:null,description:''};
const boundary={type:'Polygon',coordinates:[[[25,-24],[26,-24],[25,-25],[25,-24]]]};
test('clip parameters survive portable projects and evidence distinguishes cutline from study area',async()=>{
 const {grid,bytes}=await fixture(),w=oldNalediWorkflow(),cutline={geometry:boundary,selectionMode:'polygon'};
 w.nodes.push({id:'raster',type:'raster_input',x:0,y:0,params:{label:'Raster',asset:grid.asset}},{id:'clip',type:'clip_raster',x:0,y:0,params:{label:'Clip',method:'all-touched',marginPixels:0,cutline}});
 const zip=await createEncryptedPackage(w,new Map([[grid.asset.sha256,bytes]]),'independent cutline passphrase'),restored=await readEncryptedPackage(zip,'independent cutline passphrase',validateWorkflow);
 assert.deepEqual(restored.workflow.nodes.find(n=>n.id==='clip').params.cutline,cutline);assert.equal(restored.workflow.manifest.inventory.nodes.find(n=>n.id==='clip').geometry,true);
 assert.deepEqual(restored.workflow.nodes.find(n=>n.id==='clip').params,w.nodes.at(-1).params);for(const marginPixels of [-1,1.1]){const invalid=structuredClone(w);invalid.nodes.at(-1).params.marginPixels=marginPixels;assert.throws(()=>validateWorkflow(invalid),/margin/);}
 const area={boundary:{type:'Polygon',coordinates:[[[25,-24],[26,-24],[26,-25],[25,-25],[25,-24]]]},areaId:'urn:area',geometryId:'urn:area-geometry'},receipt=rasterReceipt(w.nodes.at(-1),clipRaster(grid,boundary),area,'independent','raster');
 const quads=new Parser().parse(receipt.facts),cutlineQuad=quads.find(q=>q.predicate.value==='urn:fieldwork:clipGeometry');assert.ok(cutlineQuad);
 const wkt=subject=>quads.find(q=>q.subject.value===subject&&q.predicate.value==='http://www.opengis.net/ont/geosparql#asWKT').object.value;
 assert.notEqual(wkt(cutlineQuad.object.value),wkt('urn:area-geometry'));const bad=structuredClone(w);bad.nodes.at(-1).params.cutline.geometry={type:'Point',coordinates:[25,-24]};assert.throws(()=>validateWorkflow(bad),/polygon/i);
});
async function fixture(){const values=[0,1.25,2,3,4,null,6,7,8,9,10,11,12,13,14,15],bytes=encodeRaster({metadata,values}),actual=await inspectRaster(new Blob([bytes])),asset={sha256:await contentHash(bytes),bytes:bytes.length,filename:'window.tif',mediaType:'image/tiff',metadata:actual,source:{filename:'original.tif',bytes:bytes.length,lastModified:0,metadata:actual},window:[0,0,4,4]};return {grid:{metadata:actual,values,asset},bytes};}
test('GeoTIFF round trip preserves zero, floating values, NoData and native georeferencing',async()=>{const {grid,bytes}=await fixture(),r=await readRasterWindow(new Blob([bytes]),grid.metadata,[0,0,4,4]);assert.deepEqual(r.values,grid.values);assert.deepEqual(r.metadata.bounds,metadata.bounds);assert.equal(r.metadata.crs,'EPSG:4326');});
test('all-touched retains partial edge cells and tiny islands without inventing missing data',async()=>{
 const {grid}=await fixture(),diagonal={type:'Polygon',coordinates:[[[25,-24],[25.8,-24],[25,-24.8],[25,-24]]]};
 const center=clipRaster(grid,diagonal),touched=clipRaster(grid,diagonal,{method:'all-touched'});
 assert.equal(center.mask.inside,6);assert.equal(touched.mask.inside,10);assert.equal(center.values[3],null);assert.equal(touched.values[3],3);assert.equal(touched.values[5],null);assert.equal(touched.values[0],0);
 const island={type:'Polygon',coordinates:[[[25.05,-24.05],[25.075,-24.05],[25.05,-24.075],[25.05,-24.05]]]};assert.equal(clipRaster(grid,island).mask.inside,0);assert.equal(clipRaster(grid,island,{method:'all-touched'}).values[0],0);
 const decoded=await inspectRaster(new Blob([encodeRaster(touched)])),restored=await readRasterWindow(new Blob([encodeRaster(touched)]),decoded,[0,0,4,4]);assert.deepEqual(restored.values,touched.values);assert.match(decoded.description,/all-touched/);
});
test('pixel margin uses source data, honors holes and budgets, and requires real source coverage',async()=>{
 const {grid}=await fixture(),inner={type:'Polygon',coordinates:[[[25.275,-24.275],[25.675,-24.275],[25.275,-24.675],[25.275,-24.275]]]};
 const noMargin=clipRaster(grid,inner,{method:'all-touched'}),margin=clipRaster(grid,inner,{method:'all-touched',marginPixels:.25});assert.ok(margin.mask.inside>noMargin.mask.inside);assert.equal(margin.values[0],0);
 for(const r of [noMargin,margin,clipRaster(grid,inner,{method:'all-touched',marginPixels:1})]){const x=Math.round((r.metadata.origin[0]-grid.metadata.origin[0])/.25),y=Math.round((r.metadata.origin[1]-grid.metadata.origin[1])/-.25);for(let i=0;i<r.values.length;i++)if(r.values[i]!==null)assert.equal(r.values[i],grid.values[(Math.floor(i/r.metadata.width)+y)*4+i%r.metadata.width+x]);}
 const outer=[[25.01,-24.01],[25.99,-24.01],[25.99,-24.99],[25.01,-24.99],[25.01,-24.01]],hole=[[25.2,-24.2],[25.55,-24.2],[25.55,-24.55],[25.2,-24.55],[25.2,-24.2]],filled={...grid,values:Array.from({length:16},(_,i)=>i)};
 const h=clipRaster(filled,{type:'Polygon',coordinates:[outer,hole]},{method:'all-touched'});assert.equal(h.values[5],null);assert.equal(h.values[9],9);assert.deepEqual(clipRaster(filled,{type:'MultiPolygon',coordinates:[[outer,hole]]},{method:'all-touched'}).values,h.values);
 assert.throws(()=>clipRaster(grid,boundary,{method:'all-touched',marginPixels:1}),/coverage/);for(const marginPixels of [-1,1.1,NaN,Infinity])assert.throws(()=>clipRaster(grid,inner,{marginPixels}),/margin/);
});
test('polygon clipping preserves source and masks cell centers including holes and multipart areas',async()=>{const {grid}=await fixture(),before=structuredClone(grid),clipped=clipRaster(grid,boundary);assert.equal(clipped.values[0],0);assert.equal(clipped.values[1],1.25);assert.equal(clipped.values[5],null);assert.equal(clipped.values[15],null);assert.deepEqual(grid,before);assert.equal(clipped.mask.inside,10);assert.equal(clipped.mask.valid,9);const outer=[[25,-24],[26,-24],[26,-25],[25,-25],[25,-24]],hole=[[25.05,-24.05],[25.2,-24.05],[25.2,-24.2],[25.05,-24.2],[25.05,-24.05]],holes=clipRaster(grid,{type:'Polygon',coordinates:[outer,hole]});assert.equal(holes.values[0],null);const multi=clipRaster(grid,{type:'MultiPolygon',coordinates:[[outer,hole]]});assert.deepEqual(multi.values,holes.values);const out=await readRasterWindow(new Blob([encodeRaster(clipped)]),clipped.metadata,[0,0,4,4]);assert.deepEqual(out.values,clipped.values);});
test('window bounds, decoding budgets and smaller native-grid crops are enforced',async()=>{const {grid}=await fixture();assert.throws(()=>rasterWindow(metadata,{type:'Polygon',coordinates:[[[24,-24],[26,-24],[26,-25],[24,-24]]]}),/coverage/);assert.throws(()=>rasterWindow({...metadata,blockWidth:10000,blockHeight:10000},boundary),/64 MB/);const small=clipRaster(grid,{type:'Polygon',coordinates:[[[25.25,-24.25],[25.5,-24.25],[25.5,-24.5],[25.25,-24.5],[25.25,-24.25]]]});assert.deepEqual(small.metadata.origin,[25.25,-24.25]);assert.equal(small.values.length,1);assert.equal(small.values[0],null);});
test('raster assets are complete, digest-checked portable encrypted project contents',async()=>{const {grid,bytes}=await fixture(),w=oldNalediWorkflow();w.nodes.push({id:'raster',type:'raster_input',x:0,y:0,params:{label:'Raster',asset:grid.asset}});const files=new Map([[grid.asset.sha256,bytes]]),password='raster test passphrase',zip=await createEncryptedPackage(w,files,password),result=await readEncryptedPackage(zip,password,validateWorkflow);assert.deepEqual(result.files,files);assert.equal(result.workflow.manifest.inventory.assets[0].mediaType,'image/tiff');await assert.rejects(()=>createEncryptedPackage(w,new Map(),password));const bad=new Uint8Array(bytes);bad[100]^=1;await assert.rejects(()=>createEncryptedPackage(w,new Map([[grid.asset.sha256,bad]]),password),/checksum/);const receipt=rasterReceipt({id:'clip',type:'clip_raster',params:{label:'Clip',method:'cell-center'}},clipRaster(grid,boundary),{boundary,areaId:'urn:area',geometryId:'urn:geometry'},'trial','raster');assert.ok(new Parser().parse(receipt.facts).length>10);assert.match(receipt.facts,/RasterClipping/);});

test('unsupported CRS and pixel interpretation are rejected before acquisition',async()=>{for(const keys of [{GeographicTypeGeoKey:4269,GTRasterTypeGeoKey:1},{GeographicTypeGeoKey:4326,GTRasterTypeGeoKey:2}]){const bytes=writeArrayBuffer(new Float64Array([0]),{width:1,height:1,BitsPerSample:[64],SampleFormat:[3],ModelPixelScale:[1,1,0],ModelTiepoint:[0,0,0,25,-24,0],GTModelTypeGeoKey:2,...keys});await assert.rejects(()=>inspectRaster(new Blob([bytes])),/EPSG:4326|PixelIsArea/);}});

test('source provenance uses safe bounded metadata, standard RDF and preserves existing assets',async()=>{validateRasterProvenance(undefined);validateRasterProvenance(WORLDPOP_BOTSWANA);assert.throws(()=>validateRasterProvenance({sourceURL:'javascript:alert(1)'}),/HTTP/);assert.throws(()=>validateRasterProvenance({citation:'x'.repeat(4001)}),/length/);assert.throws(()=>validateRasterProvenance({unexpected:'x'}));const facts='@prefix dct:<http://purl.org/dc/terms/>. @prefix dcat:<http://www.w3.org/ns/dcat#>. @prefix fw:<urn:fieldwork:>. '+rasterProvenanceN3('<urn:source>',{...WORLDPOP_BOTSWANA,title:'Title "quoted"\nline'});assert.ok(new Parser().parse(facts).some(q=>q.predicate.value.endsWith('bibliographicCitation')));const {grid,bytes}=await fixture();grid.asset.provenance=WORLDPOP_BOTSWANA;const w=oldNalediWorkflow();w.nodes.push({id:'r',type:'raster_input',x:0,y:0,params:{label:'Source',asset:grid.asset}});const zip=await createEncryptedPackage(w,new Map([[grid.asset.sha256,bytes]]),'provenance test passphrase');const restored=await readEncryptedPackage(zip,'provenance test passphrase',validateWorkflow);assert.deepEqual(restored.workflow.nodes.find(n=>n.id==='r').params.asset.provenance,WORLDPOP_BOTSWANA);});

test('long Unicode citation in exported TIFF preserves header, source distinction and pixels',async()=>{const {grid}=await fixture();grid.asset.provenance={citation:'\u00e9\u4eba'.repeat(1500),sourceURL:'https://example.org/source'};const encoded=encodeRaster(grid),m=await inspectRaster(new Blob([encoded])),description=JSON.parse(m.description.replace(/\x00+$/,''));assert.equal(description.source.citation,grid.asset.provenance.citation);assert.equal(description.embeddedBy,'Fieldwork');assert.match(description.sourceMetadataOrigin,/separate from original/);assert.deepEqual(description.originalRasterMetadata,grid.asset.source.metadata);const decoded=await readRasterWindow(new Blob([encoded]),m,[0,0,4,4]);assert.deepEqual(decoded.values,grid.values);});
