import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {fromFile,fromArrayBuffer} from 'geotiff';
import {encodeRaster} from '../build/raster.js';
import {oldNalediWorkflow} from '../build/old-naledi.js';
const real=process.env.FIELDWORK_WORLDPOP_FILE;
async function exercise(page,file){
 const w=oldNalediWorkflow();w.name='Old Naledi raster clipping';w.nodes=w.nodes.filter(n=>n.type==='area');w.edges=[];delete w.outputId;
 await page.goto('/?example=blank');await page.locator('#workflow-file').setInputFiles({name:'raster-workflow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
 await page.locator('[data-add="raster_input"]').click();await page.locator('#prepare-raster').click();await page.locator('#raster-file').setInputFiles(file);await expect(page.locator('#raster-save')).toBeEnabled();if(typeof file==='string'){await page.locator('#raster-worldpop').click();await expect(page.locator('#raster-source-identifier')).toHaveValue('10.5258/SOTON/WP00839');}else{await page.locator('#raster-source-sourceURL').fill('https://example.org/raster');await page.locator('#raster-source-citation').fill('Synthetic raster citation');await page.locator('#raster-source-units').fill('test units');}await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('fieldwork-workflow-v1'))),source=saved.nodes.find(n=>n.type==='raster_input');assert.equal(saved.manifest.inventory.assets.length,1);await page.locator('#prepare-raster').click();await expect(page.locator('#raster-source-citation')).toHaveValue(source.params.asset.provenance.citation);await page.locator('#raster-source-notes').fill('Reviewed source attribution; clipping is a derived product.');await page.screenshot({path:'test-results/raster-source-metadata-editor.png'});await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 await page.locator('[data-add="clip_raster"]').click();await page.locator('#raster-raster').selectOption(source.id);await page.locator('#add-raster-map').click();await expect(page.locator('#output-input-mode')).toHaveValue('raster');
 await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map image')).toHaveCount(1);await expect(page.locator('#result-metrics')).toContainText('Cell-center polygon mask');
 const download=page.waitForEvent('download');await page.locator('#raster-download').click();const derivative=await readFile(await (await download).path());assert.ok(derivative.length>100);const tiff=await fromArrayBuffer(derivative.buffer.slice(derivative.byteOffset,derivative.byteOffset+derivative.byteLength)),image=await tiff.getImage(),description=JSON.parse(String(await image.getFileDirectory().loadValue('ImageDescription')).replace(/\x00+$/,''));assert.equal(description.source.citation,source.params.asset.provenance.citation);assert.equal(description.source.notes,'Reviewed source attribution; clipping is a derived product.');assert.equal(description.retainedInputSHA256,source.params.asset.sha256);await tiff.close();
 await page.locator('[data-view="rules"]').click();const evidence=page.waitForEvent('download');await page.locator('#download-evidence').click();const receipt=JSON.parse(await readFile(await (await evidence).path(),'utf8'));assert.match(receipt.receipts.find(r=>r.nodeId.startsWith('clip_raster')).facts,/RasterClipping/);assert.match(receipt.receipts.find(r=>r.nodeId.startsWith('clip_raster')).facts,/dct:bibliographicCitation/);assert.equal(receipt.outputs.find(o=>o.raster).raster.asset.provenance.citation,source.params.asset.provenance.citation);
 const grid=receipt.outputs.find(o=>o.raster).raster;assert.ok(grid.mask.outside>0);assert.ok(grid.mask.valid>0);assert.equal(grid.values.filter(v=>v!==null).length,grid.mask.valid);
 await page.locator('[data-view="workflow"]').click();await page.screenshot({path:'test-results/'+(real?'worldpop':'synthetic')+'-raster.png'});
 return {source,grid,receipt};
}
test('raster input, explicit clip, map, portable assets and offline rerun',async({page,browser})=>{
 const metadata={width:60,height:60,origin:[25.88,-24.67],resolution:[0.001,-0.001]},values=Array.from({length:3600},(_,i)=>i%23===0?null:i/10),buffer=Buffer.from(encodeRaster({metadata,values}));
 await exercise(page,{name:'synthetic.tif',mimeType:'image/tiff',buffer});
 await expect(page.locator('#offline-status')).toContainText('Available offline');await page.context().setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});
 await page.locator('#encrypted-export').click();await expect(page.locator('#package-dialog')).toContainText('1 raster windows');await page.locator('#package-password').fill('raster package passphrase');await page.locator('#package-confirm').fill('raster package passphrase');const exported=page.waitForEvent('download');await page.locator('#package-submit').click();const zip=await readFile(await (await exported).path());
 const context=await browser.newContext(),fresh=await context.newPage();try{await fresh.goto('http://127.0.0.1:4174/?example=blank');await expect(fresh.locator('#offline-status')).toContainText('Available offline');await context.setOffline(true);await fresh.locator('#workflow-file').setInputFiles({name:'raster.zip',mimeType:'application/zip',buffer:zip});await fresh.locator('#package-password').fill('raster package passphrase');await fresh.locator('#package-submit').click();await expect(fresh.locator('#package-dialog')).toHaveCount(0);await fresh.locator('#run-button').click();await expect(fresh.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(fresh.locator('#map image')).toHaveCount(1);const restored=await fresh.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));assert.equal(restored.nodes.find(n=>n.type==='raster_input').params.asset.provenance.citation,'Synthetic raster citation');assert.equal(restored.nodes.find(n=>n.type==='raster_input').params.asset.provenance.notes,'Reviewed source attribution; clipping is a derived product.');}finally{await context.close();}
});
test('local WorldPop file clips to Old Naledi without retaining the national raster',async({page})=>{test.skip(!real,'Set FIELDWORK_WORLDPOP_FILE for the private local-file exercise.');const {source,grid}=await exercise(page,real);assert.equal(source.params.asset.source.metadata.width,11248);assert.ok(source.params.asset.bytes<100000);const tiff=await fromFile(real);try{const image=await tiff.getImage(),values=await image.readRasters({window:source.params.asset.window,samples:[0],interleave:true});for(let i=0;i<grid.values.length;i++)if(grid.values[i]!==null)assert.equal(grid.values[i],values[i]);}finally{await tiff.close();}await writeFile('test-results/worldpop-raster-validation.json',JSON.stringify({source:source.params.asset,mask:grid.mask,range:[Math.min(...grid.values.filter(v=>v!==null)),Math.max(...grid.values.filter(v=>v!==null))]},null,2));});

 test('default Map accepts clipped raster by visible drag connector and Undo restores prior inputs',async({page})=>{
 const w=oldNalediWorkflow();w.nodes=w.nodes.filter(n=>n.type==='area');w.nodes[0].x=0;w.nodes[0].y=0;w.nodes.push({id:'clip',type:'clip_raster',x:300,y:0,params:{label:'Clipped raster',method:'cell-center'}},{id:'map',type:'map_output',x:650,y:0,params:{label:'Map'}});w.edges=[{id:'existing',from:'area',to:'map',port:'area'}];delete w.outputId;
 await page.goto('/?example=blank');await page.locator('#workflow-file').setInputFiles({name:'map-connector.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
 await page.locator('.react-flow__node[data-id="map"]').click();await expect(page.locator('#map-raster')).toBeVisible();await expect(page.locator('#output-input-mode')).toHaveValue('spatial');
 const source=page.locator('.react-flow__node[data-id="clip"] [data-handleid="out"]'),target=page.locator('.react-flow__node[data-id="map"] [data-handleid="raster"]');await expect(target).toHaveAttribute('aria-label','Map: Or: Raster input');await page.locator('#fit-button').click();await page.waitForTimeout(300);
 const a=await source.boundingBox(),b=await target.boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:20});await page.mouse.up();
 await expect(page.locator('#output-input-mode')).toHaveValue('raster');await expect(page.locator('#map-raster')).toHaveValue('clip');const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));assert.deepEqual((await saved()).edges.map(e=>[e.from,e.to,e.port]),[['clip','map','raster']]);
 await page.locator('#undo-button').click();await expect(page.locator('#output-input-mode')).toHaveValue('spatial');await expect(page.locator('#map-area')).toHaveValue('area');assert.deepEqual((await saved()).edges,w.edges);
 await page.locator('#map-raster').selectOption('clip');await expect(page.locator('#output-input-mode')).toHaveValue('raster');await page.reload();await page.locator('.react-flow__node[data-id="map"]').click();await expect(page.locator('#map-raster')).toHaveValue('clip');
 });

