import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {fromFile,fromArrayBuffer} from 'geotiff';
import {encodeRaster} from '../build/raster.js';
import {oldNalediWorkflow} from '../build/old-naledi.js';
const real=process.env.FIELDWORK_WORLDPOP_FILE;
test('all-touched margin is adjustable, saved on Clip raster and masked at display edges',async({page})=>{
 await page.goto('/?example=raster');
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));
 const metadata={width:60,height:60,origin:[25.88,-24.67],resolution:[.001,-.001]},values=Array.from({length:3600},(_,i)=>i%23===0?null:i/10);
 await page.locator('#prepare-raster').click();await page.locator('#raster-padding').selectOption('1');await page.locator('#raster-file').setInputFiles({name:'padded.tif',mimeType:'image/tiff',buffer:Buffer.from(encodeRaster({metadata,values}))});await expect(page.locator('#raster-save')).toBeEnabled();await page.locator('#raster-save').click();
 await page.locator('[data-raster-step="raster-clip"]').click();await expect(page.locator('#clip-method')).toHaveValue('all-touched');const area=(await saved()).nodes.find(n=>n.type==='area');
 await page.locator('#preview-raster-clip').click();await page.locator('#clip-preview-margin').fill('1.1');await expect(page.locator('#area-apply')).toBeDisabled();await expect(page.locator('#area-feedback')).toHaveAttribute('role','alert');await page.locator('#clip-preview-margin').fill('0.5');await expect(page.locator('#area-apply')).toBeEnabled();await page.locator('#area-cancel').click();assert.equal((await saved()).nodes.find(n=>n.type==='clip_raster').params.marginPixels,0);
 await page.locator('#preview-raster-clip').click();await page.locator('#clip-preview-margin').fill('0.5');const predicted=await page.locator('#raster-preview-status').textContent();await page.locator('#area-apply').click();await expect(page.locator('#area-dialog')).not.toBeVisible();assert.deepEqual((await saved()).nodes.find(n=>n.type==='area'),area);
 await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#result-metrics')).toContainText('All-touched polygon mask');await expect(page.locator('#map image')).toHaveAttribute('mask','url(#raster-visible-footprint)');await expect(page.locator('#map mask path')).toHaveAttribute('stroke-width','1');
 await page.locator('[data-view="rules"]').click();const evidence=page.waitForEvent('download');await page.locator('#download-evidence').click();const receipt=JSON.parse(await readFile(await (await evidence).path(),'utf8')),grid=receipt.outputs.find(o=>o.raster).raster;assert.equal(grid.mask.method,'all-touched');assert.equal(grid.mask.marginPixels,.5);assert.ok(predicted.includes(`${grid.mask.valid} with data`));assert.match(receipt.receipts.find(r=>r.nodeId==='raster-clip').facts,/fw:rasterMarginPixels 0\.5/);
 // Rasterize the actual SVG mask: inside remains opaque and distant outside is transparent.
 const sample=await page.locator('#map').evaluate(async svg=>{
  const clone=svg.cloneNode(true);clone.querySelectorAll('text').forEach(el=>el.remove());clone.querySelectorAll(':scope > path').forEach(el=>el.remove());clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','850');clone.setAttribute('height','295');
  const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=850;c.height=295;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const a=[...ctx.getImageData(0,0,850,295).data].filter((_,i)=>i%4===3);return {empty:a[0],opaque:a.filter(v=>v===255).length,clear:a.filter(v=>v===0).length};}finally{URL.revokeObjectURL(url);}
 });assert.equal(sample.empty,0);assert.ok(sample.opaque>1000);assert.ok(sample.clear>1000);
 await page.locator('[data-view="workflow"]').click();await page.screenshot({path:'test-results/raster-all-touched-margin.png'});await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});assert.equal((await saved()).nodes.find(n=>n.type==='clip_raster').params.marginPixels,.5);
});
test('raster worked workspace starts connected, preserves other workspaces and runs after local preparation',async({page})=>{
 await page.goto('/?example=blank');await page.locator('[data-add="area"]').click();await page.locator('#study-area-label').fill('Keep my separate study');await page.locator('#study-area-label-form button').click();
 await page.locator('#example-select').selectOption('raster');await expect(page.locator('#prepare-raster')).toBeVisible();await expect(page.locator('.react-flow__node')).toHaveCount(4);await expect(page.locator('#project-title')).toHaveText('Old Naledi · raster clipping');
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));const initial=await saved();assert.equal(initial.exampleId,'raster');assert.equal(initial.edges.length,4);assert.equal(initial.nodes.find(n=>n.type==='raster_input').params.asset,undefined);assert.ok(initial.nodes.find(n=>n.type==='clip_raster').params.cutline);
 await expect(page.locator('#offline-status')).toContainText('Available offline');await page.reload();await expect(page.locator('#prepare-raster')).toBeVisible();await expect(page.locator('#example-select')).toHaveValue('raster');
 const metadata={width:60,height:60,origin:[25.88,-24.67],resolution:[.001,-.001]},values=Array.from({length:3600},(_,i)=>i%23===0?null:i/10);
 await page.locator('#prepare-raster').click();await page.locator('#raster-file').setInputFiles(real||{name:'worked-example.tif',mimeType:'image/tiff',buffer:Buffer.from(encodeRaster({metadata,values}))});await expect(page.locator('#raster-save')).toBeEnabled();if(real)await page.locator('#raster-worldpop').click();await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 await page.locator('[data-raster-step="raster-clip"]').click();await expect(page.locator('#raster-raster')).toHaveValue('raster-input');await page.locator('#preview-raster-clip').click();await expect(page.locator('#raster-preview-status')).toContainText('cells selected');await page.locator('#area-apply').click();await expect(page.locator('#area-dialog')).not.toBeVisible();
 await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map image')).toHaveCount(1);const prepared=await saved();
 await page.locator('#example-select').selectOption('blank');await page.locator('.react-flow__node').click();await expect(page.locator('#study-area-label')).toHaveValue('Keep my separate study');
 await page.locator('#example-select').selectOption('raster');await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});assert.deepEqual((await saved()).nodes,prepared.nodes);
 await page.context().setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map image')).toHaveCount(1);await page.screenshot({path:'test-results/raster-worked-workspace.png'});
 await page.locator('[data-raster-step="raster-clip"]').click();await expect(page.locator('[data-clip-parameters]')).toBeVisible();await expect(page.locator('#inspector-content')).toContainText('Clip extent (degrees)');await page.screenshot({path:'test-results/raster-parameters-inspector.png'});
 await page.locator('[data-raster-step="raster-map"]').click();await expect(page.locator('[data-clip-parameters]')).toHaveCount(0);await expect(page.locator('#preview-raster-clip')).toHaveCount(0);await expect(page.locator('#map image')).toHaveCount(1);
});
test('clip preview adjusts boundary parameters before running and preserves drafts, Undo and offline pixels',async({page})=>{
 const w=oldNalediWorkflow();w.nodes=w.nodes.filter(n=>n.type==='area');w.edges=[];delete w.outputId;
 await page.goto('/?example=blank');await page.locator('#workflow-file').setInputFiles({name:'preview.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
 const metadata={width:60,height:60,origin:[25.88,-24.67],resolution:[.001,-.001]},values=Array.from({length:3600},(_,i)=>i%23===0?null:i/10);
 await page.locator('[data-add="raster_input"]').click();await page.locator('#prepare-raster').click();await page.locator('#raster-file').setInputFiles({name:'preview.tif',mimeType:'image/tiff',buffer:Buffer.from(encodeRaster({metadata,values}))});await expect(page.locator('#raster-save')).toBeEnabled();await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1'))),source=(await saved()).nodes.find(n=>n.type==='raster_input');
 await page.locator('[data-add="clip_raster"]').click();await page.locator('#clip-method').selectOption('cell-center');await page.locator('#raster-raster').selectOption(source.id);let baseline=await saved();
 await page.locator('#preview-raster-clip').click();await expect(page.locator('#area-dialog')).toBeVisible();await expect(page.locator('.raster-preview-image')).toBeVisible();await expect(page.locator('#area-online')).not.toBeChecked();await expect(page.locator('#raster-preview-status')).toContainText('centers inside');await expect(page.locator('#area-apply')).toBeEnabled();
 await expect(page.locator('.raster-preview-image')).toHaveJSProperty('complete',true);await page.screenshot({path:'test-results/raster-preview-polygon.png'});
 await page.locator('#raster-preview-opacity').fill('30');await expect(page.locator('.raster-preview-image')).toHaveCSS('opacity','0.3');assert.deepEqual(await saved(),baseline);
 await page.locator('#area-apply').click();await expect(page.locator('#area-dialog')).not.toBeVisible();assert.deepEqual((await saved()).nodes.find(n=>n.type==='area'),baseline.nodes.find(n=>n.type==='area'));assert.ok((await saved()).nodes.find(n=>n.type==='clip_raster').params.cutline);baseline=await saved();await page.locator('#preview-raster-clip').click();await page.locator('#area-apply').click();assert.deepEqual(await saved(),baseline);await page.locator('#preview-raster-clip').click();await expect(page.locator('#area-dialog')).toBeVisible();
 const bounds=source.params.asset.metadata.bounds;
 async function rectangle(b){for(const [i,key] of ['west','south','east','north'].entries())await page.locator('#area-'+key).fill(String(b[i]));await expect(page.locator('#area-apply')).toBeDisabled();await page.locator('#area-use-bounds').click();}
 await rectangle([bounds[0]-.01,bounds[1],bounds[2],bounds[3]]);await expect(page.locator('#area-feedback')).toContainText('Reacquire a larger window');await expect(page.locator('#area-feedback')).toHaveAttribute('role','alert');await expect(page.locator('#area-apply')).toBeDisabled();
 const b=[bounds[0]+.002,bounds[1]+.002,bounds[2]-.002,bounds[3]-.002];await rectangle(b);await expect(page.locator('#area-apply')).toBeEnabled();await page.locator('#area-cancel').click();assert.deepEqual(await saved(),baseline);
 await expect(page.locator('#offline-status')).toContainText('Available offline');await page.context().setOffline(true);
 await page.locator('#preview-raster-clip').click();await expect(page.locator('#area-dialog')).toBeVisible();await rectangle(b);const predicted=(await page.locator('#raster-preview-status').textContent()).match(/Preview: (\d+) × (\d+) cells; (\d+) centers inside, (\d+) with data, (\d+) outside/).slice(1).map(Number);await page.screenshot({path:'test-results/raster-preview-adjust.png'});
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='fieldwork-workflow-v1')throw new DOMException('Test storage quota','QuotaExceededError');return window.originalSetItem.call(this,key,value);};});await page.locator('#area-apply').click();await expect(page.locator('#area-dialog')).toBeVisible();await expect(page.locator('#area-feedback')).toContainText('could not be saved');assert.deepEqual(await saved(),baseline);await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;delete window.originalSetItem;});
 await page.locator('#area-apply').click();await expect(page.locator('#area-dialog')).not.toBeVisible();const edited=await saved();assert.equal(edited.nodes.find(n=>n.type==='clip_raster').params.cutline.selectionMode,'bbox');assert.deepEqual(edited.nodes.find(n=>n.type==='raster_input').params.asset,source.params.asset);assert.deepEqual(edited.nodes.find(n=>n.type==='area').params,baseline.nodes.find(n=>n.type==='area').params);assert.notDeepEqual(edited.nodes.find(n=>n.type==='clip_raster').params.cutline,baseline.nodes.find(n=>n.type==='clip_raster').params.cutline);
 await page.locator('#undo-button').click();assert.deepEqual((await saved()).nodes,baseline.nodes);await page.locator('#redo-button').click();assert.deepEqual((await saved()).nodes,edited.nodes);
 await page.locator('#add-raster-map').click();await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map image')).toHaveCount(1);
 await page.locator('[data-view="rules"]').click();const evidence=page.waitForEvent('download');await page.locator('#download-evidence').click();const receipt=JSON.parse(await readFile(await (await evidence).path(),'utf8')),grid=receipt.outputs.find(o=>o.raster).raster;assert.deepEqual([grid.metadata.width,grid.metadata.height,grid.mask.inside,grid.mask.valid,grid.mask.outside],predicted);assert.deepEqual(grid.boundary,edited.nodes.find(n=>n.type==='clip_raster').params.cutline.geometry);
 await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});assert.deepEqual((await saved()).nodes.find(n=>n.type==='clip_raster').params.cutline,edited.nodes.find(n=>n.type==='clip_raster').params.cutline);
 await page.locator('#fit-button').click();await page.locator('.react-flow__node[data-id^="clip_raster-"]').click();await expect(page.locator('[data-clip-parameters]')).toBeVisible();await page.locator('#reset-clip-boundary').click();assert.equal((await saved()).nodes.find(n=>n.type==='clip_raster').params.cutline,undefined);await page.locator('#undo-button').click();assert.deepEqual((await saved()).nodes.find(n=>n.type==='clip_raster').params.cutline,edited.nodes.find(n=>n.type==='clip_raster').params.cutline);assert.deepEqual((await saved()).nodes.find(n=>n.type==='area'),baseline.nodes.find(n=>n.type==='area'));
});
async function exercise(page,file){
 const w=oldNalediWorkflow();w.name='Old Naledi raster clipping';w.nodes=w.nodes.filter(n=>n.type==='area');w.edges=[];delete w.outputId;
 await page.goto('/?example=blank');await page.locator('#workflow-file').setInputFiles({name:'raster-workflow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
 await page.locator('[data-add="raster_input"]').click();await page.locator('#prepare-raster').click();await page.locator('#raster-file').setInputFiles(file);await expect(page.locator('#raster-save')).toBeEnabled();if(typeof file==='string'){await page.locator('#raster-worldpop').click();await expect(page.locator('#raster-source-identifier')).toHaveValue('10.5258/SOTON/WP00839');}else{await page.locator('#raster-source-sourceURL').fill('https://example.org/raster');await page.locator('#raster-source-citation').fill('Synthetic raster citation');await page.locator('#raster-source-units').fill('test units');}await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('fieldwork-workflow-v1'))),source=saved.nodes.find(n=>n.type==='raster_input');assert.equal(saved.manifest.inventory.assets.length,1);await page.locator('#prepare-raster').click();await expect(page.locator('#raster-source-citation')).toHaveValue(source.params.asset.provenance.citation);await page.locator('#raster-source-notes').fill('Reviewed source attribution; clipping is a derived product.');await page.screenshot({path:'test-results/raster-source-metadata-editor.png'});await page.locator('#raster-save').click();await expect(page.locator('#raster-dialog')).toHaveCount(0);
 await page.locator('[data-add="clip_raster"]').click();await page.locator('#clip-method').selectOption('cell-center');await page.locator('#raster-raster').selectOption(source.id);await page.locator('#add-raster-map').click();await expect(page.locator('#output-input-mode')).toHaveValue('raster');
 await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(page.locator('#map image')).toHaveCount(1);await expect(page.locator('#result-metrics')).toContainText('Cell-center polygon mask');
 const download=page.waitForEvent('download');await page.locator('#raster-download').click();const derivative=await readFile(await (await download).path());assert.ok(derivative.length>100);const tiff=await fromArrayBuffer(derivative.buffer.slice(derivative.byteOffset,derivative.byteOffset+derivative.byteLength)),image=await tiff.getImage(),description=JSON.parse(String(await image.getFileDirectory().loadValue('ImageDescription')).replace(/\x00+$/,''));assert.equal(description.source.citation,source.params.asset.provenance.citation);assert.equal(description.source.notes,'Reviewed source attribution; clipping is a derived product.');assert.equal(description.retainedInputSHA256,source.params.asset.sha256);await tiff.close();
 await page.locator('[data-view="rules"]').click();const evidence=page.waitForEvent('download');await page.locator('#download-evidence').click();const receipt=JSON.parse(await readFile(await (await evidence).path(),'utf8'));assert.match(receipt.receipts.find(r=>r.nodeId.startsWith('clip_raster')).facts,/RasterClipping/);assert.match(receipt.receipts.find(r=>r.nodeId.startsWith('clip_raster')).facts,/dct:bibliographicCitation/);assert.equal(receipt.outputs.find(o=>o.raster).raster.asset.provenance.citation,source.params.asset.provenance.citation);
 const grid=receipt.outputs.find(o=>o.raster).raster;assert.ok(grid.mask.outside>0);assert.ok(grid.mask.valid>0);assert.equal(grid.values.filter(v=>v!==null).length,grid.mask.valid);
 await expect(page.locator('#map > rect')).toHaveCount(0);await expect(page.locator('#map [data-raster-nodata-background]')).toHaveAttribute('fill-rule','evenodd');
 const alpha=await page.locator('#map image').evaluate(async el=>{const img=new Image();img.src=el.getAttribute('href');await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return [...ctx.getImageData(0,0,c.width,c.height).data].filter((_,i)=>i%4===3);});assert.deepEqual(alpha,grid.values.map(v=>v===null?0:255));
 await page.locator('[data-view="workflow"]').click();await page.screenshot({path:'test-results/'+(real?'worldpop':'synthetic')+'-raster.png'});
 return {source,grid,receipt};
}
test('raster input, explicit clip, map, portable assets and offline rerun',async({page,browser})=>{
 const metadata={width:60,height:60,origin:[25.88,-24.67],resolution:[0.001,-0.001]},values=Array.from({length:3600},(_,i)=>i%23===0?null:i/10),buffer=Buffer.from(encodeRaster({metadata,values}));
 await exercise(page,{name:'synthetic.tif',mimeType:'image/tiff',buffer});
 await expect(page.locator('#offline-status')).toContainText('Available offline');await page.context().setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});
 await page.locator('#encrypted-export').click();await expect(page.locator('#package-dialog')).toContainText('1 raster windows');await page.locator('#package-password').fill('raster package passphrase');await page.locator('#package-confirm').fill('raster package passphrase');const exported=page.waitForEvent('download');await page.locator('#package-submit').click();const zip=await readFile(await (await exported).path());
 const context=await browser.newContext(),fresh=await context.newPage();try{await fresh.goto('http://127.0.0.1:4174/?example=blank');await expect(fresh.locator('#offline-status')).toContainText('Available offline');await context.setOffline(true);await fresh.locator('#workflow-file').setInputFiles({name:'raster.zip',mimeType:'application/zip',buffer:zip});await fresh.locator('#package-password').fill('raster package passphrase');await fresh.locator('#package-submit').click();await expect(fresh.locator('#package-dialog')).toHaveCount(0);await fresh.locator('#run-button').click();await expect(fresh.locator('#workflow-state')).toContainText('Run complete',{timeout:45000});await expect(fresh.locator('#map image')).toHaveCount(1);const restored=await fresh.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));assert.equal(restored.nodes.find(n=>n.type==='raster_input').params.asset.provenance.citation,'Synthetic raster citation');assert.equal(restored.nodes.find(n=>n.type==='raster_input').params.asset.provenance.notes,'Reviewed source attribution; clipping is a derived product.');}finally{await context.close();}
});
test('local WorldPop file clips to Old Naledi without retaining the national raster',async({page})=>{test.skip(!real,'Set FIELDWORK_WORLDPOP_FILE for the private local-file exercise.');const {source,grid}=await exercise(page,real);await page.locator('#fit-button').click();await page.locator('.react-flow__node[data-id^="clip_raster-"]').click();await page.locator('#preview-raster-clip').click();await expect(page.locator('#area-dialog')).toBeVisible();await expect(page.locator('#raster-preview-status')).toContainText(`${grid.mask.valid} with data`);await expect(page.locator('#area-apply')).toBeEnabled();await page.screenshot({path:'test-results/worldpop-preview-polygon.png'});await page.locator('#area-cancel').click();assert.equal(source.params.asset.source.metadata.width,11248);assert.ok(source.params.asset.bytes<100000);const tiff=await fromFile(real);try{const image=await tiff.getImage(),values=await image.readRasters({window:source.params.asset.window,samples:[0],interleave:true});for(let i=0;i<grid.values.length;i++)if(grid.values[i]!==null)assert.equal(grid.values[i],values[i]);}finally{await tiff.close();}await writeFile('test-results/worldpop-raster-validation.json',JSON.stringify({source:source.params.asset,mask:grid.mask,range:[Math.min(...grid.values.filter(v=>v!==null)),Math.max(...grid.values.filter(v=>v!==null))]},null,2));});

 test('default Map accepts clipped raster by visible drag connector and Undo restores prior inputs',async({page})=>{
 const w=oldNalediWorkflow();w.nodes=w.nodes.filter(n=>n.type==='area');w.nodes[0].x=0;w.nodes[0].y=0;w.nodes.push({id:'clip',type:'clip_raster',x:300,y:0,params:{label:'Clipped raster',method:'cell-center'}},{id:'map',type:'map_output',x:650,y:0,params:{label:'Map'}});w.edges=[{id:'existing',from:'area',to:'map',port:'area'}];delete w.outputId;
 await page.goto('/?example=blank');await page.locator('#workflow-file').setInputFiles({name:'map-connector.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
 await page.locator('.react-flow__node[data-id="map"]').click();await expect(page.locator('#map-raster')).toBeVisible();await expect(page.locator('#output-input-mode')).toHaveValue('spatial');
 const source=page.locator('.react-flow__node[data-id="clip"] [data-handleid="out"]'),target=page.locator('.react-flow__node[data-id="map"] [data-handleid="raster"]');await expect(target).toHaveAttribute('aria-label','Map: Or: Raster input');await page.locator('#fit-button').click();await page.waitForTimeout(300);
 const a=await source.boundingBox(),b=await target.boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:20});await page.mouse.up();
 await expect(page.locator('#output-input-mode')).toHaveValue('raster');await expect(page.locator('#map-raster')).toHaveValue('clip');const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));assert.deepEqual((await saved()).edges.map(e=>[e.from,e.to,e.port]),[['clip','map','raster']]);
 await page.locator('#undo-button').click();await expect(page.locator('#output-input-mode')).toHaveValue('spatial');await expect(page.locator('#map-area')).toHaveValue('area');assert.deepEqual((await saved()).edges,w.edges);
 await page.locator('#map-raster').selectOption('clip');await expect(page.locator('#output-input-mode')).toHaveValue('raster');await page.reload();await page.locator('.react-flow__node[data-id="map"]').click();await expect(page.locator('#map-raster')).toHaveValue('clip');
 });

