import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
test("Blank canvas, study-area drawing, labels and recovery",async({page,context})=>{
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const run=async()=>{await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});};
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));
const open=async()=>{await page.locator('[data-view="workflow"]').click();await page.locator('.react-flow__node').click();await page.locator('#edit-study-area').click();await expect(page.locator('#area-dialog')).toBeVisible();};
const points=async(list)=>{const b=await page.locator('#area-map').boundingBox();for(const [x,y] of list)await page.mouse.click(b.x+b.width*x,b.y+b.height*y);};
  await mkdir('test-results',{recursive:true});
  await page.goto('/?example=blank');
  await expect(page.locator('.react-flow__node')).toHaveCount(0);await expect(page.locator('#run-button')).toBeDisabled();
  await page.screenshot({path:'test-results/study-area-empty.png',fullPage:true});
  await page.locator('#blank-add').click();await expect(page.locator('.react-flow__node')).toHaveCount(1);
  assert.equal((await saved()).nodes[0].params.geometry,null);
  await page.locator('#edit-study-area').click();
  // Observe real online tiles; drawing tests below do not depend on network success.
  let onlineTiles=false;
  try{await expect(page.locator('#area-map .leaflet-tile-loaded').first()).toBeVisible({timeout:20000});onlineTiles=true;}catch{}
  console.log('Online OpenStreetMap tiles loaded:',onlineTiles);
  await page.locator('#draw-bbox').click();await points([[.3,.3],[.65,.7]]);
  await expect(page.locator('#area-apply')).toBeEnabled();await expect(page.locator('#area-n3')).toContainText('a geo:Feature');
  await page.locator('#area-name').fill('Old Naledi exploration');
  await expect(page.locator('.area-map-label')).toHaveText('Old Naledi exploration');
  await page.screenshot({path:'test-results/study-area-editor.png',fullPage:true});
  await page.locator('#area-apply').click();
  const box=(await saved()).nodes[0].params.geometry;assert.equal(box.coordinates[0].length,5);
  const areaId=(await saved()).nodes[0].id,label='Old Naledi <pilot> & study';
  await page.locator('#study-area-label').fill(label);await page.locator('#study-area-label-form button').click();
  assert.equal((await saved()).nodes[0].id,areaId);assert.deepEqual((await saved()).nodes[0].params.geometry,box);
  await expect(page.locator('.react-flow__node')).toContainText(label);
  await page.locator('[data-view="rules"]').click();await expect(page.locator('#n3-preview')).toContainText('not executed evidence');
  await run();await expect(page.locator('#area-semantic-graph')).toContainText('Ready for spatial analysis');
  await expect(page.locator('#n3-preview')).toContainText(`rdfs:label "${label}"`);await expect(page.locator('#map')).toContainText(label);
  await expect(page.locator('#n3-preview')).toContainText('"true"^^<http://www.w3.org/2001/XMLSchema#boolean>');
  await expect(page.getByRole('tab')).toHaveCount(1);
  const receiptDownload=page.waitForEvent('download');await page.locator('#download-evidence').click();
  const receipt=JSON.parse(await readFile(await (await receiptDownload).path(),'utf8'));
  assert.equal(receipt.outputs[0].ready,true);assert.equal(receipt.receipts.length,1);
  assert.ok(receipt.receipts[0].input.includes('geo:wktLiteral'));
  await open();await page.locator('#area-clear').click();await expect(page.locator('#area-apply')).toBeDisabled();await page.locator('#area-cancel').click();
  assert.deepEqual((await saved()).nodes[0].params.geometry,box);
  await open();await page.locator('#draw-polygon').click();await points([[.2,.2],[.7,.7],[.2,.7],[.7,.2]]);await page.locator('#area-finish').click();
  await expect(page.locator('#area-apply')).toBeDisabled();await expect(page.locator('#area-feedback')).toContainText('cross');
  await page.locator('#draw-polygon').click();await points([[.25,.25],[.7,.3],[.6,.7],[.3,.65]]);await page.locator('#area-undo-point').click();await points([[.3,.6]]);await page.locator('#area-finish').click();
  await expect(page.locator('#area-apply')).toBeEnabled();
  const handle=await page.locator('.area-vertex').first().boundingBox();await page.mouse.move(handle.x+6,handle.y+6);await page.mouse.down();await page.mouse.move(handle.x+20,handle.y+16,{steps:5});await page.mouse.up();
  await expect(page.locator('#area-apply')).toBeEnabled();await page.locator('#area-apply').click();
  const polygon=(await saved()).nodes[0].params.geometry;assert.notDeepEqual(polygon,box);assert.equal((await saved()).nodes[0].params.selectionMode,'polygon');
  await page.locator('#undo-button').click();assert.deepEqual((await saved()).nodes[0].params.geometry,box);
  await page.locator('#redo-button').click();assert.deepEqual((await saved()).nodes[0].params.geometry,polygon);
  const workflowDownload=page.waitForEvent('download');await page.locator('#export-button').click();const exported=await readFile(await (await workflowDownload).path());
  await page.locator('#new-workflow').click();await expect(page.locator('.react-flow__node')).toHaveCount(0);
  await page.locator('#workflow-file').setInputFiles({name:'study.json',mimeType:'application/json',buffer:exported});await expect(page.locator('.react-flow__node')).toHaveCount(1);assert.deepEqual((await saved()).nodes[0].params.geometry,polygon);
  await run();await expect(page.locator('#offline-status')).toContainText('Available offline');
  await context.setOffline(true);await page.reload();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});
  assert.deepEqual((await saved()).nodes[0].params.geometry,polygon);await open();
  await expect(page.locator('#area-name')).toHaveValue(label);await expect(page.locator('.area-map-label')).toHaveText(label);
  // navigator.onLine is advisory and can remain true after a cached navigation.
  assert.equal(await page.locator('#area-online').isChecked(),await page.evaluate(()=>navigator.onLine));
  await page.locator('#area-online').uncheck();await expect(page.locator('#area-tile-status')).toContainText('Basemap off');await expect(page.locator('#area-apply')).toBeEnabled();
  await page.setViewportSize({width:390,height:844});
  await page.locator('#area-fit').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.equal(await page.locator('#area-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);
  await page.screenshot({path:'test-results/study-area-mobile.png',fullPage:true});
  await page.locator('#area-cancel').click();await page.setViewportSize({width:1600,height:1100});await page.locator('[data-view="rules"]').click();
  await page.screenshot({path:'test-results/study-area-evidence.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: blank canvas, bbox and polygon drawing, invalid shape rejection, vertex correction, draft versus EYE inference, cancellation, undo/redo, export/import, offline geometry and inference, mobile layout.');
});
