import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const fixture=JSON.parse(await readFile(new URL('./fixtures/coverage-workflow-2026-10-05.json',import.meta.url),'utf8'));
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('fieldwork-workflow-v1')));
const upload=(page,w)=>page.locator('#workflow-file').setInputFiles({name:'compatibility.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});
const run=async page=>{await page.locator('#run-button').click();await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});};
const receipt=async page=>{
  await page.locator('[data-view="rules"]').click();
  const download=page.waitForEvent('download');await page.locator('#download-evidence').click();
  return JSON.parse(await readFile(await (await download).path(),'utf8'));
};

test('frozen workflow restores typed data, area enrichment and real EYE decisions offline',async({page,context})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/?example=blank');await upload(page,fixture);await run(page);
  const before=await saved(page),evidence=await receipt(page),map=evidence.outputs.find(o=>o.nodeId==='map');
  assert.deepEqual(map.rows.map(r=>[r.sourceNodeId,r.recordId,r.relation,r.decision]),[
    ['observations','inside','Inside','Accept'],['observations','edge','Boundary','Accept'],
    ['observations','outside','Outside','Excluded'],['observations','missing','MissingLocation','Review'],
    ['second','inside','Inside','Accept'],['second','outside','Outside','Review'],
  ]);
  assert.equal(map.reviewCount,2);assert.equal(map.excludedCount,1);assert.equal(map.canProceed,false);
  assert.deepEqual(map.retainedLayers.map(l=>l.data.features.length),[3,2]);
  assert.deepEqual(map.boundary,fixture.nodes[0].params.geometry);
  assert.equal(map.spatialReference.geometryCRS,'OGC:CRS84');
  // Independent spherical-rectangle reference, not a snapshot generated by the area implementation.
  const rad=Math.PI/180,expected=6371008.8**2*(.02*rad)*Math.abs(Math.sin(-24.68*rad)-Math.sin(-24.7*rad));
  assert.ok(Math.abs(map.measurement.squareMetres-expected)/expected<1e-9);
  const facts=evidence.receipts.find(r=>r.nodeId==='coverage').input;
  for(const token of ['geo:hasMetricArea','geo:sfDisjoint','XMLSchema#date','XMLSchema#integer'])assert.ok(facts.includes(token),token);
  await expect(page.locator('#offline-status')).toContainText('Available offline');
  await context.setOffline(true);await page.reload();
  await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete',{timeout:45000});
  assert.deepEqual(await saved(page),before);
  const restored=(await receipt(page)).outputs.find(o=>o.nodeId==='map');
  assert.deepEqual(restored.rows,map.rows);assert.deepEqual(restored.measurement,map.measurement);
  assert.deepEqual(errors,[]);
});

test('rejected imports leave the current workflow and completed results intact',async({page})=>{
  await page.goto('/?example=blank');await upload(page,fixture);await run(page);
  const before=await saved(page);
  for(const [mutate,message] of [
    [w=>{w.schema='unknown';},'Invalid Fieldwork workflow'],
    [w=>{w.nodes.find(n=>n.id==='observations').params.data.features[0].properties.household_size='five';},'data type integer'],
    [w=>{w.nodes[0].params.spatialReference={datum:'WGS84',geodeticCRS:'EPSG:3857',geometryCRS:'EPSG:3857',axisOrder:'x-y',units:'metre'};},'CRS'],
    [w=>{w.edges.find(e=>e.to==='map').port='points';},'Incompatible node connection'],
  ]){
    const invalid=structuredClone(fixture);mutate(invalid);await upload(page,invalid);
    await expect(page.locator('#toast')).toContainText(message);
    assert.deepEqual(await saved(page),before);
    await expect(page.locator('#workflow-state')).toHaveText('✓ Run complete');
    await expect(page.getByRole('tab',{name:'Regression map'})).toBeVisible();
  }
});

test('all eight point inputs remain connectable and survive removal and Undo',async({page})=>{
  const w=structuredClone(fixture),source=w.nodes.find(n=>n.id==='observations');
  w.nodes=w.nodes.filter(n=>['scope','observations','coverage','map'].includes(n.id));
  w.nodes.find(n=>n.id==='coverage').params={pointInputCount:1,exclusions:[]};
  for(let i=2;i<=8;i++)w.nodes.push({...structuredClone(source),id:`layer${i}`,x:40,y:230,params:{...structuredClone(source.params),label:`Layer ${i}`}});
  w.edges=[{id:'area',from:'scope',to:'coverage',port:'area'},{id:'points',from:'observations',to:'coverage',port:'points'},{id:'map',from:'coverage',to:'map',port:'coverage'}];
  await page.goto('/?example=blank');await upload(page,w);
  await page.locator('.react-flow__node[data-id="coverage"]').click();
  for(let i=2;i<=8;i++){
    await page.locator('#add-point-input').click();await page.locator(`#coverage-points_${i}`).selectOption(`layer${i}`);
    await expect(page.locator(`.react-flow__node[data-id="coverage"] [data-handleid="points_${i}"]`)).toBeVisible();
  }
  await expect(page.locator('#add-point-input')).toBeDisabled();
  const handles=page.locator('.react-flow__node[data-id="coverage"] .react-flow__handle.target');
  await expect(handles).toHaveCount(9);
  const boxes=await handles.evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom};}));
  for(let i=1;i<boxes.length;i++)assert.ok(boxes[i].top>boxes[i-1].bottom,'Expandable input hit areas must not overlap');
  await page.locator('#remove-point-input').click();
  assert.equal((await saved(page)).edges.some(e=>e.port==='points_8'),false);
  await page.locator('#undo-button').click();await expect(page.locator('#coverage-points_8')).toHaveValue('layer8');
  await run(page);const result=(await receipt(page)).outputs.find(o=>o.nodeId==='map');
  assert.equal(result.rows.length,32);assert.equal(result.pointLayers.length,8);
  assert.equal(result.reviewCount,16);assert.equal(result.excludedCount,0);
});
