import {evidenceInspector,openEvidenceEditor} from './evidence-ui.js';
import {workflowDocument,importWorkflowDocument,exportEvidenceFiles} from './evidence-storage.js';
import {MAX_BUNDLE_BYTES} from './evidence.js';
import type {Workflow,WorkflowNode,NodeType,NodeSpec,Boundary,Position,SpatialRelation} from './types.js';
import type {WorkflowRun,Receipt,Output,MapRow,PointRow,CoverageRow,CoverageValue,TableValue} from './results.js';
import type {CanvasAPI,NodeDescription} from './canvas.js';
import type {Connection,Edge} from '@xyflow/react';
import type {ReasonerQuad,ReasoningRequest,ReasoningResponse} from './worker-types.js';
import {element as $,optionalElement,control} from './dom.js';
import {errorMessage,required} from './guards.js';
function getNode<K extends NodeType>(w:Workflow,id:string,type:K):WorkflowNode<K>{const node=required(w.nodes.find(n=>n.id===id));if(node.type!==type)throw new Error('Node type changed while editing');return node as WorkflowNode<K>;}
function updateParam(w:Workflow,id:string,key:string,value:unknown){Object.assign(required(w.nodes.find(n=>n.id===id)).params,{[key]:value});}
function replaceWorkflow(w:Workflow,next:Workflow){for(const key of Object.keys(w))Reflect.deleteProperty(w,key);Object.assign(w,next);}
import {TYPES,exampleWorkflow,validateWorkflow,validateGeoJSON,executionPlan,executeWorkflow,nodeInputs} from './core.js';
import {mountCanvas} from './canvas.js';
import {OLD_TYPES,oldNalediWorkflow,tierLabel} from './old-naledi.js';
import {oldInspector,oldEvidence,resultTable,oldMap} from './old-naledi-ui.js';
import {blankWorkflow,newStudyArea,studyAreaN3,quadToN3,areaSvg} from './study-area.js';
import {openStudyAreaEditor} from './study-area-map.js';
import {newAreaMeasurement,areaUnitOptions,formatArea,AREA_UNITS} from './area-measurement.js';
import {coverageExercise,newObservations,newCoverageCheck,relationLabel} from './spatial-coverage.js';
import {coverageTable,coverageEvidence} from './coverage-ui.js';
import {openInputDataEditor} from './input-data-ui.js';
import {boundary as oldNalediBoundary} from '../examples/old-naledi/data.js';
import {chartMarkup} from './chart-output.js';
import {openRasterEditor,rasterSvg,downloadRaster} from './raster-ui.js';
import {openPackageDialog} from './package-ui.js';
import {syncProjectManifest} from './project-manifest.js';
import {mountPanelLayout} from './panel-layout.js';
import {newMapOutput,mapEvidence} from './map-output.js';
import {newTableOutput,pointTableMarkup,pointTableEvidence} from './table-output.js';
import {pointPort,MAX_POINT_LAYERS} from './point-layers.js';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const KEY='fieldwork-workflow-v1';
// Keep keyboard and scroll-to-element navigation clear of the floating controls.
new ResizeObserver(([entry])=>document.documentElement.style.setProperty('--project-bar-height',`${entry.target.getBoundingClientRect().height+12}px`)).observe($('.project-bar'));
const WORKSPACES='fieldwork-examples-v1';
const exampleKey=(w:Workflow):string=>(w.exampleId==='blank'||w.exampleId==='coverage')?w.exampleId:w.exampleId==='old-naledi'||w.nodes.some(n=>n.type==='area')?'old-naledi':'heat';
const template=(key:string)=>key==='coverage'?coverageExercise():key==='blank'?blankWorkflow():key==='old-naledi'?oldNalediWorkflow():exampleWorkflow();
let workflow=exampleWorkflow(),selected:string|null|undefined='criteria',result:WorkflowRun|null=null,runWorkflow:Workflow|null=null,busy=false,dirty=true,statuses:Record<string,string>={},history:Workflow[]=[],future:Workflow[]=[],flow:CanvasAPI|null=null,worker:Worker|null=null,seq=0,lastNodeCount=0,importNode:string|null=null;
let toastTimer:ReturnType<typeof setTimeout>|undefined,activeOutputId:string|null=null,tablePage=0,tableAttributePage=0;
const activeOutput=()=>result?.outputs.find(o=>o.nodeId===activeOutputId)||result?.outputs[0];
const hiddenMapLayers=new Map<string,Set<string>>();
function toast(message:string){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000);}
try{const saved=localStorage.getItem(KEY);if(saved)workflow=validateWorkflow(JSON.parse(saved));}catch{toast('Saved workflow could not be loaded. The example is ready.');}
if(!workflow.nodes.some(n=>n.id===selected))selected=exampleKey(workflow)==='old-naledi'?'access':workflow.nodes[0]?.id;
function save(){
  syncProjectManifest(workflow);
  const previous=new Map<string,string|null>();
  try{for(const key of [KEY,WORKSPACES])previous.set(key,localStorage.getItem(key));const workspaces=JSON.parse(previous.get(WORKSPACES)||'{}');workspaces[exampleKey(workflow)]=workflow;localStorage.setItem(KEY,JSON.stringify(workflow));localStorage.setItem(WORKSPACES,JSON.stringify(workspaces));$('#save-status').textContent='Saved on this device';return true;}
  catch{for(const [key,value] of previous){try{if(localStorage.getItem(key)!==value){if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value);}}catch{/* Storage may be unavailable even for rollback. Keep the editor draft open. */}}$('#save-status').textContent='Storage unavailable — export to keep';return false;}
}
function loadExample(key:string){if(busy)return;save();try{const saved=JSON.parse(localStorage.getItem(WORKSPACES)||'{}')[key];workflow=saved?validateWorkflow(saved):template(key);}catch{workflow=template(key);}selected=key==='old-naledi'?'access':'criteria';result=null;runWorkflow=null;activeOutputId=null;history=[];future=[];statuses={};dirty=true;save();renderLibrary();renderResults();render();switchView('workflow');setTimeout(()=>flow?.fit(),80);if(workflow.nodes.length&&key!=='blank')run();}
function change(fn:(w:Workflow)=>void,{spatial=true,requirePersistence=false}={}){if(busy)return false;const previous=structuredClone(workflow);try{fn(workflow);syncProjectManifest(workflow,true);workflow=validateWorkflow(workflow);const persisted=save();if(requirePersistence&&!persisted){workflow=previous;render();return false;}history.push(previous);if(history.length>40)history.shift();future=[];if(spatial){dirty=true;statuses={};}render();return persisted;}catch(e){workflow=previous;toast(errorMessage(e));render();return false;}}
function setConnection(w:Workflow,from:string|null,to:string,port:string){
  const target=w.nodes.find(n=>n.id===to),map=['map_output','table_output'].includes(target?.type||'');
  if(from&&target?.type==='map_output'&&port==='raster'){target.params.inputMode='raster';w.edges=w.edges.filter(e=>e.to!==to);}
  w.edges=w.edges.filter(e=>e.to!==to||(e.port!==port&&(!from||!map||(port!=='coverage'&&e.port!=='coverage'))));
  if(from)w.edges.push({id:`e-${Date.now()}`,from,to,port});
}
function describe(n:WorkflowNode,status?:string):NodeDescription{let subtitle=TYPES[n.type].description,detail='Ready';if((n.type==='places'||n.type==='centers')){subtitle=`${n.params.data.features.length} local locations`;detail='GeoJSON · CRS84';}if(n.type==='policy'){subtitle=`Heat alert + distance > ${n.params.thresholdKm} km`;detail='Evidence → decision';}if(n.type==='alert'){subtitle=n.params.active===null?'Alert status unknown':n.params.active?'Heat alert is active':'No active heat alert';detail=n.params.date;}if(n.type==='nearest'){detail='Kilometers · straight-line';}if(n.type==='output'){subtitle={table:'Table with supporting evidence',bars:'Grouped result counts',map:'Map of results and locations'}[n.params.view];detail='Creates a Results tab';}if(n.type==='area'){subtitle='Old Naledi · Gaborone';detail='Source boundary · CRS84';}if(n.type==='samples'){subtitle=`Regular grid · ${n.params.spacingM} m`;detail='Demonstration points';}if(n.type==='facilities'){subtitle=`Search within ${n.params.radiusKm} km`;detail='Historical registry · 214 points';}if(n.type==='xpert'){subtitle='Named evidence → facility type';detail='NB06 hierarchy · N3';}if(n.type==='access'){subtitle=`${n.params.minimumEvidence} evidence · ${n.params.service==='onsite'?'onsite':'incl. referral'}`;detail=`Straight-line proxy · ${n.params.speedMPerMin} m/min`;}if(n.type==='access_policy'){subtitle=`Review proxy time > ${n.params.thresholdMin} min`;detail='N3 · missing stays unknown';}if(n.type==='facility_audit'){subtitle='Service, evidence, and references';detail='All candidate facilities';}return {definition:{...TYPES[n.type],inputs:nodeInputs(n)},type:n.type,label:n.params.label||TYPES[n.type].title,subtitle,detail,status};}
function render(){
  const url=new URL(location.href);url.searchParams.set('example',exampleKey(workflow));window.history.replaceState(null,'',url);
  renderLibrary($('#node-search').value);
  const old=exampleKey(workflow)==='old-naledi';$('#example-select').value=old?'old-naledi':'heat';$('#project-title').textContent=workflow.name||'Untitled workflow';$('#project-description').textContent=old?'Explore diagnostic access, evidence strength, and the assumptions connecting them.':'Connect geography to evidence. Make every decision explainable.';$('#example-note').textContent=old?'Source boundary + historical facilities · generated sample locations · straight-line access proxy':'Synthetic neighborhoods and cooling centers · illustrative screening rule';$('#canvas-example').textContent=old?'OLD NALEDI · WORKED EXAMPLE 02':'HEAT OUTREACH · DEMO 01';$('#footer-context').textContent=old?'Source snapshot 7f183843 · synthetic sample locations':'CRS84 coordinates · geodesic approximation · synthetic data';
  if(exampleKey(workflow)==='blank'){$('#example-select').value='blank';$('#project-description').textContent='Developmental evaluation · define a study area and inspect its semantic representation.';$('#example-note').textContent='Experiment 01 · draw → inspect facts → run the rule';$('#canvas-example').textContent='STUDY AREA · EXPERIMENT 01';$('#footer-context').textContent='User-defined study area · CRS84 · local reasoning';}
  if(exampleKey(workflow)==='coverage'){$('#example-select').value='coverage';$('#project-description').textContent='Developmental evaluation · inspect spatial exceptions, exclude with a reason, or revise the boundary.';$('#example-note').textContent='Synthetic points and illustrative boundary · no patient data';$('#canvas-example').textContent='SPATIAL COVERAGE · EXPERIMENT';$('#footer-context').textContent='Synthetic coverage exercise · CRS84 · boundary included';}
  $('#blank-canvas').hidden=workflow.nodes.length!==0||exampleKey(workflow)!=='blank';
  flow?.update(workflow,selected,statuses);$('#node-count').textContent=String(workflow.nodes.length);$('#undo-button').disabled=!history.length||busy;$('#redo-button').disabled=!future.length||busy;
  $('#workflow-state').textContent=busy?'Running locally…':dirty?(result?'Changed · rerun to update':'Ready to run'):'✓ Run complete';
  $('#run-button').disabled=busy;$('#run-button').innerHTML=busy?'◌ Running…':'<span>▶</span> Run workflow';
  $('#run-summary').textContent=result?(dirty?'Previous run · settings have changed':`${result.outputs.length} outputs · ${Math.round(result.trace.reduce((a,t)=>a+t.milliseconds,0))} ms`):'Run the workflow to see results';
  $('#example-select').disabled=busy;document.body.classList.toggle('busy',busy);flow?.setBusy(busy);renderInspector();
  $('#run-button').disabled=busy||!workflow.nodes.length;$('#new-workflow').disabled=busy;
  if(!workflow.nodes.length)$('#workflow-state').textContent='Add Study area to begin';
  renderN3();
  renderCoverageAlert();
}
function describeNode(n:WorkflowNode,status?:string):NodeDescription{const d=describe(n,status);if(n.type==='map_output'&&n.params.inputMode==='raster'){d.subtitle='Native raster cells and study boundary';d.detail='GeoTIFF download';}if(n.type==='raster_input')d.detail=n.params.asset?`${n.params.asset.metadata.width} x ${n.params.asset.metadata.height} retained cells`:'Prepare GeoTIFF input';if(n.type==='area'&&n.params.source==='drawn'){d.subtitle=n.params.geometry?`${n.params.selectionMode==='bbox'?'Bounding box':'Polygon'} · ${n.params.geometry.coordinates[0].length-1} vertices`:'Choose a boundary on the map';d.detail=n.params.geometry?'GeoJSON → N3 · CRS84':'Not configured';}if(n.type==='measure_area'){d.subtitle='Study area → study area + area';d.detail=`${AREA_UNITS[n.params.unit].symbol} · spherical calculation`;}return d;}
function runEvidenceText(){return result?result.receipts.map(receiptText).join('\n\n')+(result.provenanceN3?'\n\n# REFERENCE PROVENANCE (documentation, not rule premises)\n'+result.provenanceN3:''):'';}
function receiptText(r:Receipt){return r.kind==='presentation'?`# PRESENTATION NODE: ${r.nodeId}\n# SOURCE FACTS AND VIEW PROVENANCE (no new inference)\n${r.input}`:r.kind==='computation'?`# COMPUTATION NODE: ${r.nodeId}\n# COMPUTED FACTS (not inferred)\n${r.input}`:`# RULE NODE: ${r.nodeId}\n${r.input}\n# DERIVED CONCLUSIONS\n${r.conclusions.map(quadToN3).join('\n')}`;}
function renderN3(){
  const drawn=workflow.nodes.filter((n):n is WorkflowNode<'area'> & {params:Extract<import('./types.js').AreaParams,{source:'drawn'}>}=>n.type==='area'&&n.params.source==='drawn');
  const area=drawn.find(n=>n.params.geometry);$('#area-semantic-graph').hidden=!area;
  const evaluated=area&&!dirty&&result?.receipts.some(r=>r.nodeId===area.id&&r.conclusions.some(q=>q.predicate==='urn:fieldwork:readyForSpatialAnalysis'&&q.object==='true'));
  if(area)$('#area-semantic-graph').innerHTML=`<div>${esc(area.params.label)}<small>Study area · ${esc(area.id)}</small></div><span>geo:hasGeometry →</span><div>${area.params.selectionMode==='bbox'?'Bounding box polygon':'Polygon'}<small>geo:asWKT · CRS84</small></div><span>validated geometry → rule</span><div>${evaluated?'Ready for spatial analysis':'Not evaluated'}<small>${evaluated?'EYE conclusion from widget checks':'Draft facts'}</small></div>`;
  if(dirty&&drawn.length){$('#n3-preview').textContent='# CURRENT STUDY-AREA DRAFT — not evaluated\n\n'+drawn.map(n=>{try{return studyAreaN3(n).input;}catch{return `# ${n.id}: select a valid study area before running.`;}}).join('\n\n');}
  else if(result)$('#n3-preview').textContent=runEvidenceText();
  else $('#n3-preview').textContent='Add a Study area and draw a boundary to generate facts, or run a worked example.';
}
function renderLibrary(search=''){
  const allowed=new Set<string>(['blank','coverage'].includes(exampleKey(workflow))?['area','observations','measure_area','coverage_check','map_output']:template(exampleKey(workflow)).nodes.map(n=>n.type));if(exampleKey(workflow)==='old-naledi')for(const type of ['measure_area','observations','coverage_check','map_output'])allowed.add(type);allowed.add('raster_input');allowed.add('clip_raster');allowed.delete('output');allowed.add('chart_output');allowed.add('map_output');allowed.add('table_output');let group='';const entries=Object.entries(TYPES).filter(([k,t])=>allowed.has(k)&&(t.title+' '+t.description).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>['Sources','Spatial operations','Semantic reasoning','Summaries','Outputs'].indexOf(a[1].group)-['Sources','Spatial operations','Semantic reasoning','Summaries','Outputs'].indexOf(b[1].group));$('#library-count').textContent=String(allowed.size);$('#node-library').innerHTML=entries.map(([k,t])=>{const heading=t.group!==group?`<div class="library-group">${t.group}</div>`:'';group=t.group;return `${heading}<button class="palette-node ${t.color}" data-add="${k}"><span class="palette-icon">${t.icon}</span><strong>${t.title}</strong><span>+</span></button>`;}).join('');
  $('#node-library').querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.onclick=()=>{
    const type=b.dataset.add as NodeType,sample=structuredClone(type==='raster_input'?{type:'raster_input' as const,params:{label:'Raster input'}}:type==='clip_raster'?{type:'clip_raster' as const,params:{label:'Clipped raster',method:'cell-center' as const}}:type==='chart_output'?{type:'chart_output' as const,params:{label:'Chart'}}:type==='table_output'?newTableOutput():type==='map_output'?newMapOutput():type==='observations'?newObservations():type==='coverage_check'?newCoverageCheck():type==='measure_area'?newAreaMeasurement():['blank','coverage'].includes(exampleKey(workflow))&&type==='area'?newStudyArea():template(exampleKey(workflow)).nodes.find(n=>n.type===type));const id=`${type}-${Date.now()}`;
    change(w=>{const source=['measure_area','raster_input'].includes(type)?w.nodes.find(n=>n.type==='area'):type==='clip_raster'?w.nodes.find(n=>n.type==='raster_input'):null;const added={...required(sample),id,x:source?source.x+310:180+(w.nodes.length%4)*80,y:source?source.y:90+(w.nodes.length%3)*80};if(added.type==='output')added.params={view:'bars',label:`Bar chart ${w.nodes.filter(n=>n.type==='output').length+1}`};w.nodes.push(added);if(added.type==='raster_input'||added.type==='clip_raster'){const area=w.nodes.find(n=>n.type==='area');if(area)setConnection(w,area.id,id,'area');}selected=id;});flow?.fit();toast(type==='area'?'Study area added. Select its boundary in the Inspector.':`${TYPES[type].title} added. Connect its ports to the workflow.`);
  });
}
function title(n:WorkflowNode){const t=TYPES[n.type];return `<div class="inspector-title ${t.color}"><span class="node-icon">${t.icon}</span><div><h2>${esc(n.params.label||t.title)}</h2><p>${esc(t.group)} / ${esc(n.id)}</p></div></div>`;}
function renderInspector(){
  if(selected?.startsWith('result:')){renderEvidence(selected.slice(7));return;}
  if(exampleKey(workflow)==='blank'&&!workflow.nodes.some(n=>n.id===selected)){$('#inspector-content').innerHTML='<div class="inspector-body"><span class="inspector-section">Developmental evaluation · step 1</span><h2>Define the study area</h2><p class="description">Add Study area, then select the node to draw a bounding box or polygon on an online map.</p><div class="rule-preview">Predict what the selection will produce, inspect the N3 facts, then run the readiness rule.</div><p class="muted">Your other worked examples remain saved separately.</p></div>';return;}
  const n=workflow.nodes.find(n=>n.id===selected);if(!n){$('#inspector-content').innerHTML=`<div class="inspector-body"><h2>Your analysis, connected.</h2><p class="description">Choose a node to inspect its settings, or select a result to inspect its evidence.</p><div class="notice">${exampleKey(workflow)==='old-naledi'?'Real source boundary and historical facilities; generated sample locations. Select Facility access to explore the assumptions.':'The heat example uses synthetic neighborhoods and illustrative screening criteria.'}</div></div>`;return;}
  let content=title(n)+`<p class="description">${esc(n.type==='map_output'&&n.params.inputMode==='raster'?'Display native raster cells and the study polygon':TYPES[n.type].description)}. ${n.type==='policy'?'Turn computed spatial evidence into explicit, inspectable conclusions.':''}</p>`;
  if(n.type==='map_output'||n.type==='table_output'){
    const outputType=n.type==='table_output'?'table':'map',reasoning=n.params.inputMode==='decisions',raster=n.type==='map_output'&&n.params.inputMode==='raster';
    content+=`<div class="field"><label class="field-label" for="output-input-mode">Input mode</label><select id="output-input-mode"><option value="spatial" ${!reasoning&&!raster?'selected':''}>Point layers or spatial coverage</option><option value="decisions" ${reasoning?'selected':''}>Reasoning results</option>${n.type==='map_output'?`<option value="raster" ${raster?'selected':''}>Raster</option>`:''}</select><small>Changing mode removes existing input connectors; Undo restores them.</small></div>`;
    if(reasoning)content+=`<div class="field"><label class="field-label" for="output-view">Display as</label><select id="output-view"><option value="map" ${outputType==='map'?'selected':''}>Map</option><option value="table" ${outputType==='table'?'selected':''}>Table</option><option value="bars">Chart</option></select></div>`;
    content+=`<div class="field"><label class="field-label" for="${outputType}-label">Results tab name</label><input id="${outputType}-label" maxlength="60" value="${esc(n.params.label)}"></div><p class="description">${raster?'Connect Raster input or Clip raster. The native grid is displayed with its study boundary.':reasoning?'Connect an existing reasoning result. Decisions, missing evidence and supporting references are retained.':outputType==='table'?'Connect point data directly; no study area is required. Or connect a coverage result to include spatial relations and review decisions.':'Connect a study area and points, or use a coverage check that already contains both.'}${!reasoning&&!raster?' Connecting a coverage result or raster replaces the separate inputs; Undo restores them.':''}</p>`;
    content+=nodeInputs(n).map(([port,type])=>{const edge=workflow.edges.find(e=>e.to===n.id&&e.port===port);return `<div class="field"><label class="field-label" for="${outputType}-${port}">${({area:'Study area',coverage:'Or: spatial coverage check',decisions:'Reasoning result',raster:raster?'Raster':'Or: Raster'}[port]||'Point data '+(port==='points'?1:port.split('_')[1]))}</label><select id="${outputType}-${port}" data-map-port="${port}"><option value="">Select input</option>${workflow.nodes.filter(x=>TYPES[x.type].output===type).map(x=>`<option value="${esc(x.id)}" ${edge?.from===x.id?'selected':''}>${esc(x.params.label||TYPES[x.type].title)} · ${esc(x.id)}</option>`).join('')}</select></div>`;}).join('');
    content+=raster?'<div class="notice">Colors show relative cell values; gray cells are NoData. Download GeoTIFF preserves native values and georeferencing.</div>':reasoning?'<div class="notice">This is a presentation of existing results, with no new inference or exclusion.</div>':outputType==='table'?'<div class="notice">Rows include coordinates and all point attributes. Missing coordinates and excluded records remain visible. Search covers all rows and attributes; large tables use row and attribute pages. Works offline.</div>':'<div class="notice">The map fits the polygon and every located point, including outside records. Missing coordinates appear in a selectable list. This local map works offline.</div>';
  }else if(n.type==='raster_input'||n.type==='clip_raster'){
    content+=nodeInputs(n).map(([port,type])=>`<div class="field"><label class="field-label" for="raster-${port}">${port==='area'?'Study area':'Raster input'}</label><select id="raster-${port}" data-map-port="${port}"><option value="">Select input</option>${workflow.nodes.filter(x=>x.id!==n.id&&TYPES[x.type].output===type).map(x=>`<option value="${esc(x.id)}" ${workflow.edges.some(e=>e.to===n.id&&e.port===port&&e.from===x.id)?'selected':''}>${esc(x.params.label||TYPES[x.type].title)}</option>`).join('')}</select></div>`).join('');
    if(n.type==='raster_input'){content+='<button id="prepare-raster" class="button primary">Prepare GeoTIFF input</button><p class="description">Acquire a rectangular window and enter source metadata/citation. Reopen to edit metadata without re-uploading. Use Clip raster to apply the polygon mask.</p>';if(n.params.asset)content+=`<p>${esc(n.params.asset.source.filename)}<br>${n.params.asset.source.metadata.width} x ${n.params.asset.source.metadata.height} source cells; retained ${n.params.asset.metadata.width} x ${n.params.asset.metadata.height}.</p><details><summary>GeoTIFF metadata and source</summary><pre>${esc(JSON.stringify(n.params.asset,null,2))}</pre></details>`;}else content+='<div class="notice">Native grid, cell-center inclusion. Outside cells become NoData. Zero remains valid. No population total, resampling or reprojection.</div><button id="add-raster-map" class="button">Add raster map</button>';
  }else if(n.type==='area'){
    content+=`<form id="study-area-label-form" class="field"><label class="field-label" for="study-area-label">Study area label</label><input id="study-area-label" maxlength="100" required value="${esc(n.params.label||'My study area')}"><button type="submit" class="button small">Apply label</button></form>`;
    content+=n.params.source==='drawn'?`<div class="source-card"><span class="inspector-section">${n.params.geometry?'Selected geometry':'No geometry yet'}</span><h3>${esc(n.params.label)}</h3><p>${n.params.geometry?`${n.params.selectionMode==='bbox'?'Bounding box':'Polygon'} · ${n.params.geometry.coordinates[0].length-1} vertices`:'Draw a bounding box or polygon on the online map.'}</p></div><p class="description">The shape is stored in longitude, latitude order. Applying it generates N3 facts; Run workflow evaluates the readiness rule.</p>`:oldInspector(n);
    content+=`<button id="edit-study-area" class="button primary">${n.params.geometry?'Edit area on map':'Select area on map'}</button>${n.params.geometry?'<button id="area-view-n3" class="text-button">Inspect N3 facts and rule ↗</button>':''}<div class="notice">Evaluation prompt: what should the next workflow node receive from this selection?</div>`;
  }else if(n.type==='observations'){
    if(n.sourceMigration)content+='<p class="notice">This saved example source now uses the shared Input data editor. Its label, records and connections are retained.</p>';
    content+=`<div class="field"><label class="field-label" for="source-label">Source label</label><input id="source-label" maxlength="60" value="${esc(n.params.label||'Input data')}"></div><div class="source-card"><h3>${n.params.data.features.length} point records</h3><p>${esc(n.params.sourceInfo?.format||'Local input')} · ${n.params.data.features.filter(f=>!f.geometry).length} missing locations</p></div><button id="edit-input-data" class="button primary">Prepare input data</button><p class="description">Generate synthetic points, import CSV / GeoPackage / GeoJSON, or place pushpins with forms. Connect to Check spatial coverage before deciding how to handle outside records.</p>`;
  }else if(n.type==='coverage_check'){
    content+=nodeInputs(n).map(([port])=>{const input=workflow.edges.find(e=>e.to===n.id&&e.port===port);return `<div class="field"><label class="field-label" for="coverage-${port}">${port==='area'?'Study area':'Point data '+(port==='points'?1:port.split('_')[1])}</label><select id="coverage-${port}" data-coverage-port="${port}"><option value="">Select input</option>${workflow.nodes.filter(x=>TYPES[x.type].output===(port==='area'?'area':'points')).map(x=>`<option value="${esc(x.id)}" ${input?.from===x.id?'selected':''}>${esc(x.params.label||TYPES[x.type].title)} · ${esc(x.id)}</option>`).join('')}</select></div>`;}).join('');content+='<div class="notice">Inside and boundary points are included. Outside or missing-location records require review; they are not automatically classified as data errors.</div><p class="description">Run, then select a record in Coverage review or Coverage map. Exclude with a reason or edit the study boundary. Original input records are preserved.</p>';
  }else if(n.type==='measure_area'){
    const input=workflow.edges.find(e=>e.to===n.id&&e.port==='area'),output=result?.outputs.find(o=>o.nodeId===n.id);
    content+=`<div class="field"><label class="field-label" for="measure-area-source">Boundary input</label><select id="measure-area-source"><option value="">Select a Study area</option>${workflow.nodes.filter(x=>x.id!==n.id&&TYPES[x.type].output==='area').map(x=>`<option value="${esc(x.id)}" ${input?.from===x.id?'selected':''}>${esc(x.params.label||TYPES[x.type].title)} · ${esc(x.id)}</option>`).join('')}</select><small>Selecting an area adds its connector to the canvas.</small><label class="field-label" for="area-unit">Area unit</label><select id="area-unit" data-param="unit">${areaUnitOptions(n.params.unit)}</select></div><div class="source-card"><span class="inspector-section">${dirty?'Run to calculate or update':'Calculated area'}</span><h3>${!dirty&&output?.measurement?esc(formatArea(output.measurement)):'—'}</h3><p>Approximate surface area on a sphere.</p></div><p class="description">Outputs the same study area with its calculated area attached. Connect it to a Study area input, such as Check spatial coverage. Square metres are retained as the canonical value; the selected unit controls display.</p><div class="notice">This calculation uses the polygon itself, including its shape, rather than its bounding box. It does not measure terrain surface area.</div>`;
  }else if(Object.hasOwn(OLD_TYPES,n.type)){content+=oldInspector(n);
  }else if(n.type==='policy'){
    content+=`<span class="inspector-section">Rule settings</span><div class="field"><label class="field-label" for="threshold">Distance threshold</label><div class="input-unit"><input id="threshold" type="number" min="0" max="1000" step="0.5" value="${n.params.thresholdKm}"><span>km</span></div><small>Flag distances strictly greater than this value.</small></div><div class="rule-preview">When the heat alert is <b>active</b><br>and the nearest center is <b>more than ${n.params.thresholdKm} km away</b>,<br>flag the neighborhood for review.</div><span class="inspector-section">Missing evidence</span><p class="description">Missing coordinates, missing centers, or an unknown alert produce “Insufficient data”.</p><div class="inspector-divider"></div><span class="inspector-section">Execution engine</span><div class="engine-card"><span class="engine-mark">⋈</span><div><strong>EYE-JS · Notation3</strong><small>WebAssembly · runs on this device</small></div></div><div class="notice">Illustrative screening criteria. A flag is a reason to review evidence, not a risk estimate or an intervention order.</div>`;
  }else if(n.type==='alert'){
    content+=`<div class="field"><label class="field-label" for="alert-state">Heat alert status</label><select id="alert-state"><option value="true" ${n.params.active===true?'selected':''}>Active</option><option value="false" ${n.params.active===false?'selected':''}>Inactive</option><option value="null" ${n.params.active===null?'selected':''}>Unknown</option></select><label class="field-label" for="assessment-date">Assessment date</label><input id="assessment-date" type="date" value="${n.params.date}"><small>This example supplies a single alert status for all locations on the assessment date. No external alert feed is queried.</small></div>`;
  }else if((n.type==='places'||n.type==='centers')){
    content+=`<div class="field"><label class="field-label" for="source-label">Source label</label><input id="source-label" maxlength="60" value="${esc(n.params.label)}"></div><div class="detail-row"><span>Records</span><strong>${n.params.data.features.length}</strong></div><div class="detail-row"><span>Coordinates</span><strong>Longitude, latitude · CRS84</strong></div><button id="replace-data" class="button small">↑ Replace with local GeoJSON</button><ul class="record-list">${n.params.data.features.slice(0,12).map(f=>`<li>${esc(f.properties.name)}<span>${f.geometry?'Point':'Missing location'}</span></li>`).join('')}</ul><small class="muted">Point FeatureCollections only, up to 2,000 records. Files stay in this browser.</small>`;
  }else if(n.type==='nearest'){
    content+=`<span class="inspector-section">Spatial operation</span><div class="detail-row"><span>Method</span><strong>Haversine</strong></div><div class="detail-row"><span>Earth model</span><strong>Sphere · 6,371.0088 km</strong></div><div class="detail-row"><span>Units</span><strong>Kilometers</strong></div><div class="rule-preview">For each neighborhood, find the cooling center with the <b>shortest great-circle distance</b>.</div><p class="description">Computed in JavaScript before N3 inference. Source coordinates are longitude and latitude. Full precision is used for classification; the map and table round for display.</p><div class="notice">This is not road distance, travel time, facility availability, or evidence of service access.</div>`;
  }else if(n.type==='chart_output'||n.type==='output'){
    content+=`<div class="field"><label class="field-label" for="chart-decisions">Reasoning result</label><select id="chart-decisions" data-map-port="decisions"><option value="">Select input</option>${workflow.nodes.filter(x=>TYPES[x.type].output==='decisions').map(x=>`<option value="${esc(x.id)}" ${workflow.edges.some(e=>e.to===n.id&&e.port==='decisions'&&e.from===x.id)?'selected':''}>${esc(x.params.label||TYPES[x.type].title)} · ${esc(x.id)}</option>`).join('')}</select></div><p class="description">Counts every input record once by decision, access zone or evidence tier. Unclassified values are shown separately. Counts and source provenance are included in evidence; sample locations are not population estimates.</p><div class="field"><label class="field-label" for="output-label">Results tab name</label><input id="output-label" maxlength="60" value="${esc(n.params.label||'')}"><label class="field-label" for="output-view">Display as</label><select id="output-view"><option value="map" ${n.type==='output'&&n.params.view==='map'?'selected':''}>Map</option><option value="table" ${n.type==='output'&&n.params.view==='table'?'selected':''}>Table</option><option value="bars" ${n.type==='chart_output'||n.params.view==='bars'?'selected':''}>Bar chart</option></select></div><div class="rule-preview">Each output node creates a named tab in Results. Connect it to the results you want to display, then run the workflow.</div><p class="description">All output branches run together. Shared analysis nodes run once. Select a location in the map or table to inspect its evidence.</p>`;
  }
  if(['area','observations','places','centers','measure_area','coverage_check','map_output','table_output'].includes(n.type))content+='<div class="source-card" data-spatial-reference><span class="inspector-section">Coordinate reference system</span><h3>WGS84 · EPSG:4326</h3><p>Stored coordinates: longitude, latitude in degrees (OGC:CRS84). Other CRSs will require a Reproject node; reprojection is not implemented yet.</p></div>';
  if(n.type==='coverage_check'||((n.type==='map_output'||n.type==='table_output')&&(!n.params.inputMode||n.params.inputMode==='spatial')))content+=`<div class="inspector-actions"><button id="add-point-input" class="button small" ${(n.params.pointInputCount??1)>=MAX_POINT_LAYERS?'disabled':''}>＋ Add point input</button><button id="remove-point-input" class="button small" ${(n.params.pointInputCount??1)<=1?'disabled':''}>Remove last input</button></div><p class="muted">${n.type==='table_output'?'No boundary required for point inputs':'One study boundary'} · up to 8 point layers and 2,000 records combined. Each added point port needs a source. Removing the last port also removes its connector; Undo restores it. Adding a point input switches a Map or Table from reviewed input to direct layers.</p>`;
  content+=evidenceInspector(n);
  const incoming=workflow.edges.filter(e=>e.to===n.id);content+=`<div class="inspector-divider"></div><span class="inspector-section">Connections</span>${incoming.map(e=>`<div class="detail-row"><span>${esc(e.port)}</span><strong>${esc(workflow.nodes.find(x=>x.id===e.from)?.params.label||TYPES[workflow.nodes.find(x=>x.id===e.from)!.type].title)}</strong></div>`).join('')||'<p class="muted">Source node · no incoming connections</p>'}<div class="inspector-actions"><button id="duplicate-node" class="button small">Duplicate</button><button id="delete-node" class="button small danger">Remove node</button></div>`;
  $('#inspector-content').innerHTML=`<div class="inspector-body">${content}</div>`;
  optionalElement('#manage-references')?.addEventListener('click',()=>{let baseline=JSON.stringify(n.references||[]);openEvidenceEditor(n,refs=>{const current=workflow.nodes.find(x=>x.id===n.id);if(!current||JSON.stringify(current.references||[])!==baseline)throw new Error('The node changed while editing. Close and reopen its references.');const saved=change(w=>{required(w.nodes.find(x=>x.id===n.id)).references=structuredClone(refs);},{requirePersistence:true});if(saved)baseline=JSON.stringify(refs);return saved;});});
  optionalElement('#add-point-input')?.addEventListener('click',()=>change(w=>{const node=required(w.nodes.find(x=>x.id===n.id)) as WorkflowNode<'map_output'|'table_output'|'coverage_check'>;node.params.pointInputCount=(node.params.pointInputCount??1)+1;w.edges=w.edges.filter(e=>!(e.to===n.id&&e.port==='coverage'));}));
  optionalElement('#remove-point-input')?.addEventListener('click',()=>change(w=>{const node=required(w.nodes.find(x=>x.id===n.id)) as WorkflowNode<'map_output'|'table_output'|'coverage_check'>,count=node.params.pointInputCount??1;if(count>1){w.edges=w.edges.filter(e=>!(e.to===n.id&&e.port===pointPort(count-1)));node.params.pointInputCount=count-1;}}));
  document.querySelectorAll<HTMLInputElement>('#map-label,#table-label').forEach(el=>el.addEventListener('change',e=>change(w=>required(w.nodes.find(x=>x.id===n.id)).params.label=control(e).value.trim()||TYPES[n.type].title)));
  document.querySelectorAll<HTMLSelectElement>('[data-map-port]').forEach(el=>el.onchange=()=>change(w=>setConnection(w,el.value,n.id,el.dataset.mapPort!)));
  optionalElement('#prepare-raster')?.addEventListener('click',()=>{
    let source=workflow.nodes.find(x=>x.id===workflow.edges.find(e=>e.to===n.id&&e.port==='area')?.from);const visited=new Set<string>();
    while(source?.type==='measure_area'&&!visited.has(source.id)){visited.add(source.id);source=workflow.nodes.find(x=>x.id===workflow.edges.find(e=>e.to===source!.id&&e.port==='area')?.from);}
    if(source?.type!=='area'||(!source.params.geometry&&source.params.source==='drawn')){toast('Connect and define a study area before preparing the raster.');return;}
    const baseline=JSON.stringify(workflow);openRasterEditor(source.params.geometry||oldNalediBoundary as Boundary,asset=>{if(JSON.stringify(workflow)!==baseline)throw new Error('The workflow changed. Reopen Prepare GeoTIFF input.');return change(w=>{getNode(w,n.id,'raster_input').params.asset=asset;},{requirePersistence:true});},getNode(workflow,n.id,'raster_input').params.asset);
  });
  optionalElement('#add-raster-map')?.addEventListener('click',()=>change(w=>{const id=`map-${Date.now()}`;w.nodes.push({id,type:'map_output',x:n.x+270,y:n.y,params:{label:'Clipped raster',inputMode:'raster',pointInputCount:1}});w.edges.push({id:`e-${Date.now()}`,from:n.id,to:id,port:'raster'});selected=id;}));
  optionalElement('#study-area-label-form')?.addEventListener('submit',e=>{e.preventDefault();const input=$('#study-area-label'),label=input.value.trim();if(!label){input.setCustomValidity('Enter a label for the study area.');input.reportValidity();return;}change(w=>required(w.nodes.find(x=>x.id===n.id)).params.label=label);});
  optionalElement('#study-area-label')?.addEventListener('input',e=>control(e).setCustomValidity(''));
  optionalElement('#edit-input-data')?.addEventListener('click',()=>openInputDataEditor(getNode(workflow,n.id,'observations'),workflow.nodes.filter((x):x is WorkflowNode<'area'>=>x.type==='area'&&(!!x.params.geometry||x.params.source!=='drawn')).map(x=>({id:x.id,label:x.params.label||'Old Naledi',geometry:x.params.geometry||oldNalediBoundary as Boundary})),data=>validateGeoJSON(data,{attributes:true}),params=>{const persisted=change(w=>getNode(w,n.id,'observations').params=params,{requirePersistence:true});if(persisted)toast('Input edits saved on this device. Rerun the workflow to update results.');return persisted;}));
  document.querySelectorAll<HTMLSelectElement>('[data-coverage-port]').forEach(el=>el.onchange=()=>{const from=el.value,port=el.dataset.coveragePort!;change(w=>{w.edges=w.edges.filter(e=>!(e.to===n.id&&e.port===port));if(from)w.edges.push({id:`e-${Date.now()}`,from,to:n.id,port});});});
  optionalElement('#measure-area-source')?.addEventListener('change',e=>{const from=control(e).value;change(w=>{w.edges=w.edges.filter(x=>!(x.to===n.id&&x.port==='area'));if(from)w.edges.push({id:`e-${Date.now()}`,from,to:n.id,port:'area'});});});
  optionalElement('#edit-study-area')?.addEventListener('click',()=>openStudyAreaEditor(getNode(workflow,n.id,'area'),params=>change(w=>getNode(w,n.id,'area').params=params)));
  optionalElement('#area-view-n3')?.addEventListener('click',()=>{renderN3();switchView('rules');});
  $('#inspector-content').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('[data-param]').forEach(el=>el.addEventListener('change',()=>change(w=>updateParam(w,n.id,required(el.dataset.param),el.type==='number'?(el.value===''?NaN:Number(el.value)):el.value))));
  optionalElement('#threshold')?.addEventListener('change',e=>{const value=control(e).value===''?NaN:Number(control(e).value);change(w=>getNode(w,n.id,'policy').params.thresholdKm=value);});
  optionalElement('#alert-state')?.addEventListener('change',e=>change(w=>getNode(w,n.id,'alert').params.active=JSON.parse(control(e).value)));
  optionalElement('#assessment-date')?.addEventListener('change',e=>change(w=>getNode(w,n.id,'alert').params.date=control(e).value));
  optionalElement('#source-label')?.addEventListener('change',e=>change(w=>required(w.nodes.find(x=>x.id===n.id)).params.label=control(e).value.trim()||TYPES[n.type].title));
  optionalElement('#replace-data')?.addEventListener('click',()=>{importNode=n.id;$('#geojson-file').click();});
  optionalElement('#output-label')?.addEventListener('change',e=>change(w=>required(w.nodes.find(x=>x.id===n.id)).params.label=control(e).value.trim()));
  optionalElement('#output-view')?.addEventListener('change',e=>change(w=>{const index=w.nodes.findIndex(x=>x.id===n.id);w.nodes[index]={...w.nodes[index],type:'output',params:{label:n.params.label,view:control(e).value as 'map'|'table'|'bars'}};}));
  optionalElement('#output-input-mode')?.addEventListener('change',e=>change(w=>{const node=required(w.nodes.find(x=>x.id===n.id)) as WorkflowNode<'map_output'>;node.params.inputMode=control(e).value as 'spatial'|'decisions'|'raster';w.edges=w.edges.filter(edge=>edge.to!==n.id);}));
  $('#delete-node').onclick=()=>removeNodes([n.id]);
  $('#duplicate-node').onclick=()=>change(w=>{const copy=structuredClone(n);copy.id=`${n.type}-${Date.now()}`;copy.x+=40;copy.y+=90;w.nodes.push(copy);selected=copy.id;});
  if(busy)$('#inspector-content').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button').forEach(el=>el.disabled=true);
}
function removeNodes(ids:string[]){change(w=>{w.nodes=w.nodes.filter(n=>!ids.includes(n.id));w.edges=w.edges.filter(e=>!ids.includes(e.from)&&!ids.includes(e.to));if(ids.includes(w.outputId||''))w.outputId=w.nodes.find(n=>n.type==='output')?.id;if(ids.includes(selected||''))selected=null;});}
function renderEvidence(id:string){
  const result=activeOutput(),row=result?.rows.find(r=>r.id===id);if(!result||!row){selected=null;renderInspector();return;}
  if(result.kind==='point-table'){$('#inspector-content').innerHTML=pointTableEvidence(row as PointRow,dirty,esc);return;}
  if(result.kind==='spatial-map'){$('#inspector-content').innerHTML=mapEvidence(row as MapRow,dirty,esc);return;}
  if(result.kind==='spatial-coverage'){
    $('#inspector-content').innerHTML=coverageEvidence(result as unknown as CoverageValue,row as CoverageRow,dirty||busy,esc);
    optionalElement('#coverage-exclude-form')?.addEventListener('submit',e=>{e.preventDefault();if(dirty||busy)return;const reason=$('#exclusion-reason').value.trim();if(!reason)return;change(w=>{const check=getNode(w,required(result.checkNodeId),'coverage_check');check.params.exclusions=check.params.exclusions.filter(x=>!(x.sourceNodeId===row.sourceNodeId&&x.featureId===row.recordId));check.params.exclusions.push({sourceNodeId:required(row.sourceNodeId),featureId:required(row.recordId),signature:required(row.signature),reason});});});
    optionalElement('#coverage-restore')?.addEventListener('click',()=>{if(dirty||busy)return;change(w=>{const check=getNode(w,required(result.checkNodeId),'coverage_check');check.params.exclusions=check.params.exclusions.filter(x=>!(x.sourceNodeId===row.sourceNodeId&&x.featureId===row.recordId));});});
    optionalElement('#coverage-edit-boundary')?.addEventListener('click',()=>{if(dirty||busy)return;const area=workflow.nodes.find(n=>n.id===result.areaNodeId);if(area?.type==='area')openStudyAreaEditor(area,params=>change(w=>getNode(w,area.id,'area').params=params),{point:row,boundary:result.boundary});});
    return;
  }
  if(result.kind){$('#inspector-content').innerHTML=`<div class="inspector-body"><span class="inspector-section">Run evidence ${dirty?'· previous run':''}</span>${oldEvidence(result,row,esc)}</div>`;$('#inspect-rules').onclick=()=>switchView('rules');return;}
  const label=statusLabel(row.status);
  $('#inspector-content').innerHTML=`<div class="inspector-body"><span class="inspector-section">Decision evidence ${dirty?'· previous run':''}</span><h2>${esc(row.name)}</h2><span class="status-pill ${row.status}">${label}</span><p class="description">${esc(row.explanation)}</p><div class="inspector-divider"></div><span class="inspector-section">Inputs used in this run</span><div class="detail-row"><span>Nearest center</span><strong>${esc(row.center?.name||'Unknown')}</strong></div><div class="detail-row"><span>Distance</span><strong>${row.distanceKm===null?'Unknown':row.distanceKm!.toFixed(3)+' km'}</strong></div><div class="detail-row"><span>Threshold</span><strong>${result.threshold} km</strong></div><div class="detail-row"><span>Heat alert</span><strong>${result.alert!.active===null?'Unknown':result.alert!.active?'Active':'Inactive'}</strong></div><div class="detail-row"><span>Assessment date</span><strong>${result.alert!.date}</strong></div><div class="rule-preview">${row.status==='Review'?'The N3 rule matched an active alert and a distance above the threshold.':row.status==='Unknown'?'An explicit missing-evidence rule matched. This result is not a negative finding.':'The N3 rule matched an inactive alert or a distance at or below the threshold, with required evidence present.'}</div><span class="inspector-section">Derived assertion</span><pre>&lt;urn:fieldwork:place:${esc(row.id)}&gt;\n  fw:decision fw:${row.status}.</pre><small class="muted">This explanation is assembled from the run inputs and returned assertion. It is not an EYE proof certificate.</small><div class="inspector-actions"><button id="inspect-rules" class="button small">View N3 & evidence ↗</button></div></div>`;
  $('#inspect-rules').onclick=()=>switchView('rules');
}
function statusLabel(status:string|undefined){return ({Review:'Review',NoFlag:'No flag',Unknown:'Insufficient data'} as Record<string,string>)[status||'Unknown'];}
function renderCoverageAlert(){const checks=[...new Map((result?.outputs.filter(o=>o.kind==='spatial-coverage'&&o.view==='table')||[]).map(o=>[o.checkNodeId,o])).values()],count=checks.reduce((sum,o)=>sum+(o.reviewCount||0),0),empty=checks.some(o=>!o.rows.length||o.rows.length===o.excludedCount);$('#coverage-alert').hidden=!count&&!empty;$('#coverage-alert').textContent=(dirty?'Previous run — rerun after changes. ':'')+(count?`${count} records require spatial review. Outside or missing coordinates do not establish a data-quality error. Select a record to exclude with a reason or edit the boundary.`:empty?'Coverage cannot be established: no usable records remain.':'');}
function renderResults(){
  const output=activeOutput();activeOutputId=output?.nodeId||null;
  $('.results-panel').classList.toggle('spatial-results',['spatial-map','spatial-coverage'].includes(output?.kind||''));
  $('#result-tabs').innerHTML=(result?.outputs||[]).map(o=>`<button id="result-tab-${esc(o.nodeId)}" role="tab" aria-selected="${o.nodeId===activeOutputId}" tabindex="${o.nodeId===activeOutputId?0:-1}" aria-controls="${o.view}-panel" class="${o.nodeId===activeOutputId?'active':''}" data-output="${esc(o.nodeId)}">${o.view==='table'?'☷':o.view==='bars'?'▥':'◈'} ${esc(o.label)}</button>`).join('');
  const tabs=[...$('#result-tabs').querySelectorAll<HTMLButtonElement>('[data-output]')];
  tabs.forEach((b,i)=>{b.onclick=()=>{activeOutputId=b.dataset.output!;if(selected?.startsWith('result:'))selected=null;renderResults();render();$(`#result-tab-${activeOutputId}`).focus();};b.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].click();}};});
  $('#map-panel').hidden=!output||output.view!=='map';$('#table-panel').hidden=!output||output.view!=='table';$('#bars-panel').hidden=!output||output.view!=='bars';
  if(output)$(`#${output.view}-panel`).setAttribute('aria-labelledby',`result-tab-${output.nodeId}`);
  $('#results-empty').hidden=!!output;
  const rows=output?.rows||[];$('#result-metrics').innerHTML=output?`<span class="metric review"><b>${rows.filter(r=>r.status==='Review').length}</b> flagged for review</span><span class="metric"><b>${rows.filter(r=>r.status==='NoFlag').length}</b> no flag</span><span class="metric unknown"><b>${rows.filter(r=>r.status==='Unknown').length}</b> insufficient data</span>`:'';
  if(output?.kind==='facility-evidence')$('#result-metrics').innerHTML=['Direct','Contextual','Inferential','None'].map(t=>`<span class="metric"><b>${rows.filter(r=>r.tier===t).length}</b> ${tierLabel(t)}</span>`).join('');
  if(output?.kind==='access')$('#result-metrics').innerHTML+=`<span class="metric">${output.eligibleCount} eligible facilities · ${rows.length} ${output.locationSource?.kind==='input-points'?'input locations':'grid samples'}</span>`;
  if(output?.kind==='study-area')$('#result-metrics').innerHTML=`<span class="metric"><b>1</b> stored geometry</span><span class="metric">CRS84 · longitude, latitude</span><span class="metric">${output.ready?'N3: ready for spatial analysis':'Source preview'}</span>`;
  if(output?.kind==='study-area'&&output.measurement)$('#result-metrics').innerHTML=`<span class="metric"><b>${esc(formatArea(output.measurement))}</b> enclosed area</span><span class="metric">Approximate · spherical calculation</span>`;
  if(output?.kind==='spatial-coverage')$('#result-metrics').innerHTML=`<span class="metric"><b>${rows.filter(r=>r.decision==='Accept').length}</b> included</span><span class="metric review"><b>${output.reviewCount}</b> need review</span><span class="metric"><b>${output.excludedCount}</b> explicitly excluded</span>`;
  if(output?.kind==='point-table')$('#result-metrics').innerHTML=`<span class="metric"><b>${rows.length}</b> records</span><span class="metric"><b>${rows.filter(r=>!r.coordinates).length}</b> missing coordinates</span><span class="metric">CRS84 · longitude, latitude</span>`;
  const table=output?.pointTable?{head:'',body:''}:output?.kind==='spatial-map'?{head:'<th>Record</th><th>Spatial relation</th>',body:rows.map(r=>`<tr data-place="${esc(r.id)}"><td>${esc(r.name)}</td><td>${esc(relationLabel(r.relation!))}</td></tr>`).join('')}:output?.kind==='spatial-coverage'?coverageTable(output as unknown as CoverageValue,esc):resultTable(output,esc,statusLabel);$('#result-head').innerHTML=table.head;$('#result-rows').innerHTML=table.body;
  $('#result-search').value='';tablePage=0;tableAttributePage=0;
  $('#result-search').placeholder=output?.pointTable?'Search all records and attributes…':'Name, evidence, or service…';
  $('#point-table-controls').hidden=!output?.pointTable;
  $('#table-panel').classList.toggle('point-table',!!output?.pointTable);
  if(output?.pointTable)renderPointTable();
  $('#bars-panel').innerHTML=output?.chart?chartMarkup(output.chart,esc):'';
  $('#facility-legend').textContent=output?.kind?'Qualifying facility':'Cooling center';$('#map-note').textContent=output?.kind==='facility-evidence'?'Historical facilities · evidence tiers':output?.kind==='access'?`${output.locationSource?.kind==='input-points'?'Input locations':'Generated samples'} \u00b7 source boundary`:'Local locations · no external map tiles';
  $('#review-legend').textContent=output?.kind==='facility-evidence'?'Contextual / inferential':'Review';$('#clear-legend').textContent=output?.kind==='facility-evidence'?'Direct':'No flag';$('#unknown-legend').textContent=output?.kind==='facility-evidence'?'No evidence':'Unknown';$('#facility-legend').parentElement!.hidden=output?.kind==='facility-evidence';
  $('.map-legend').hidden=output?.kind==='study-area';
  if(output?.kind==='spatial-coverage'){$('#review-legend').textContent='Needs review';$('#clear-legend').textContent='Inside / boundary';$('#unknown-legend').textContent='Excluded';$('#facility-legend').parentElement!.hidden=true;$('#map-note').textContent='Missing coordinates appear in the review table';}
  if(output?.kind==='spatial-map'){
    $('#result-metrics').innerHTML=['Inside','Boundary','Outside','MissingLocation'].map(relation=>`<span class="metric"><b>${rows.filter(r=>r.relation===relation).length}</b> ${esc(relationLabel(relation as SpatialRelation))}</span>`).join('');
    $('#review-legend').textContent='Outside boundary';$('#clear-legend').textContent='Inside / on boundary';$('#unknown-legend').textContent='Missing coordinates (not plotted)';$('#facility-legend').parentElement!.hidden=true;$('#map-note').textContent='Local map · all located points remain visible';
  }
  const spatial=['spatial-map','spatial-coverage'].includes(output?.kind||''),missing=spatial?rows.filter(r=>!r.coordinates):[],outside=output?.kind==='spatial-map'?rows.filter(r=>r.relation==='Outside').length:0;
  $('#map-spatial-notice').hidden=output?.view!=='map'||(!outside&&!missing.length);
  $('#map-spatial-notice').textContent=`${outside?`${outside} outside ${outside===1?'point':'points'} shown in amber. `:''}${missing.length?`${missing.length} ${missing.length===1?'record has':'records have'} no coordinates and cannot be plotted. `:''}Outside does not establish a data-quality problem.`;
  $('#map-missing-records').innerHTML=missing.map(r=>`<button class="button small" data-map-record="${esc(r.id)}">${esc(r.name)} · missing coordinates</button>`).join('');
  $('#map-missing-records').hidden=output?.view!=='map';
  $('#map-missing-records').querySelectorAll<HTMLButtonElement>('[data-map-record]').forEach(el=>el.onclick=()=>selectResult(el.dataset.mapRecord!));
  $('#map-layer-list').hidden=output?.view!=='map'||!output.pointLayers?.length;
  $('#map-layer-list').innerHTML=(output?.pointLayers||[]).map(layer=>`<label><input type="checkbox" data-map-layer="${esc(layer.sourceNodeId)}" ${hiddenMapLayers.get(output!.nodeId)?.has(layer.sourceNodeId)?'':'checked'}> ${esc(layer.label)} (${layer.count})</label>`).join('');
  $('#map-layer-list').querySelectorAll<HTMLInputElement>('[data-map-layer]').forEach(el=>el.onchange=()=>{const hidden=hiddenMapLayers.get(output!.nodeId)||new Set();if(el.checked)hidden.delete(el.dataset.mapLayer!);else hidden.add(el.dataset.mapLayer!);hiddenMapLayers.set(output!.nodeId,hidden);renderMap();});
  $('#result-rows').querySelectorAll<HTMLElement & SVGElement>('[data-place]').forEach(el=>{el.onclick=()=>selectResult(el.dataset.place!);el.onkeydown=e=>{if(e.key==='Enter')selectResult(el.dataset.place!);};});
  const raster=output?.raster;$('#raster-download').hidden=!raster;$('#raster-download').onclick=()=>{if(raster)try{downloadRaster(raster);}catch(e){toast(errorMessage(e));}};if(raster){$('#result-metrics').textContent=`${raster.metadata.width} x ${raster.metadata.height} cells | ${raster.values.filter(v=>v!==null).length} valid | ${raster.mask?'Cell-center polygon mask':'Unmasked input window'} | Source-reported units: ${raster.asset.provenance?.units||'Not supplied'}`;$('.map-legend').hidden=true;}else $('.map-legend').hidden=false;
  renderMap();
  renderCoverageAlert();
  if(result){$('#n3-preview').textContent=result.receipts.map(receiptText).join('\n\n');}
}
function renderPointTable(){
  const table=pointTableMarkup(required(activeOutput()) as unknown as TableValue|CoverageValue,esc,{query:$('#result-search').value,page:tablePage,attributePage:tableAttributePage});
  $('#result-head').innerHTML=table.head;$('#result-rows').innerHTML=table.body;$('#point-table-controls').innerHTML=table.controls;
  $('#point-table-controls').querySelectorAll<HTMLButtonElement>('[data-table-page]').forEach(b=>b.onclick=()=>{tablePage=Number(b.dataset.tablePage);renderPointTable();});
  $('#point-table-controls').querySelectorAll<HTMLButtonElement>('[data-table-fields]').forEach(b=>b.onclick=()=>{tableAttributePage=Number(b.dataset.tableFields);renderPointTable();});
  $('#result-rows').querySelectorAll<HTMLElement & SVGElement>('[data-place]').forEach(row=>{row.onclick=()=>selectResult(row.dataset.place!);row.onkeydown=e=>{if(e.key==='Enter')selectResult(row.dataset.place!);};});
}
function selectResult(id:string){selected=`result:${id}`;flow?.update(workflow,null,statuses);renderInspector();renderMap();}
function renderMap(){
  const result=activeOutput(),svg=$('#map'), rows=result?.rows||[], centers=result?.centers||[], points=[...rows.filter(r=>r.coordinates).map(r=>r.coordinates!),...centers.filter(c=>c.geometry).map(c=>c.geometry!.coordinates)];
  if(result?.raster){svg.innerHTML=rasterSvg(result.raster);return;}
  if(result?.pointTable){svg.innerHTML='';return;}
  if(result?.kind==='study-area'){svg.innerHTML=areaSvg(required(result.boundary),result.label);return;}
  if(result?.boundary){svg.innerHTML=oldMap(result,selected,esc,statusLabel);svg.querySelectorAll<HTMLElement & SVGElement>('[data-place]').forEach(el=>{el.style.display=hiddenMapLayers.get(result.nodeId)?.has(el.dataset.layer!)?'none':'';el.onclick=()=>selectResult(el.dataset.place!);el.onkeydown=e=>{if(e.key==='Enter')selectResult(el.dataset.place!);};});return;}
  if(!points.length){svg.innerHTML='<text x="425" y="140" text-anchor="middle">Run the workflow to map its local results.</text>';return;}
  let minX=Math.min(...points.map(p=>p[0])),maxX=Math.max(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxY=Math.max(...points.map(p=>p[1]));
  const midY=(minY+maxY)/2,cos=Math.max(.05,Math.cos(midY*Math.PI/180)),width=Math.max((maxX-minX)*cos,.01),height=Math.max(maxY-minY,.01),scale=Math.min(660/width,210/height);
  const midX=(minX+maxX)/2,proj=(c:Position)=>[425+(c[0]-midX)*cos*scale,142-(c[1]-midY)*scale];
  const grid=Array.from({length:12},(_,i)=>`<path class="gridline" d="M${i*80} 0V295"/>`).join('')+Array.from({length:5},(_,i)=>`<path class="gridline" d="M0 ${i*65}H850"/>`).join('');
  const focus=rows.find(r=>`result:${r.id}`===selected);
  let content=`<rect width="850" height="295" fill="#f0f3e9"/>${grid}<path d="M15 252 C110 140 158 268 261 142 S432 34 536 155 S710 244 844 67" fill="none" stroke="#e0e8d5" stroke-width="60" opacity=".5"/><path d="M15 252 C110 140 158 268 261 142 S432 34 536 155 S710 244 844 67" fill="none" stroke="#e6eddc" stroke-width="30"/><text x="20" y="24" style="letter-spacing:1.5px;font-size:9px">LOCAL SPATIAL PREVIEW</text><text x="815" y="30" text-anchor="middle">N</text><path d="M815 37l-4 13 4-3 4 3z" fill="#86987b"/>`;
  if(focus?.coordinates&&focus.center){const a=proj(focus.coordinates),b=proj(focus.center.coordinates);content+=`<path d="M${a.join(' ')}L${b.join(' ')}" stroke="#698b78" stroke-dasharray="4 4" stroke-width="1.5"/>`;}
  for(const c of centers){if(!c.geometry)continue;const [x,y]=proj(c.geometry!.coordinates),radius=result!.threshold!/111.195*scale;content+=`<circle cx="${x}" cy="${y}" r="${radius}" fill="#abc2a0" opacity=".10"/><circle cx="${x}" cy="${y}" r="${radius}" fill="none" stroke="#a0b596" stroke-dasharray="3 5" opacity=".6"/><rect x="${x-6}" y="${y-6}" width="12" height="12" rx="2" fill="#3e6860" stroke="white" stroke-width="2"/><text x="${x+11}" y="${y+17}" style="font-size:9px">${esc(c.properties.name)}</text>`;}
  for(const r of rows){if(!r.coordinates)continue;const [x,y]=proj(r.coordinates),color={Review:'#c18b4f',NoFlag:'#699178',Unknown:'#a89b87'}[r.status!];content+=`<g class="location" data-place="${esc(r.id)}" tabindex="0" role="button" aria-label="${esc(r.name)}, ${statusLabel(r.status)}"><title>${esc(r.name)} · ${statusLabel(r.status)} · ${r.distanceKm?.toFixed(2)??'Unknown'} km</title>${focus?.id===r.id?`<circle cx="${x}" cy="${y}" r="12" fill="none" stroke="${color}" opacity=".7"/>`:''}<circle cx="${x}" cy="${y}" r="6" fill="${color}" stroke="white" stroke-width="2"/><text class="location-label" x="${x+10}" y="${y-8}">${esc(r.name)}</text></g>`;}
  content+=`<text x="20" y="276" style="font-size:9px">${minX.toFixed(3)}° to ${maxX.toFixed(3)}° longitude · circles show ${result!.threshold} km (approx.)</text>`;
  const missing=rows.filter(r=>!r.coordinates).length;if(missing)content+=`<text x="830" y="276" text-anchor="end" style="font-size:9px">${missing} unmapped · see table</text>`;
  svg.innerHTML=content;svg.querySelectorAll<HTMLElement & SVGElement>('[data-place]').forEach(el=>{el.onclick=()=>selectResult(el.dataset.place!);el.onkeydown=e=>{if(e.key==='Enter')selectResult(el.dataset.place!);};});
}
function reason(input:string):Promise<ReasonerQuad[]>{return new Promise<ReasonerQuad[]>((resolve,reject)=>{
  if(!worker)worker=new Worker('./build/reasoning-worker.js');const id=++seq;
  const timeout=setTimeout(()=>{worker?.terminate();worker=null;reject(new Error('Reasoning exceeded 45 seconds. Reduce the dataset and try again.'));},45000);
  worker.onmessage=({data}:MessageEvent<ReasoningResponse>)=>{if(data.id!==id)return;clearTimeout(timeout);if('error' in data)reject(new Error(data.error));else resolve(data.quads);};
  worker.onerror=e=>{clearTimeout(timeout);worker?.terminate();worker=null;reject(new Error(`Reasoning worker failed: ${errorMessage(e)}`));};worker.postMessage({id,input} satisfies ReasoningRequest);
});}
async function run(){if(busy)return;try{executionPlan(workflow);}catch(e){toast(errorMessage(e));return;}busy=true;statuses={};render();const snapshot=structuredClone(workflow);try{const next=await executeWorkflow(snapshot,reason,(id,state)=>{statuses[id]=state;flow?.update(workflow,selected,statuses);});result=next;runWorkflow=snapshot;dirty=false;renderResults();toast(`Complete: ${result.outputs.length} output tabs updated.`);}catch(e){toast(`Workflow stopped: ${errorMessage(e)}`);$('#workflow-state').textContent='Run failed';console.error(e);}finally{busy=false;render();}}
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function switchView(view:string){$('.work-area').classList.remove('results-expanded');$('#expand-results').textContent='⛶ Expand';$('#expand-results').setAttribute('aria-expanded','false');$('#workflow-view').hidden=view!=='workflow';$('#rules-view').hidden=view!=='rules';document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function validConnection(c:Connection|Edge){const a=workflow.nodes.find(n=>n.id===c.source),b=workflow.nodes.find(n=>n.id===c.target);return !!a&&!!b&&a.id!==b.id&&!!TYPES[a.type].output&&nodeInputs(b).find(([p])=>p===c.targetHandle)?.[1]===TYPES[a.type].output;}
mountCanvas($('#canvas'),{describe:describeNode,ready(api){flow=api;render();setTimeout(()=>flow!.fit(),80);},select(id){selected=id;render();},clear(){selected=null;render();},move(id,p){change(w=>Object.assign(required(w.nodes.find(n=>n.id===id)),{x:p.x,y:p.y}),{spatial:false});},connect(c){change(w=>setConnection(w,c.source,c.target,required(c.targetHandle)));},valid:validConnection,remove:removeNodes,removeEdges(ids){change(w=>w.edges=w.edges.filter(e=>!ids.includes(e.id)));},zoom(z){$('#zoom-value').textContent=`${Math.round(z*100)}%`;}});
$('#run-button').onclick=run;$('#node-search').oninput=e=>renderLibrary(control(e).value);$('#zoom-in').onclick=()=>flow?.zoomIn();$('#zoom-out').onclick=()=>flow?.zoomOut();$('#fit-button').onclick=()=>flow?.fit();
$('#undo-button').onclick=()=>{if(busy||!history.length)return;future.push(structuredClone(workflow));workflow=history.pop()!;dirty=true;statuses={};save();render();};
$('#redo-button').onclick=()=>{if(busy||!future.length)return;history.push(structuredClone(workflow));workflow=future.pop()!;dirty=true;statuses={};save();render();};
$('#reset-button').onclick=()=>{change(w=>{const key=exampleKey(w);replaceWorkflow(w,template(key));selected=key==='old-naledi'?'access':'criteria';});renderLibrary();flow?.fit();};
$('#example-select').onchange=e=>loadExample(control(e).value);
$('#blank-add').onclick=()=>$('#node-library [data-add="area"]')?.click();
$('#new-workflow').onclick=()=>{if(busy)return;loadExample('blank');change(w=>{replaceWorkflow(w,blankWorkflow());selected=null;});result=null;runWorkflow=null;activeOutputId=null;renderResults();render();switchView('workflow');};
$('#result-search').oninput=e=>{if(activeOutput()?.pointTable){tablePage=0;renderPointTable();return;}$('#result-rows').querySelectorAll('tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(control(e).value.toLowerCase()));};
$('#expand-results').onclick=()=>{const expanded=$('.work-area').classList.toggle('results-expanded');$('#expand-results').textContent=expanded?'↙ Split view':'⛶ Expand';$('#expand-results').setAttribute('aria-expanded',String(expanded));};
$('#encrypted-export').onclick=()=>{try{openPackageDialog(workflow,validateWorkflow,applyImportedWorkflow);}catch(error){toast(errorMessage(error));}};
function applyImportedWorkflow(next:Workflow){const persisted=change(w=>{replaceWorkflow(w,next);selected=next.nodes[0]?.id;},{requirePersistence:true});if(!persisted)throw new Error('Workflow could not be saved. The previous workflow is unchanged.');renderLibrary();flow?.fit();toast('Workflow imported. Run it to update results.');}
$('#export-button').onclick=async()=>{try{const exported=await workflowDocument(workflow);download(exported.schema==='fieldwork/bundle/1'?'fieldwork-workflow-bundle.json':'fieldwork-workflow.json',JSON.stringify(exported,null,2));}catch(error){toast(errorMessage(error));}};$('#import-button').onclick=()=>$('#workflow-file').click();
$('#workflow-file').onchange=async e=>{const file=(control(e) as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>MAX_BUNDLE_BYTES)throw new Error('Workflow or bundle exceeds the 20 MB import limit.');if(file.name.toLowerCase().endsWith('.zip')){openPackageDialog(workflow,validateWorkflow,applyImportedWorkflow,file);control(e).value='';return;}const next=await importWorkflowDocument(JSON.parse(await file.text()),validateWorkflow);const persisted=change(w=>{replaceWorkflow(w,next);selected=next.nodes.find(n=>n.type==='output')?.id;},{requirePersistence:true});if(!persisted)throw new Error('Workflow could not be saved. The previous workflow is unchanged.');renderLibrary();flow?.fit();toast('Workflow imported. Run it to update results.');}catch(err){toast(errorMessage(err));}control(e).value='';};
$('#geojson-file').onchange=async e=>{const file=(control(e) as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>5e6)throw new Error('GeoJSON file is too large (5 MB maximum).');const data=validateGeoJSON(JSON.parse(await file.text()));change(w=>{const n=w.nodes.find(n=>n.id===importNode);if(!n)throw new Error('Source node no longer exists.');updateParam(w,n.id,'data',data);});toast('Local geographic data loaded. Run to update results.');}catch(err){toast(errorMessage(err));}control(e).value='';};
$('#download-evidence').onclick=async()=>{if(!result||!runWorkflow){toast('Run the workflow first.');return;}const snapshot=structuredClone({schema:'fieldwork/run/1',workflow:runWorkflow,...result});try{const attachments=await exportEvidenceFiles(snapshot.workflow);download('fieldwork-run-receipt.json',JSON.stringify({...snapshot,...(attachments.length?{attachments}:{})},null,2));}catch(error){toast(errorMessage(error));}};
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view!));
$('#help-button').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as Element).tagName)){e.preventDefault();$(e.shiftKey?'#redo-button':'#undo-button').click();}});
const requestedExample=new URLSearchParams(location.search).get('example');
if(requestedExample&&['old-naledi','heat','blank','coverage'].includes(requestedExample)&&requestedExample!==exampleKey(workflow)){save();try{const saved=JSON.parse(localStorage.getItem(WORKSPACES)||'{}')[requestedExample];workflow=saved?validateWorkflow(saved):template(requestedExample);}catch{workflow=template(requestedExample);}selected=requestedExample==='old-naledi'?'access':'criteria';}
renderLibrary();renderResults();save();render();mountPanelLayout();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(async()=>{const ok=!!(await caches.match('./vendor/eye-21.1.24.js'));$('#offline-status').innerHTML=ok?'<i></i> Available offline':'<i></i> Offline setup incomplete';}).catch(()=>{$('#offline-status').textContent='Offline cache unavailable';});}else{$('#offline-status').textContent='Offline cache unsupported';}
if(workflow.nodes.length)setTimeout(run,350);
