import type {WorkflowNode,Escape} from './types.js';
import {CATCHMENT_TYPES} from './catchments.js';
export function catchmentInspector(n:WorkflowNode,esc:Escape):string{
  if(!Object.hasOwn(CATCHMENT_TYPES,n.type))return '';
  let html=`<label class="field-label" for="catchment-label">Node label</label><input id="catchment-label" data-catchment-param="label" maxlength="100" value="${esc(n.params.label||'')}"><div class="notice">Local computation. Parameters and source links appear in N3 & evidence. Outputs are modeled catchments, not observed facility use.</div>`;
  const number=(key:string,label:string,value:number,min:number,max:number,step=1)=>`<div class="field"><label class="field-label" for="catchment-${key}">${label}</label><input id="catchment-${key}" data-catchment-param="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;
  if(n.type==='voronoi'||n.type==='isochrone')html+=number('zone','Computation CRS: WGS84 UTM zone',n.params.zone,1,60)+`<label class="field-label" for="catchment-hemisphere">Hemisphere</label><select id="catchment-hemisphere" data-catchment-param="hemisphere"><option value="north" ${n.params.hemisphere==='north'?'selected':''}>North</option><option value="south" ${n.params.hemisphere==='south'?'selected':''}>South</option></select><p class="muted">Input/output: CRS84. Computation projects to the selected UTM CRS. Restricted to a local zone; no global distance claim.</p>`;
  if(n.type==='isochrone')html+=`<label class="field-label" for="catchment-thresholds">Time thresholds (minutes, comma separated)</label><input id="catchment-thresholds" data-catchment-param="thresholds" value="${(n.params.thresholds||[]).join(', ')}"><small>Up to six increasing values. Leave empty to use the single travel time below.</small><label><input type="checkbox" data-catchment-param="fillHoles" ${n.params.fillHoles?'checked':''}> Fill interior holes (illustrative regions)</label><p class="muted">Infill can include locations not reachable on the network. Keep off for corridor coverage.</p>`+number('minutes','Travel time (minutes)',n.params.minutes,.1,60,.1)+number('speedMPerMin','Walking speed (metres/minute)',n.params.speedMPerMin,1,200)+number('bufferM','Corridor buffer (metres)',n.params.bufferM,1,100)+number('maxSnapM','Maximum node snap distance (metres)',n.params.maxSnapM,0,1000)+`<label class="field-label" for="catchment-direction">Travel direction</label><select id="catchment-direction" data-catchment-param="direction"><option value="outbound" ${n.params.direction==='outbound'?'selected':''}>From site (outbound)</option><option value="inbound" ${n.params.direction==='inbound'?'selected':''}>To site (inbound)</option></select><p class="muted">Dijkstra uses directed edges and supplied metre lengths. Includes partial curved edges. Buffer approximates off-street coverage; holes remain unless infill is enabled. Snap distance is not charged as travel time. Graph extent may truncate coverage.</p>`;
  if(n.type==='summarize_polygons')html+=`<label class="field-label" for="catchment-boundary">Points on polygon boundary</label><select id="catchment-boundary" data-catchment-param="boundary"><option value="include" ${n.params.boundary==='include'?'selected':''}>Include in every matching polygon</option><option value="exclude" ${n.params.boundary==='exclude'?'selected':''}>Exclude boundary points</option></select><label class="field-label" for="catchment-valueField">Optional numeric field to sum</label><input id="catchment-valueField" data-catchment-param="valueField" maxlength="100" value="${esc(n.params.valueField)}"><p class="muted">Location count is always retained. Empty field: chart counts locations. Enter DEATHS: chart sums deaths. Missing/non-numeric values are counted separately. Multiple memberships are reported, never silently deduplicated.</p>`;
  if(n.type==='network_input')html+=`<label class="field-label" for="network-input-method">Input method</label><select id="network-input-method" data-catchment-param="inputMethod"><option value="file" ${n.params.inputMethod!=='osm'?'selected':''}>Upload network file</option><option value="osm" ${n.params.inputMethod==='osm'?'selected':''}>Download from OpenStreetMap</option></select>`+(n.params.inputMethod==='osm'?number('marginM','Download margin outside study bounds (metres)',n.params.marginM??250,0,2000)+`<button class="button primary" id="download-network">Download and save OSM network</button><p>Uses the connected Study area's bounding box plus margin (up to 6 km across). Whole ways may extend beyond it. Sends those bounds to overpass-api.de; no key required. Retains topology rather than cutting edges at the polygon. Max 2 MB / 2,000 nodes / 5,000 edges.</p>`:'')+`<p>${n.params.data.nodes.length} nodes · ${n.params.data.edges.length} directed edges</p><p>${esc(n.params.data.source)}</p><label class="field-label" for="network-upload">Upload GraphML or JSON</label><input id="network-upload" type="file" accept=".json,.graphml"><p>Files retain their existing network extent. Attach a URL or PDF reference below for citation.</p><details><summary>Edit bounded network JSON</summary><label class="field-label" for="network-json">Network JSON: nodes, edges, source</label><textarea id="network-json" rows="10">${esc(JSON.stringify(n.params.data,null,2))}</textarea><button class="button" id="save-network">Save network edits</button><label class="field-label" for="network-file">Upload GraphML / JSON (up to 2 MB)</label><input id="network-file" type="file" accept=".json,.graphml,application/json,application/xml"><p>Directed edges require from, to, lengthM and optional CRS84 geometry. Reverse travel requires a reverse edge. Full contract: worked-example guide.</p></details>`;
  if(n.type==='network_input')html+='<p id="network-download-status" role="status"></p><p class="muted">One OSM request at a time; at least 60 seconds between attempts. No automatic retries. Saved networks remain usable offline. Changing the boundary or buffer does not expand a saved graph.</p>';
  return html;
}
