import type {WorkflowNode,Boundary,ObservationParams,PointCollection,PointFeature,AttributeDefinition,FormField,SourceInfo,AttributeType} from './types.js';
import type {CSVTable,CSVMapping} from './input-data.js';
import type {Database} from 'sql.js';
import {element,optionalElement} from './dom.js';
import {errorMessage,required} from './guards.js';
const attributeType=(value:string):AttributeType=>{if(!ATTRIBUTE_TYPES.includes(value))throw new Error('Choose a supported attribute type.');return value as AttributeType;};
import L from 'leaflet';
import {parseCSV,csvPoints,syntheticPoints,loadSQLite,geoPackageLayers,geoPackagePoints} from './input-data.js';
import {geometryBounds} from './study-area.js';
import {ATTRIBUTE_TYPES,validAttributeKey,parseAttributeValue,parseValueSet,validateAttributeSchema} from './attribute-schema.js';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const markup=`<dialog id="input-dialog" aria-labelledby="input-dialog-title"><div class="area-dialog-heading"><h2 id="input-dialog-title">Prepare input data</h2><button id="input-close" class="icon-button" aria-label="Close input editor">×</button></div>
<div class="input-editor-body"><label class="field-label" for="input-mode">Input method</label><select id="input-mode"><option value="synthetic">Generate synthetic points</option><option value="csv">Import CSV</option><option value="gpkg">Import GeoPackage</option><option value="geojson">Import GeoJSON</option><option value="pins">Place pushpins on map</option></select>
<div id="input-synthetic"><label class="field-label" for="synthetic-boundary">Study area for generation</label><select id="synthetic-boundary"></select><div class="input-inline"><label>Inside points<input id="synthetic-inside" type="number" value="20" min="1" max="2000"></label><label>Outside points for testing<input id="synthetic-outside" type="number" value="2" min="0" max="1999"></label><label>Seed<input id="synthetic-seed" type="number" value="42" min="0" max="4294967295"></label></div><button id="generate-input" class="button small">Generate points</button><p class="muted">Synthetic demonstration records. Generating replaces this draft.</p></div>
<div id="input-file-panel" hidden><label class="field-label" for="input-file">Local file · 5 MB maximum</label><input id="input-file" type="file"><div id="csv-mapping" hidden><div class="input-inline"><label>Longitude<select id="csv-longitude"></select></label><label>Latitude<select id="csv-latitude"></select></label><label>Record ID<select id="csv-id"></select></label><label>Label<select id="csv-name"></select></label></div><button id="csv-preview" class="button small">Preview mapped records</button></div><div id="gpkg-mapping" hidden><label for="gpkg-layer">Point layer · EPSG:4326</label><select id="gpkg-layer"></select><button id="gpkg-preview" class="button small">Preview layer</button></div><p class="muted">Up to 2,000 points. Scalar attributes are retained. CSV needs longitude/latitude degrees. GeoPackage supports 2D POINT layers in EPSG:4326.</p></div>
<div id="input-pins" hidden><p>Click the map to add a pin. Select or drag a pin to edit it.</p><label><input id="pins-online" type="checkbox"> Online basemap</label><label class="field-label" for="pin-record">Select a record to edit, including missing locations</label><select id="pin-record"></select><div class="pin-record-actions"><button id="pin-delete" class="button danger" disabled>Delete Pin</button><label><input id="pin-use-uuid" type="checkbox"> Generate UUIDs for new pins</label></div><p class="muted">Existing record IDs stay unchanged. Delete Pin removes the selected record from this draft; Save Edits keeps the change.</p><div class="pin-layout"><div><div id="pin-map"></div><button id="pins-fit" class="button small">Fit pins and study area</button><span id="pins-map-status" class="muted"></span></div><div id="pin-form"></div></div><details><summary>Add a form field</summary><div class="input-inline"><label>Field key<input id="pin-field-key" maxlength="60" placeholder="household_size"></label><label>Label<input id="pin-field-label" maxlength="100" placeholder="Household size"></label><label>Type<select id="pin-field-type"><option value="text">Text</option><option value="number">Number</option><option value="integer">Whole number</option><option value="date">Date</option><option value="boolean">Yes / no</option></select></label><label>Default value<input id="pin-field-default" maxlength="1000"></label><label>Allowed values (optional, one per line)<textarea id="pin-field-values" maxlength="10000" rows="3"></textarea></label></div><button id="pin-add-field" class="button small">Add field</button></details></div>
<p id="input-summary" class="notice" role="status"></p><details><summary>Preview first two records</summary><pre id="input-preview"></pre></details></div><div class="area-dialog-actions"><div id="input-error" role="alert" aria-atomic="true" hidden><span class="input-error-icon" aria-hidden="true">!</span><div><strong>Action needed</strong><p id="input-error-message"></p><small>Your edits remain in this draft until saved.</small></div></div><span id="input-save-status" role="status">Choose Save Edits to keep changes on this device.</span><button id="input-cancel" class="button">Cancel</button><button id="input-apply" class="button primary">Save Edits</button><div id="input-discard-prompt" hidden role="alert"><p>You have unsaved edits. Keep editing to save them, or discard them.</p><button id="input-keep-editing" class="button">Keep editing</button><button id="input-discard-edits" class="button danger">Discard edits</button></div></div></dialog>`;
export function openInputDataEditor(node:WorkflowNode<'observations'>,areas:{id:string;label:string;geometry:Boundary}[],validateData:(data:unknown)=>PointCollection,onApply:(params:ObservationParams)=>boolean|void){
  if(!document.querySelector('#input-dialog'))document.body.insertAdjacentHTML('beforeend',markup);
  const dialog=element('#input-dialog'),$=<S extends string>(s:S)=>element(s,dialog);
  let data=structuredClone(node.params.data),fields:FormField[]=structuredClone(node.params.fields||[{key:'category',label:'Category',type:'text'},{key:'notes',label:'Notes',type:'text'}]),source:SourceInfo=structuredClone(node.params.sourceInfo||{format:'manual'}),csv:CSVTable|null=null,db:Database|null=null,map:L.Map|null=null,markers:L.LayerGroup|null=null,tiles:L.TileLayer|null=null,selected:string|null=null,serial=0,requestId=0,closed=false;
  let attributeRules=structuredClone(node.params.attributeRules||[]),dirty=false;
  $('#pin-use-uuid').checked=node.params.pinIdStrategy==='uuid';$('#input-discard-prompt').hidden=true;
  $('#input-save-status').textContent='Choose Save Edits to keep changes on this device.';
  const markDirty=()=>{dirty=true;$('#input-save-status').textContent='Unsaved edits · choose Save Edits to keep them.';$('#input-discard-prompt').hidden=true;};
  dialog.oninput=e=>{if(e.target instanceof Element&&e.target.matches('input,select,textarea')&&!['input-mode','pin-record','pins-online','synthetic-boundary'].includes(e.target.id))markDirty();};
  for(const id of ['key','label','default','values'])($('#pin-field-'+id) as HTMLInputElement).value='';$('#pin-field-type').value='text';
  const checkDraft=(next:unknown,nextFields=fields,nextRules=attributeRules)=>{const normalized=validateData(next);validateAttributeSchema(normalized,nextFields,nextRules);return normalized;};
  const error=(e:unknown)=>{const message=e?errorMessage(e):'';$('#input-error-message').textContent=message;$('#input-error').hidden=!message;};
  const preview=()=>{$('#input-summary').textContent=`${data.features.length} draft point records · ${data.features.filter(f=>!f.geometry).length} missing locations`;$('#input-preview').textContent=JSON.stringify(data.features.slice(0,2),null,2);$('#input-apply').disabled=false;};
  const accept=(next:unknown,info:SourceInfo)=>{data=checkDraft(next);source=info;selected=null;markDirty();error('');preview();};
  $('#synthetic-boundary').innerHTML=areas.map(a=>`<option value="${esc(a.id)}">${esc(a.label)}</option>`).join('');
  for(const key of ['inside','outside','seed'] as const)($('#synthetic-'+key) as HTMLInputElement).value=String(source[key]??{inside:20,outside:2,seed:42}[key]);
  $('#input-file').value='';$('#csv-mapping').hidden=true;$('#gpkg-mapping').hidden=true;$('#input-mode').value=['synthetic','csv','gpkg','geojson','pins'].includes(source.format)?source.format:'synthetic';
  const metadata=(file:File)=>({format:$('#input-mode').value,filename:file.name,bytes:file.size,importedAt:new Date().toISOString()});
  function mode(){const kind=$('#input-mode').value;$('#input-synthetic').hidden=kind!=='synthetic';$('#input-file-panel').hidden=!['csv','gpkg','geojson'].includes(kind);$('#input-pins').hidden=kind!=='pins';$('#input-file').accept=({csv:'.csv',gpkg:'.gpkg',geojson:'.geojson,.json'} as Record<string,string>)[kind]||'';error('');if(kind==='pins')setTimeout(()=>{if(!closed){ensureMap();map!.invalidateSize();fit();}},0);}
  let activeMode=$('#input-mode').value;
  $('#input-mode').onchange=()=>{if(activeMode==='pins'&&!savePin()){$('#input-mode').value=activeMode;return;}activeMode=$('#input-mode').value;requestId++;mode();if(activeMode==='pins')preview();};
  $('#generate-input').onclick=()=>{try{const area=areas.find(a=>a.id===$('#synthetic-boundary').value);if(!area)throw new Error('Define a study area before generating sample points.');const options=Object.fromEntries(['inside','outside','seed'].map(k=>[k,Number(($('#synthetic-'+k) as HTMLInputElement).value)]));accept(syntheticPoints(area.geometry,options),{format:'synthetic',areaNodeId:area.id,boundarySnapshot:structuredClone(area.geometry),...options,method:'Seeded uniform rejection sampling in longitude/latitude',generatedAt:new Date().toISOString()});}catch(e){error(e);}};
  $('#input-file').onchange=async()=>{const file=$('#input-file').files?.[0];if(!file)return;const request=++requestId,kind=$('#input-mode').value;$('#input-apply').disabled=true;$('#csv-mapping').hidden=true;$('#gpkg-mapping').hidden=true;error('');try{if(file.size>5e6)throw new Error('File exceeds the 5 MB prototype limit.');db?.close();db=null;
    if(kind==='gpkg'){const bytes=new Uint8Array(await file.arrayBuffer()),SQL=await loadSQLite();if(closed||request!==requestId)return;db=new SQL.Database(bytes);const layers=geoPackageLayers(db);$('#gpkg-layer').innerHTML=layers.map(l=>`<option value="${esc(l.table_name)}">${esc(l.table_name)}</option>`).join('');$('#gpkg-mapping').hidden=false;$('#gpkg-preview').onclick=()=>{try{accept(geoPackagePoints(required(db),$('#gpkg-layer').value),{...metadata(file),layer:$('#gpkg-layer').value,crs:'EPSG:4326'});}catch(e){$('#input-apply').disabled=true;error(e);}};$('#gpkg-preview').click();}
    else {const text=await file.text();if(closed||request!==requestId)return;if(kind==='geojson')accept(JSON.parse(text),metadata(file));else{csv=parseCSV(text);const aliases:Record<string,string[]>={longitude:['longitude','lon','lng','x'],latitude:['latitude','lat','y'],id:['id','fid'],name:['name','label']};for(const key of Object.keys(aliases)){const select=$('#csv-'+key) as HTMLSelectElement;select.innerHTML='<option value="-1">'+(['id','name'].includes(key)?'Generate automatically':'Select column')+'</option>'+csv.headers.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');select.value=String(csv.headers.findIndex(h=>aliases[key].includes(h.toLowerCase())));select.onchange=()=>$('#input-apply').disabled=true;}$('#csv-mapping').hidden=false;$('#csv-preview').onclick=()=>{try{accept(csvPoints(required(csv),Object.fromEntries(Object.keys(aliases).map(k=>[k,Number(($('#csv-'+k) as HTMLSelectElement).value)])) as unknown as CSVMapping),{...metadata(file),crs:'CRS84'});}catch(e){$('#input-apply').disabled=true;error(e);}};$('#csv-preview').click();}}
  }catch(e){error(e);}};
  $('#gpkg-layer').onchange=()=>$('#input-apply').disabled=true;
  function fit(){if(!map)return;const points=data.features.filter(f=>f.geometry).map((f):L.LatLngTuple=>[f.geometry!.coordinates[1],f.geometry!.coordinates[0]]);for(const a of areas){const b=geometryBounds(a.geometry);points.push([b[1],b[0]],[b[3],b[2]]);}if(points.length)map.fitBounds(points,{padding:[25,25],maxZoom:16});}
  function ensureMap(){if(map){drawPins();renderPin();return;}map=L.map($('#pin-map'),{center:[-24.685,25.901],zoom:14,minZoom:2,maxZoom:19,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false,doubleClickZoom:false});tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{noWrap:true,maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>'});$('#pins-online').checked=navigator.onLine;$('#pins-online').onchange=()=>{if($('#pins-online').checked)tiles!.addTo(map!);else map!.removeLayer(tiles!);$('#pins-map-status').textContent=$('#pins-online').checked?'Online basemap requested':'Basemap off · pins stay local';};tiles.on('tileerror',()=>$('#pins-map-status').textContent='Tiles unavailable · pin editing remains local');$('#pins-online').dispatchEvent(new Event('change'));for(const a of areas)L.geoJSON(a.geometry,{interactive:false,style:{color:'#176b59',weight:2,fillOpacity:.08}}).addTo(map);markers=L.layerGroup().addTo(map);map.on('click',e=>{if(data.features.length>=2000){error('At most 2,000 pins are supported.');return;}if(!savePin())return;let id:string;do{serial++;id=$('#pin-use-uuid').checked?crypto.randomUUID():`pin-${serial}`;}while(data.features.some(f=>f.id===id));const properties:PointFeature['properties']={name:`Pin ${serial}`,capturedAt:new Date().toISOString()};for(const f of fields)if(f.defaultValue!==undefined)properties[f.key]=f.defaultValue;const next:PointFeature={type:'Feature',id,properties,geometry:{type:'Point',coordinates:[e.latlng.lng,e.latlng.lat]}};try{validateData({type:'FeatureCollection',features:[next]});data.features.push(next);selected=id;source={...source,format:'pins'};markDirty();drawPins();renderPin();preview();}catch(err){error(err);}});drawPins();renderPin();}
  function drawPins(){if(!markers)return;$('#pin-record').innerHTML='<option value="">Add a pin or select a record</option>'+data.features.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(f.properties.name)}</option>`).join('');markers.clearLayers();for(const f of data.features){if(!f.geometry)continue;const label=document.createElement('span');label.textContent=f.properties.name;const m=L.marker([f.geometry.coordinates[1],f.geometry.coordinates[0]],{draggable:true,icon:L.divIcon({className:'input-pin'+(f.id===selected?' selected':''),html:'●',iconSize:[20,20],iconAnchor:[10,10]})}).bindTooltip(label).addTo(markers);m.on('click',()=>{if(!savePin())return;selected=f.id;renderPin();drawPins();});m.on('dragend',()=>{const p=m.getLatLng();try{const current=required(data.features.find(x=>x.id===f.id)),next=structuredClone(current);next.geometry={type:'Point',coordinates:[p.lng,p.lat]};validateData({type:'FeatureCollection',features:[next]});current.geometry=next.geometry;markDirty();if(selected===f.id){$('#pin-longitude').value=String(p.lng);$('#pin-latitude').value=String(p.lat);}preview();}catch(e){error(e);drawPins();}});}}
  function renderPin(){const f=data.features.find(x=>x.id===selected);$('#pin-delete').disabled=!f;if(!f){$('#pin-form').innerHTML='<p>Select or add a pin.</p>';return;}
    const inferred=Object.keys(f.properties).filter(k=>!['name','capturedAt'].includes(k)&&!fields.some(x=>x.key===k)).map((key):FormField=>({key,label:key,type:typeof f.properties[key]==='number'?'number':typeof f.properties[key]==='boolean'?'boolean':'text',...attributeRules.find(r=>r.key===key)})),all=[...fields,...inferred];
    $('#pin-form').innerHTML=`<label class="field-label" for="pin-id">Record ID</label><input id="pin-id" readonly value="${esc(f.id)}"><label class="field-label" for="pin-name">Pin label</label><input id="pin-name" maxlength="100" value="${esc(f.properties.name)}"><div class="input-inline"><label>Longitude<input id="pin-longitude" type="number" step="any" value="${f.geometry?.coordinates[0]??''}"></label><label>Latitude<input id="pin-latitude" type="number" step="any" value="${f.geometry?.coordinates[1]??''}"></label></div><p class="muted">Captured: ${esc(f.properties.capturedAt||'Not supplied')}</p>${all.map((field,i)=>{const value=Object.hasOwn(f.properties,field.key)?f.properties[field.key]??'':field.defaultValue??'';return `<label class="field-label" for="pin-attr-${i}">${esc(field.label)}</label>${field.type==='boolean'?`<select id="pin-attr-${i}" data-pin-key="${esc(field.key)}" data-pin-type="boolean"><option value="">Not given</option><option value="true" ${value===true?'selected':''}>Yes</option><option value="false" ${value===false?'selected':''}>No</option></select>`:`<input id="pin-attr-${i}" data-pin-key="${esc(field.key)}" data-pin-type="${field.type}" type="${field.type==='integer'?'number':field.type}" ${field.type==='number'?'step="any"':''} maxlength="1000" value="${esc(value)}">`}`;}).join('')}<button id="pin-save" class="button small">Update pin draft</button><p class="muted">Choose Save Edits below to save this input on your device.</p>`;
    for(const el of dialog.querySelectorAll<HTMLInputElement>('input[data-pin-type="text"]')){const value=f.properties[el.dataset.pinKey!]??fields.find(x=>x.key===el.dataset.pinKey!)?.defaultValue??'';if(el.dataset.pinKey==='notes'||String(value).includes('\n')){const text=document.createElement('textarea');text.id=el.id;text.dataset.pinKey=el.dataset.pinKey!;text.dataset.pinType='text';text.maxLength=1000;text.rows=2;text.value=String(value);el.replaceWith(text);}}
    for(const field of all){if(!field.allowedValues)continue;const old=[...dialog.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-pin-key]')].find(el=>el.dataset.pinKey===field.key),select=document.createElement('select'),value=old!.value;select.id=old!.id;select.dataset.pinKey=field.key;select.dataset.pinType=field.type;select.innerHTML='<option value="">Not given</option>'+field.allowedValues.map(v=>`<option value="${esc(String(v))}">${esc(String(v))}</option>`).join('');select.value=value;old!.replaceWith(select);}
    for(const el of dialog.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-pin-key]')){
      const key=el.dataset.pinKey!,shared=fields.some(x=>x.key===key),label=$(`label[for="${el.id}"]`),pair=document.createElement('div');pair.className='pin-attribute';
      label.before(pair);pair.append(label);pair.insertAdjacentHTML('beforeend',shared?(key==='category'?'<p class="pin-field-help">Optional label for this location, such as Clinic, Household or Water point. This does not classify the pin automatically or change its marker.</p>':key==='notes'?'<p class="pin-field-help">Optional free-text observations about this location.</p>':''):`<label class="field-label">Attribute name (key)<input data-pin-rename="${esc(key)}" aria-label="Key for ${esc(key)}" value="${esc(key)}" maxlength="100"></label><span class="muted">Value</span>`);pair.append(el);pair.insertAdjacentHTML('beforeend',`<small class="muted">Data type: ${esc({text:'Text',number:'Number',integer:'Whole number',boolean:'Yes / no',date:'Date'}[attributeType(el.dataset.pinType!)])}${all.find(d=>d.key===key)?.allowedValues?' · constrained value set':''}</small>`);
      if(!shared){const remove=document.createElement('button');remove.type='button';remove.className='text-button';remove.textContent='Remove pair';remove.dataset.removePair=key;remove.onclick=()=>{if(!savePin())return;const record=data.features.find(x=>x.id===selected);delete record!.properties[pair.querySelector<HTMLInputElement>('[data-pin-rename]')!.value.trim()];renderPin();preview();};pair.append(remove);}
    }
    $('#pin-save').insertAdjacentHTML('beforebegin','<fieldset class="pin-new-pair"><legend>Add an attribute to this pin</legend><p class="pin-field-help">The attribute name describes what you record (for example, household_size). The value is your answer (for example, 5).</p><label class="field-label">Attribute name (key)<input id="pin-pair-key" maxlength="60" placeholder="household_size"></label><label class="field-label">Value type<select id="pin-pair-type"><option value="text">Text</option><option value="number">Number</option><option value="integer">Whole number</option><option value="boolean">Yes / no</option><option value="date">Date</option></select></label><label class="field-label">Allowed values (optional, one per line)<textarea id="pin-pair-values" maxlength="10000" rows="3"></textarea></label><label class="field-label">Value<textarea id="pin-pair-value" maxlength="1000" rows="2"></textarea></label><button id="pin-add-pair" class="button small" type="button">Add pair</button><small>The value belongs to this pin. Type and allowed values apply to this key throughout this input. Use Add a form field below to show a field on every pin.</small></fieldset>');
    $('#pin-add-pair').onclick=()=>{if(!hasPendingPair()){error('Enter a key and value for the new pair.');return;}if(savePin()){renderPin();preview();}};
    $('#pin-pair-key').onchange=()=>{const rule=attributeRules.find(r=>r.key===$('#pin-pair-key').value.trim());if(rule){$('#pin-pair-type').value=rule.type;$('#pin-pair-values').value=(rule.allowedValues||[]).join('\n');}};
    $('#pin-save').onclick=()=>{if(savePin()){source={...source,format:'pins'};drawPins();renderPin();preview();}};
  }
  function hasPendingPair(){return !!optionalElement('#pin-pair-key',dialog)&&[$('#pin-pair-key').value.trim(),$('#pin-pair-value').value,$('#pin-pair-values').value.trim()].some(Boolean);}
  function clearPair(){for(const suffix of ['key','value','values'])($('#pin-pair-'+suffix) as HTMLInputElement|HTMLTextAreaElement).value='';$('#pin-pair-type').value='text';}
  function savePin(){const f=data.features.find(x=>x.id===selected);if(!f||!optionalElement('#pin-name',dialog))return true;try{
    const next=structuredClone(f),lon=$('#pin-longitude').value.trim(),lat=$('#pin-latitude').value.trim();next.properties.name=$('#pin-name').value.trim()||f.id;next.geometry=lon&&lat?{type:'Point',coordinates:[Number(lon),Number(lat)]}:null;
    const values=[...dialog.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-pin-key]')];for(const el of values)delete next.properties[el.dataset.pinKey!];
    const nextRules=structuredClone(attributeRules);for(const el of values){if(!el.checkValidity())throw new Error('Correct the invalid pin attribute.');const key=el.closest('.pin-attribute')?.querySelector<HTMLInputElement>('[data-pin-rename]')?.value.trim()??el.dataset.pinKey!;if(key!==el.dataset.pinKey!&&!validAttributeKey(key))throw new Error('Use a key beginning with a letter; name and capture time are reserved.');if(Object.hasOwn(next.properties,key))throw new Error('Each key must be unique on this pin.');next.properties[key]=parseAttributeValue(el.value,attributeType(el.dataset.pinType!));if(key!==el.dataset.pinKey!){const rule=attributeRules.find(r=>r.key===el.dataset.pinKey!);if(rule&&!nextRules.some(r=>r.key===key))nextRules.push({...rule,key});}}
    const pending=hasPendingPair();if(pending){
      const key=$('#pin-pair-key').value.trim(),type=attributeType($('#pin-pair-type').value);
      const rejectKey=(message:string)=>{$('#pin-pair-key').setAttribute('aria-invalid','true');$('#pin-pair-key').focus();throw new Error(message);};
      if(!key)rejectKey('Enter an attribute name for the new value, or clear the new value and allowed values to save only your other edits.');
      if(['name','capturedAt','constructor','prototype'].includes(key))rejectKey(`"${key}" is reserved. ${key==='name'?'Edit Pin label above instead.':key==='capturedAt'?'Capture time is recorded automatically.':'Choose another attribute name.'} Clear the new attribute fields to save only your other edits.`);
      if(!validAttributeKey(key))rejectKey(`"${key}" is not a valid attribute name. Use 1-60 letters, numbers or underscores, starting with a letter (for example, household_size). Spaces are not allowed.`);
      if(Object.hasOwn(next.properties,key)||fields.some(x=>x.key===key))rejectKey(`"${key}" already exists on this pin. Edit its value above, then clear the new attribute fields before saving.`);
      const allowedValues=parseValueSet($('#pin-pair-values').value,type),definition={key,type,...(allowedValues?{allowedValues}:{})},existing=nextRules.find(r=>r.key===key);
      if(existing&&(existing.type!==type||JSON.stringify(existing.allowedValues)!==JSON.stringify(definition.allowedValues)))throw new Error('This key already has a definition. Use its existing type and allowed values.');
      next.properties[key]=parseAttributeValue($('#pin-pair-value').value,type);if(!existing)nextRules.push(definition);
    }
    const normalized=checkDraft({...data,features:data.features.map(record=>record.id===selected?next:record)},fields,nextRules);
    if(JSON.stringify(normalized)!==JSON.stringify(data)||JSON.stringify(nextRules)!==JSON.stringify(attributeRules)){markDirty();source={...source,format:'pins'};}
    data=normalized;attributeRules=nextRules;if(pending)clearPair();error('');return true;
  }catch(e){error(e);return false;}}
  function addField(required=false){
    const pending=['key','label','default','values'].some(id=>($('#pin-field-'+id) as HTMLInputElement).value!=='')||$('#pin-field-type').value!=='text';if(!pending&&!required)return;
    const key=$('#pin-field-key').value.trim(),label=$('#pin-field-label').value.trim(),type=attributeType($('#pin-field-type').value),raw=$('#pin-field-default').value;
    if(!validAttributeKey(key)||fields.some(f=>f.key===key)||attributeRules.some(f=>f.key===key)||!label||fields.length>=30)throw new Error('Use a unique field key beginning with a letter and a label; at most 30 fields.');
    const allowedValues=parseValueSet($('#pin-field-values').value,type),definition={key,label,type,...(allowedValues?{allowedValues}:{}),...(raw?{defaultValue:parseAttributeValue(raw,type)}:{})},nextFields=[...fields,definition];
    checkDraft(data,nextFields);fields=nextFields;markDirty();for(const id of ['key','label','default','values'])($('#pin-field-'+id) as HTMLInputElement).value='';$('#pin-field-type').value='text';
  }
  $('#pin-add-field').onclick=()=>{try{if(!savePin())return;renderPin();addField(true);renderPin();error('');}catch(e){error(e);}};
  $('#pin-delete').onclick=()=>{if(!selected)return;data.features=data.features.filter(x=>x.id!==selected);selected=null;source={...source,format:'pins'};markDirty();error('');renderPin();drawPins();preview();};
  $('#pins-fit').onclick=fit;
  $('#pin-record').onchange=()=>{const next=$('#pin-record').value;if(!savePin()){drawPins();return;}selected=next||null;renderPin();drawPins();};
  $('#input-apply').onclick=()=>{try{if($('#input-mode').value==='pins'){if(!savePin())return;renderPin();addField();}data=checkDraft(data);const saved=onApply({...structuredClone(node.params),data:structuredClone(data),fields:structuredClone(fields),attributeRules:structuredClone(attributeRules),sourceInfo:structuredClone(source),pinIdStrategy:$('#pin-use-uuid').checked?'uuid':'sequential'});if(saved===false)throw new Error('Edits could not be saved on this device. Your draft is still open; try Save Edits again.');dirty=false;dialog.close();}catch(e){error(e);}};
  const requestClose=()=>{if(!dirty){dialog.close();return;}$('#input-discard-prompt').hidden=false;$('#input-keep-editing').focus();};
  $('#input-close').onclick=requestClose;$('#input-cancel').onclick=requestClose;dialog.oncancel=e=>{e.preventDefault();requestClose();};
  $('#input-keep-editing').onclick=()=>{$('#input-discard-prompt').hidden=true;$('#input-apply').focus();};$('#input-discard-edits').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{closed=true;requestId++;db?.close();map?.stop();map?.remove();},{once:true});
  error('');dialog.showModal();preview();mode();
}
