import type {PointComparison} from './point-comparison.js';
import type {Escape,PointCollection,Position} from './types.js';

export function pointComparisonMarkup(comparison:PointComparison,escape:Escape):string{
  const c=comparison,all=[...c.original.features,...c.moved.features,...c.pumps.features].map(f=>f.geometry!.coordinates).concat([c.originalMean,c.movedMean]);
  const west=Math.min(...all.map(p=>p[0])),east=Math.max(...all.map(p=>p[0])),south=Math.min(...all.map(p=>p[1])),north=Math.max(...all.map(p=>p[1]));
  const latitude=(south+north)/2,cos=Math.cos(latitude*Math.PI/180),width=Math.max((east-west)*cos,0.0001),height=Math.max(north-south,0.0001);
  const scale=Math.min(365/width,220/height),centerX=(west+east)/2,centerY=(south+north)/2;
  const project=(p:Position)=>[210+(p[0]-centerX)*cos*scale,146-(p[1]-centerY)*scale];
  const map=(label:string,points:PointCollection,mean:Position,nearest:{id:string;name:string;distanceM:number},color:string,side:string)=>{
    const [mx,my]=project(mean),pump=c.pumps.features.find(f=>f.id===nearest.id)!,[px,py]=project(pump.geometry!.coordinates);
    const dots=points.features.map(f=>{const [x,y]=project(f.geometry!.coordinates);return `<circle data-${side}-point cx="${x.toFixed(3)}" cy="${y.toFixed(3)}" r="2.1" fill="${color}" fill-opacity=".55"><title>${escape(f.properties.name)}</title></circle>`;}).join('');
    const pumps=c.pumps.features.map((f,i)=>{const [x,y]=project(f.geometry!.coordinates);return `<g data-pump="${escape(f.id)}"><rect x="${(x-3.5).toFixed(3)}" y="${(y-3.5).toFixed(3)}" width="7" height="7" fill="#176b88" stroke="white" stroke-width="1"/><title>${escape(f.properties.name)}</title><text x="${(x+5).toFixed(3)}" y="${(y-5).toFixed(3)}" font-size="8">P${i+1}</text></g>`;}).join('');
    return `<article class="comparison-card"><h3>${escape(label)}</h3><svg class="comparison-map" viewBox="0 0 420 295" role="img" aria-label="${escape(label)}: ${points.features.length} locations, eight pump locations and projected mean center"><rect width="420" height="295" fill="#f4f7f2"/><path d="M20 256H400M20 36V256" stroke="#cbd8cb" stroke-width="1"/><path d="M${mx.toFixed(3)} ${my.toFixed(3)}L${px.toFixed(3)} ${py.toFixed(3)}" stroke="#6c568a" stroke-width="1.5" stroke-dasharray="4 3"/>${dots}${pumps}<g data-mean="${side}"><circle cx="${mx.toFixed(3)}" cy="${my.toFixed(3)}" r="9" fill="white" stroke="#6c568a" stroke-width="2"/><path d="M${(mx-5).toFixed(3)} ${my.toFixed(3)}H${(mx+5).toFixed(3)}M${mx.toFixed(3)} ${(my-5).toFixed(3)}V${(my+5).toFixed(3)}" stroke="#6c568a" stroke-width="1.5"/></g><text x="12" y="282" font-size="9">Dots: locations · blue squares: pumps · crosshair: mean center</text></svg><p>Mean center: ${mean[1].toFixed(5)}° N, ${Math.abs(mean[0]).toFixed(5)}° ${mean[0]<0?'W':'E'}. Nearest pump: ${escape(nearest.name)} (${nearest.distanceM.toFixed(1)} m).</p></article>`;
  };
  return `<div class="comparison-summary"><strong>Mean-center shift: ${c.centerShiftM.toFixed(1)} m</strong><span>Unweighted projected means · ${escape(c.crs)} · ${c.original.features.length} locations per map · identical extent and scale</span></div><div class="comparison-grid">${map('Original locations · private',c.original,c.originalMean,c.originalNearestPump,'#8a654c','original')}${map('Moved locations · private comparison',c.moved,c.movedMean,c.movedNearestPump,'#d28c38','moved')}</div><p class="comparison-caveat">Both maps and this evaluation retain original coordinates. Center movement does not establish privacy or preserve individual location accuracy. Pump positions provide geographic context; they do not establish historical pump use.</p>`;
}
