import {RASTER_SOURCE_FIELDS,validateRasterProvenance,WORLDPOP_BOTSWANA,WORLDPOP_BOTSWANA_FILENAME} from './raster-provenance.js';
import type {RasterProvenance} from './raster-provenance.js';
import type {Boundary} from './types.js';
import type {RasterAsset,RasterGrid,RasterMetadata} from './raster.js';
import {inspectRaster,rasterWindow,readRasterWindow,encodeRaster} from './raster.js';
import {contentHash} from './project-files.js';
import {storePDFs} from './evidence-storage.js';

export function openRasterEditor(boundary:Boundary,onSave:(asset:RasterAsset)=>boolean,existing?:RasterAsset):void{
  const dialog=document.createElement('dialog');dialog.id='raster-dialog';dialog.setAttribute('aria-labelledby','raster-title');
  dialog.innerHTML='<h2 id="raster-title">Prepare raster input</h2><p>Select a local GeoTIFF. Only a native-resolution window around the connected study area will be saved. Clip raster applies the polygon mask separately.</p><label for="raster-file" class="field-label">GeoTIFF file</label><input id="raster-file" type="file" accept=".tif,.tiff,image/tiff"><p id="raster-status" role="status"></p><details><summary>Extracted GeoTIFF metadata (from the file)</summary><pre id="raster-metadata"></pre></details><p>First version: one band, north-up WGS84 / EPSG:4326. No resampling or reprojection. Pixel values are not automatically interpreted as population totals.</p><p id="raster-error" role="alert" hidden></p><div class="package-actions"><button id="raster-cancel" class="button">Cancel</button><button id="raster-save" class="button primary" disabled>Save raster window</button></div>';
  const fields=document.createElement('fieldset');fields.id='raster-source-fields';fields.innerHTML='<legend>Source metadata and citation (entered separately)</legend><p>Entered by the workflow author; separate from extracted GeoTIFF metadata. These details follow the raster through clipping and export.</p><button type="button" id="raster-worldpop" class="button" hidden>Use Botswana WorldPop source details</button>'+Object.entries(RASTER_SOURCE_FIELDS).map(([key,label])=>'<label class="field-label" for="raster-source-'+key+'">'+label+'</label><textarea id="raster-source-'+key+'" data-source-field="'+key+'" rows="'+(['citation','notes'].includes(key)?3:1)+'" maxlength="'+(['citation','notes'].includes(key)?4000:2000)+'"></textarea>').join('');dialog.querySelector('#raster-error')!.before(fields);
  const controls=[...fields.querySelectorAll<HTMLTextAreaElement>('[data-source-field]')],fill=(values:RasterProvenance)=>controls.forEach(el=>el.value=values[el.dataset.sourceField as keyof RasterProvenance]||''),collect=():RasterProvenance=>Object.fromEntries(controls.map(el=>[el.dataset.sourceField!,el.value.trim()]).filter(([,v])=>v));fill(existing?.provenance||{});
  const preset=fields.querySelector<HTMLButtonElement>('#raster-worldpop')!;preset.hidden=existing?.source.filename!==WORLDPOP_BOTSWANA_FILENAME;preset.onclick=()=>fill(WORLDPOP_BOTSWANA);
  document.body.append(dialog);const fileInput=dialog.querySelector<HTMLInputElement>('#raster-file')!,save=dialog.querySelector<HTMLButtonElement>('#raster-save')!,cancel=dialog.querySelector<HTMLButtonElement>('#raster-cancel')!,error=dialog.querySelector<HTMLElement>('#raster-error')!,status=dialog.querySelector<HTMLElement>('#raster-status')!,preview=dialog.querySelector<HTMLElement>('#raster-metadata')!;
  let file:File|undefined,metadata:RasterMetadata|undefined,busy=false,serial=0;
  if(existing){save.disabled=false;save.textContent='Save raster and source metadata';status.textContent='Edit source metadata without selecting the original file again.';preview.textContent=JSON.stringify(existing.source.metadata,null,2);}
  const fail=(e:unknown)=>{error.textContent=e instanceof Error?e.message:String(e);error.hidden=false;error.scrollIntoView({block:'nearest'});};
  cancel.onclick=()=>dialog.close();dialog.oncancel=e=>{if(busy)e.preventDefault();};dialog.onclose=()=>{serial++;file=undefined;metadata=undefined;dialog.remove();};
  fileInput.onchange=async()=>{const request=++serial;file=fileInput.files?.[0];metadata=undefined;save.disabled=true;error.hidden=true;if(!file){save.disabled=!existing;return;}preset.hidden=file.name!==WORLDPOP_BOTSWANA_FILENAME;if(existing){fill({});status.textContent='Replacement file selected: review and re-enter source metadata.';}status.textContent='Reading GeoTIFF metadata…';try{const source=await inspectRaster(file);if(request!==serial)return;const window=rasterWindow(source,boundary);metadata=source;preview.textContent=JSON.stringify({sourceFile:file.name,sourceBytes:file.size,source,retainedWindow:window,retainedCells:(window[2]-window[0])*(window[3]-window[1])},null,2);status.textContent=`Source: ${source.width} × ${source.height}. Retain ${window[2]-window[0]} × ${window[3]-window[1]} cells.`;save.disabled=false;}catch(e){if(request===serial){status.textContent='Raster cannot be prepared.';fail(e);}}};
  save.onclick=async()=>{if(((!file||!metadata)&&!existing)||busy)return;busy=true;save.disabled=true;cancel.disabled=true;fileInput.disabled=true;fields.disabled=true;error.hidden=true;status.textContent='Reading the selected window and saving…';try{
    const provenance=collect();validateRasterProvenance(provenance);if(!file&&existing){const asset={...structuredClone(existing),provenance};if(!onSave(asset))throw new Error('Source metadata could not be saved. Retry Save.');dialog.close();return;}if(!file||!metadata)throw new Error('Select a supported raster file.');
    const window=rasterWindow(metadata,boundary),data=await readRasterWindow(file,metadata,window),bytes=encodeRaster(data);if(bytes.length>5_000_000)throw new Error('Retained GeoTIFF exceeds 5 MB. Use a smaller study area.');
    const retained=await inspectRaster(new Blob([bytes])),asset:RasterAsset={provenance,filename:'raster-window.tif',mediaType:'image/tiff',bytes:bytes.length,sha256:await contentHash(bytes),metadata:retained,source:{filename:file.name,bytes:file.size,lastModified:file.lastModified,metadata},window};
    await storePDFs(new Map([[asset.sha256,bytes]]),new Map([[asset.sha256,{...asset,asset}]]));if(!onSave(asset))throw new Error('Raster metadata could not be saved. Your previous project is unchanged; retry Save.');dialog.close();
  }catch(e){fail(e);status.textContent='Raster has not been applied to the project.';}finally{busy=false;save.disabled=false;cancel.disabled=false;fileInput.disabled=false;fields.disabled=false;}};
  dialog.showModal();
}
export function rasterSvg(grid:RasterGrid):string{
  const {metadata:m,values}=grid,canvas=document.createElement('canvas');canvas.width=m.width;canvas.height=m.height;const context=canvas.getContext('2d')!,pixels=context.createImageData(m.width,m.height);let min=Infinity,max=-Infinity;
  for(const value of values)if(value!==null){min=Math.min(min,value);max=Math.max(max,value);}for(let i=0;i<values.length;i++){const value=values[i];if(value===null)continue;const t=max===min?0.5:(value-min)/(max-min);pixels.data.set([Math.round(245-215*t),Math.round(250-145*t),Math.round(220-135*t),255],i*4);}context.putImageData(pixels,0,0);
  const [west,south,east,north]=m.bounds,cos=Math.cos((north+south)/2*Math.PI/180),scale=Math.min(800/((east-west)*cos),245/(north-south)),width=(east-west)*cos*scale,height=(north-south)*scale,x=(850-width)/2,y=(295-height)/2;
  const path=grid.boundary?(grid.boundary.type==='Polygon'?[grid.boundary.coordinates]:grid.boundary.coordinates).flatMap(poly=>poly.map(ring=>ring.map((p,i)=>`${i?'L':'M'}${x+(p[0]-west)*cos*scale},${y+(north-p[1])*scale}`).join(' ')+'Z')).join(' '):'';
  return `<rect x="${x}" y="${y}" width="${width}" height="${height}" fill="#e8ece5"/><image href="${canvas.toDataURL()}" x="${x}" y="${y}" width="${width}" height="${height}" preserveAspectRatio="none" style="image-rendering:pixelated"/><path d="${path}" fill="none" stroke="#193d33" stroke-width="1.4"/><text x="15" y="18" font-size="11">Native raster cells · ${grid.mask?'polygon center mask':'unmasked input window'} · gray = NoData</text>`;
}
export function downloadRaster(grid:RasterGrid):void{const url=URL.createObjectURL(new Blob([encodeRaster(grid)],{type:'image/tiff'})),link=document.createElement('a');link.href=url;link.download=grid.mask?'fieldwork-clipped.tif':'fieldwork-raster-window.tif';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
